### ISSUE TITLE
Not compatible with StrictMode

### ISSUE THREAD

**Issue by theKashey** [stripe/react-stripe-js#100]
### Summary

We have discovered that this package is not compatible with StrictMode if `sync` mode is used.
Async mode is working without any issues.

### Other information

I've opened an issue for React, as long as it needs some clarification. All detailed are listed there, and I hope solution will be also found there.

https://github.com/facebook/react/issues/19103

**Comment by theKashey** [comment]
In short - you should not use "ref-based" logic. Instead of 
```
 final.current = true; // 👈 this is a problem
      setContext({
        stripe: parsed.stripe,
        elements: parsed.stripe.elements(options),
      });
```
You can use `useReducer`  based logic or even something as simple as 
```
      setContext(oldState => oldState.stripe ? oldState : {
        stripe: parsed.stripe,
        elements: parsed.stripe.elements(options),
      });
```
Which would basically `setState` only once, and would not trigger any re-renders on following invocations.

**Comment by christopher-stripe** [comment]
Hey @theKashey, thanks for reporting. There's some work in progress that should address this (https://github.com/stripe/react-stripe-js/pull/93). I'll make sure to follow up here once it is complete.

**Comment by mxcl** [comment]
Is there a safe workaround? I dislike warnings.
