### ISSUE TITLE
Typescript error for createPaymentMethod

### ISSUE THREAD

**Issue by markusdanek** [stripe/react-stripe-js#114]
### Summary

```
const cardElement = elements.getElement(CardElement);

const { error, paymentMethod } = await stripe.createPaymentMethod({
    type: "card",
    card: cardElement, // type error
});
```

is returning the following Typescript error for `card: cardElement`:

> Type 'StripeCardElement | null' is not assignable to type 'StripeCardElement | StripeCardNumberElement | { token: string; }'.

> Type 'null' is not assignable to type 'StripeCardElement | StripeCardNumberElement | { token: string; }'.

**Comment by hofman-stripe** [comment]
@markusdanek `getElement()` may return `null` if the Element doesn't exist. You either need to test for existence (`if (cardElement)`) or assert the existence if you're sure the Element exists `elements.getElement(CardElement)!;`

**Comment by dominique-raymond** [comment]
I'm having this issue. @hofman-stripe , could you elaborate on how to fix this?

**Comment by juancodev** [comment]
Hi, I was able to solve it as of today as the documentation tells me, using Typescript.

```ts
const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    const payElement = elements?.getElement(CardElement);

    if (!payElement || !stripe) {
      return;
    }

    const result = await stripe.createPaymentMethod({
      type: "card",
      card: payElement,
    });
  };
```

The documentation can be found at the following [link](https://stripe.com/docs/stripe-js/react)
