### ISSUE TITLE
NPM 404

### ISSUE THREAD

**Issue by WillVill** [stripe/react-stripe-js#121]
### Summary

404 error when installing through NPM.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@stripe%2freact-stripe-js - Not found
npm ERR! 404
npm ERR! 404  '@stripe/react-stripe-js@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by EliasRut** [comment]
Same when installing through yarn.

yarn add @stripe/react-stripe-js
yarn add v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@stripe%2freact-stripe-js: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/elias/Code/Lohnbot/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by miraclemaker** [comment]
Am seeing this too. Same for @stripe/stripe-js@1.4.0

**Comment by miraclemaker** [comment]
This is the issue: https://status.npmjs.org/

**Comment by dweedon-stripe** [comment]
Closing since this seems to have been due to an NPM outage rather than a problem with this library.
