### ISSUE TITLE
Example code contradicts TypeScript types

### ISSUE THREAD

**Issue by garybernhardt** [stripe/react-stripe-js#122]
The README contains this example code:

```javascript
const CheckoutForm = () => {
  const stripe = useStripe();
  const elements = useElements();

  const handleSubmit = async (event) => {
    event.preventDefault();
    const {error, paymentMethod} = await stripe.createPaymentMethod({
      type: 'card',
      card: elements.getElement(CardElement),
    });
  };

  ...
}
```

When porting this to TypeScript, Stripe's TS types force three checks not represented in the example:

```typescript
const CheckoutForm = () => {
  const stripe = useStripe();
  const elements = useElements();

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()

    if (stripe === null) {
      throw new Error(`BUG: stripe is null`)
    }
    if (elements === null) {
      throw new Error(`BUG: stripe elements is null`)
    }

    const element = elements.getElement(CardElement)

    if (element === null) {
      throw new Error(`BUG: stripe elements element is null`)
    }

    await stripe.createPaymentMethod({
      type: 'card',
      card: element,
    })
  }

  ...
}
```

The first of those checks (for `stripe`) seems unavoidable: stripe.js might still be loading. (The example handles that by disabling the button while Stripe is loading.)

The other two checks seem to indicate contradictions between the example code and the types. The types say that `useElements` can return `null`. But if that's possible, why isn't it handled in the example code?

Likewise, the types say that the `card` option to `createPaymentMethod` can't be `null`. But `elements.getElement` can return `null`, which the sample code happily passes as a `card` to `createPaymentMethod`. So, again, why isn't the example code handling this error case, if that case is possible?

It seems like either (1) the types are wrong and overly-conservative, or else (2) the example code is wrong and not handling error cases. I think that one or the other should be updated to reflect the actual constraints of the Stripe API. Either give me a nice, clean API, or else give me an awkward API but represent it accurately in the docs. (Now that I've just made my bias clear: I'd much rather have the very-reasonable example code type check with as few additions as possible. I don't want to write a bunch of awkward guards every time I use Elements!)

**Comment by asolove-stripe** [comment]
Hey @garybernhardt: thanks for the report and yikes, this definitely should be better.

The explanation here is that all these functions can, in the general case, have `null` as a return value. But if you've followed the steps in this guide, you have already loaded Stripe.js, created an elements instance and rendered a card element, so these methods will definitely return non-`null` values. We don't have a way to statically analyze that you have done this elsewhere in your code, so we want to both represent the general case in the types, and yet avoid checking impossible cases in our sample code (since it's also used by non-TypeScript users).

There are a few things we are considering to fix this at various layers:
1. Split the README into TypeScript and non-TS versions, so that we definitely provide sample code that type-checks for users who want it.
2. Reduce the number of null checks needed by making the API more powerful. If you could call `useElements(CardElement)` rather than `useElements()` and then separately `.getElement(CardElement)` that's at least one fewer check.

We could also make the return types narrower and say "if you haven't loaded Stripe.js, something else is so terribly wrong there's no point in having our types be correct", but we'd prefer not to do that. We'd also prefer not to check impossible cases in sample code for non-TS users.

**Comment by garybernhardt** [comment]
I like the sound of (2).

I also like the sound of narrowing the types! I think that you can do at least some of it without breaking anything. Here's an example from the README:

```typescript
const {error, paymentMethod} = await stripe.createPaymentMethod({type: 'card', card})
```

The declared type for this is currently underconstrained, which is why all TS code using this function has to include a useless check on `paymentMethod`'s definedness even after `error` is known to be [un]defined. Here's the type:

```typescript
    createPaymentMethod(
      paymentMethodData: CreatePaymentMethodData
    ): Promise<{paymentMethod?: PaymentMethod; error?: StripeError}>;
```

That says "you can get a payment method and an error, or only one of them, or both of them". But the truth is that (I have to assume) you always get a payment method XOR an error. If that's true, the correct type should be:

```typescript
    createPaymentMethod(
      paymentMethodData: CreatePaymentMethodData
    ): Promise<{paymentMethod: PaymentMethod; error: undefined} | {paymentMethod: undefined; error: StripeError}>;
```

(But, with that said, this type is awkward. I think it would make much more sense to throw an exception in the error case. Then the function's return type would simply be `PaymentMethod`, with no object wrapping it, no possibly-undefined values, and no union. Much easier to reason about, whether you're using TS or not. And, unlike the current API design, it's impossible to silently ignore that error unless you intentionally write a `catch { }`. I know that some of Stripe's Node APIs throw exceptions on error, so throwing would also resolve an inconsistency across the various Stripe APIs.)

**Comment by asolove-stripe** [comment]
We're working on this at the moment and hope to do the first part for sure.

The second part (throwing an exception) is unfortunately probably only doable as an opt-in feature. While it forces exception checking for TypeScript users, which is nice, it also results in exceptions being thrown in an async promise context, which is really tricky for non-TS and non-expert users to debug. This is pointing us in a direction we haven't explored, of actually having a different API shape for TS and non-TS users.

**Comment by dweedon-stripe** [comment]
Hi @garybernhardt,

We just shipped a [new version of @stripe/stripe-js](https://github.com/stripe/stripe-js/releases/tag/v1.13.1) that fixes the return types of methods like `createPaymentMethod`. You can now do the following without errors or assertions:

```ts
const res = await stripe.createPaymentMethod(data);

if (res.error) {
  console.log(res.error.code);
} else {
  // No need to make a redundant check for res.paymentIntent
  console.log(res.paymentIntent.id);
}
```

**Comment by garybernhardt** [comment]
Thanks for the update. I still see the same type errors, but my card object is coming from @stripe/react-stripe-js which may be why. That project hasn't seen a release in 7 days, so I guess this change hasn't propagated to that package yet? (I just tested with @stripe/stripe-js 1.13.1 and @stripe/react-stripe-js 1.3.0, both current as I write this.)
