### ISSUE TITLE
Need to change the placeholder of the CardElement base on the website language

### ISSUE THREAD

**Issue by thomaslc66** [stripe/react-stripe-js#123]
### Summary

I want to change the placeholder of the CardElement based on the language of my website

1h I've been searching on the doc... No info, no example.
Then, here on this issue #120 I've seen that only CardNumberElement can have a placeholder in option element

Is there a way to have it in another language or are we stuck with the default one of the components?

**Comment by ellamurii** [comment]
hi @thomaslc66 
I'm new to stripe and we are currently using it. This might help.
loadStripe function takes in an option object.
`loadStripe(<api_key>, { locale: 'de'});`

That works fine but I eventually ended up using  CardNumberElement, CardExpiryElement, CardCvcElement. and just used the options props for the placeholder as we are using _useTranslation from react-i18next_

**Comment by asolove-stripe** [comment]
Hi @thomaslc66 and thanks @ellamurii for the answer!

As @ellamurii pointed out, providing the locale explicitly should mean that Stripe loads text localized for that language. (If there's any trouble with that, please let us know!)

We don't currently support custom placeholders in the combined Element. Its layout is complicated and we had some early users provide naive placeholders that didn't fit in the provided space in all cases. 

I'd encourage you to start with Stripe's built-in localizations. If you have any problems with them, please let us know!

**Comment by asmaboussabat90** [comment]
Hi @asolove-stripe , im passing the locale as an option in loadStripe function. The text is localized as expected but when i switch the language (language switcher) this won't be reflected on the placeholders because obviously Stripe needs to be re-loaded with i18n.language as an option . LoadStripe is `useEffect ` is not recommended. 
Any solution to this ?

**Comment by dweedon-stripe** [comment]
@asmaboussabat90 

For this case you can actually set locale on `Elements` and pass the current locale as a `key` to the <ElementsProvider> to make sure React triggers a re-render. Here is a quick example:

[Example](https://codesandbox.io/s/react-stripe-js-forked-utfyv?file=/src/index.js)

**Comment by GtzRicky** [comment]
> 

Hello, I'm wonrking on a cardElement, and react i18n. How can I change the placeholder according to useTranslation? Could you show me any example, pls? Thanks!

**Comment by GtzRicky** [comment]
> That works fine but I eventually ended up using CardNumberElement, CardExpiryElement, CardCvcElement. and just used the options props for the placeholder as we are using _useTranslation from react-i18next_

Hello, @ellamurii  I'm wonrking on a cardElement, and react i18n. How can I change the placeholder according to useTranslation? Could you show me any example, pls? Thanks!
