### ISSUE TITLE
React Stripe Chrome 80(SameSite issue blocking CORS with stripe.com)

### ISSUE THREAD

**Issue by Pavelbure34** [stripe/react-stripe-js#124]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md)!

### Summary
I am developing on the react app made with "create-react-app"
and the backend server is in Django and Docker. There is no express.js whatsoever.
After wrapping the checkout form within Elements and loading CardElement in component,
I always get CORS blocked due to SameSite issue by the
browser. Here is the error page.

I have included <script src=".../v3/"></script> tag in the header of the index.html.
I have reproduced the error by setting up checkout form into the Elements
and mount CardElement in the CheckoutForm.
and do "yarn start" and get this error.

### Other information

<img width="587" alt="Screen Shot 2020-08-13 at 7 58 54 AM" src="https://user-images.githubusercontent.com/44696888/90076807-a3d9f280-dd3b-11ea-9fbe-55823e52c9e3.png">
<img width="587" alt="Screen Shot 2020-08-13 at 7 59 09 AM" src="https://user-images.githubusercontent.com/44696888/90076818-aa686a00-dd3b-11ea-8ad1-da952fca7f83.png">
<img width="587" alt="Screen Shot 2020-08-13 at 7 58 40 AM" src="https://user-images.githubusercontent.com/44696888/90076835-b0f6e180-dd3b-11ea-9083-2c6eb718cc68.png">
<img width="558" alt="Screen Shot 2020-08-13 at 7 55 03 AM" src="https://user-images.githubusercontent.com/44696888/90076853-b8b68600-dd3b-11ea-8120-3d20c99c3ca5.png">
<img width="677" alt="Screen Shot 2020-08-13 at 7 55 59 AM" src="https://user-images.githubusercontent.com/44696888/90076859-bc4a0d00-dd3b-11ea-9be0-ea5d04b0194d.png">
<img width="286" alt="Screen Shot 2020-08-13 at 7 56 34 AM" src="https://user-images.githubusercontent.com/44696888/90076866-bf44fd80-dd3b-11ea-9309-decce2b29390.png">

I have tried this in Chrome, Firefox, and Safari and all had the same issue.

**Comment by christopher-stripe** [comment]
Hi @Pavelbure34, this looks like a bug with your integration—could you contact [Stripe Support](https://support.stripe.com/contact) instead? We use the GitHub issues only for bugs in the library itself.

In any case, it looks like the first error is what is most immediately causing this to break ("Can only create one Element of type card"). Perhaps you meant to use the `CardNumberElement`, `CardCvcElement`, and `CardExpiryElement` instead of multiple `CardElement` instances.
