### ISSUE TITLE
CORS exception for CardNumberElement on Google Chrome

### ISSUE THREAD

**Issue by FredChauviere** [stripe/react-stripe-js#125]
Am I the only one to get those kind of errors in the Development console logs on Google Chrome?

> Uncaught DOMException: Blocked a frame with origin "https://m.stripe.network" from accessing a cross-origin frame.
>     at <anonymous>:1:16

They don't seem critical, in the sense that everything seems to work properly (I can "talk" to the Stripe Server, and even register Test Cards and Real Cards), but they are really annoying !!!

I understand that HTML frame are very tricky about CORS but I also know that it's react-stripe-js that implement iframe inside the render of CardNumberElement, CardExpiryElement, CardCvcElement, so my understanding is that there's a not a great deal I can do...

### Summary

I basically implemented the example from https://github.com/stripe/react-stripe-js#using-class-components, with replacing CardElement with separated CardNumberElement, CardExpiryElement, CardCvcElement

### Other information

It seems OK on Firefox and Edge, or at least those errors are not transmitted to the console.

**Comment by christopher-stripe** [comment]
@FredChauviere That does sound annoying, and definitely should not be happening. I tried reproducing on Google Chrome 84.0.4147.125 with the `CardNumberElement` in a simple React Stripe.js integration, but I don't see any errors of the sort. Would you happen to have a reproducible sample that we could try? Also would be great to know what version of Chrome you see this error on.

**Comment by hofman-stripe** [comment]
Also, are you able to reproduce the error in an incognito window? It's possible a Chrome extension is interfering with some of our iframes.

**Comment by FredChauviere** [comment]
Thank you Mathieu and Christopher for your quick feedbacks.
Mathieu, you were right, I got absolutely 0 errors in Incognito mode, so it definitely comes from one of my Chrome Extension.

After further analysis it was "Ripple emulator" Chrome extension (emulation of a mobile environnement).
Lesson learn!
