### ISSUE TITLE
Styling the input box

### ISSUE THREAD

**Issue by stvhanna** [stripe/react-stripe-js#129]
### Summary

The style documentation list styling for the input text (https://stripe.com/docs/js/appendix/style?type=card). Is it possible to style the input box itself? I'd like to add css styling to emulate material ui form styling (basic border-bottom, nothing else). The default style is too plain and might not fully indicate the box is an input box. See screenshot below.

### Other information
![stripe-card](https://user-images.githubusercontent.com/507482/93514767-993fe980-f8f5-11ea-9b2b-f19a5e9dae5c.png)

**Comment by christopher-stripe** [comment]
You can style the containing div as if it were an input. Some more detail about this here: https://stripe.com/docs/js/element/the_element_container
