### ISSUE TITLE
Is there a way to change placeholder color on CardElement input focus?

### ISSUE THREAD

**Issue by kevinswartz** [stripe/react-stripe-js#131]
Hi Guys,
Great library!  Thanks for your help!

For our purposes we have a stripe CardElement in which we toggle the background color of the input from transparent to white on focus.  I have things working pretty well except for the placeholder color, which stays white after focusing, making it invisible.  I'm trying to do this using the CardElement style object (below).  It looks like there is no way to change the placeholder color on focus independently of CardElement state.  It would also be nice to change the card icon color on focus.

Is there another way to approach this that gives me better control of styling?  I'd love to just use CSS here if I could.

Here's my current element block and style object:
```
<CardElement className={cardElementCls}
                       onChange={this.onCardElementChange.bind(this)}
                       onFocus={this.onCardElementFocus.bind(this)}
                       onBlur={this.onCardElementBlur.bind(this)}
                       options={{
                         iconStyle: 'solid',
                         style: {
                           base: {
                             fontSize: '16px',
                             lineHeight: '1.5',
                             '::placeholder': {
                               fontSize: '14px',
                               color: colors.SECONDARY_TEXT,
                             },
                             ':focus': {
                               backgroundColor: colors.LIGHT,
                               color: colors.PRIMARY,
                             },
                           },
                           empty : {
                             color: colors.LIGHT,
                             backgroundColor: colors.TRANSPARENT,
                             '::placeholder': {
                               color: colors.LIGHT,
                             },
                             ':focus': {
                               backgroundColor: colors.LIGHT,
                               color: colors.PRIMARY,
                           },
                           },
                           invalid: {
                             color: colors.ASSERTIVE,
                             backgroundColor: colors.LIGHT,
                           },
                           complete:{
                             backgroundColor: colors.LIGHT,
                             color: colors.PRIMARY,
                           }
                         },
                       }}/>
```
Thanks again!

**Comment by dweedon-stripe** [comment]
Hi @kevinswartz,

Sorry for the late reply. Unfortunately, there isn't a way to do this today. The reason we expose the JavaScript styling API is that the components actually use iframes under the hood. We use iframes to help keep your payment flow [PCI compliant](https://stripe.com/docs/security/guide#validating-pci-compliance).

I am going to file this as a feature request it in our internal tracker and will post updates here if we anything to share. In the meantime, I'm going to close out this GitHub issue because this issue tracker is for bugs with React Stripe.js specifically.

**Comment by mschouhan123** [comment]
For **Stripe** in **React Native** you can check here

https://stackoverflow.com/a/74994215/15204127
