### ISSUE TITLE
Failed to load stripe.js

### ISSUE THREAD

**Issue by sosickstudio** [stripe/react-stripe-js#139]
I have a Failed to load.js issue randomly happening on my website as of today.

Any idea why ?

**Comment by hofman-stripe** [comment]
Hi @sosickstudio,

From 13:40–15:45 UTC, Fastly, one of our CDN, [experienced an incident](https://status.fastly.com/incidents/zrzxybrbmhps) in 2 of their locations in France, causing elevated Stripe.js errors. This is now resolved.

We apologize for any inconvenience. Please contact [Stripe support](https://support.stripe.com/contact) if you have any further questions.
