### ISSUE TITLE
Please add a usage example for Connect

### ISSUE THREAD

**Issue by bionicles** [stripe/react-stripe-js#14]
### Summary

I'd like to put Connect on a react app but there's no example. The only example is for a swift app

Would it please be possible to add a usage example of react-stripe-js to make a stripe connect app?

Then it would be much easier to develop web platform marketplace type things...

**Comment by dweedon-stripe** [comment]
Hi @bionicles,

We can look into including a basic example of Connect usage, but walking through a full Connect integration is out of the scope for what we want to include in this repo. 

I have forwarded your request on to our docs team, and we will look at adding an example of how to use this library with Connect in our official docs after we have done a general release of this library.

**Comment by dominiceden** [comment]
@bionicles This is probably 2 years too late, but I too have noticed Stripe docs are pretty poor for Connect usage. I can't see any guides at all for using react-stripe-js with Connect.

However, I managed to work it out myself - the key is creating the PaymentIntent for a specific Stripe account ID (i.e. the connected Stripe account, NOT the platform account) and initialising the Stripe object with that connected Stripe account ID. 

It might look something like this:

```
let stripePromise = loadStripe(getStripeConnectAccountPublishableKey(), {
        stripeAccount: stripePaymentIntent.stripe_account_id, // the connected account ID
      });

      return (
        <Elements
          stripe={stripePromise}
          options={{
            clientSecret: stripePaymentIntent.payment_intent_client_secret,
          }}
        >
          <StripePayment />
        </Elements>
      );
```

As with many Stripe docs, they don't connect the dots. https://stripe.com/docs/js/initializing provides more info on initialising the Stripe object.
