### ISSUE TITLE
idealBankelement can not click arrows

### ISSUE THREAD

**Issue by PixelMonsters** [stripe/react-stripe-js#141]
### Summary

In the idealBankElement you can not click the arrows on the right side. 
Its also in the CodeSandbox example. If i add with element inspection **pointer-events: none** it's works

![image](https://user-images.githubusercontent.com/22601671/101263292-724ec200-3744-11eb-9d61-dea5f45b0b75.png)

**Comment by tylersmith-stripe** [comment]
Thanks for pointing this out @PixelMonsters!

That's certainly a UX detail we can address. We'll follow-up here when it's been updated.

**Comment by tylersmith-stripe** [comment]
The fix for this has been shipped! 🚢 

Thanks again for letting us know about the issue, @PixelMonsters.
