### ISSUE TITLE
CardElement does not render on Safari (Mobile/Desktop) 

### ISSUE THREAD

**Issue by maoryadin** [stripe/react-stripe-js#145]
### Summary

CardElement Compoent does not render on safari (Mobile/Desktop) .

### Other information

```
function CardSection() {
    return (
            <CardElement options={CARD_OPTIONS}/>
    );
};
```

Edit:

on console i am getting:

**Error: Unhandled Promise Rejection: IntegrationError: Live String.js integrations must use HTTPS.**

This is happening only in Safari.

**Comment by tylersmith-stripe** [comment]
Hi @maoryadin, can you confirm that you are viewing the site via HTTPS in Safari?

If you're only seeing this issue in Safari, but it's working in other browsers, it's possible that you are accidentally viewing the HTTP (non-secure) version in Safari. Assuming you have a valid SSL certificate set up for your site, we'd suggest redirecting all HTTP traffic to HTTPS.

**Comment by maoryadin** [comment]
Thank you,
It was the problem.
