### ISSUE TITLE
Feature Request: Expose Elements Context

### ISSUE THREAD

**Issue by picosam** [stripe/react-stripe-js#146]
It is impossible to access Stripe Elements' context from within a modal -- take a look here for an explanation: https://github.com/mpontus/react-modal-hook/issues/30

Quoting from above:

> In the case of Formik, the library thankfully exposes FormikContext. This enables the modal contents to be wrapped by a FormikContext.Provider component with the value set to the return of the useFormikContext() hook.

It would really be helpful if you can expose `ElementsContext` and `useElementsContext()` in the same way.

**Comment by christopher-stripe** [comment]
From the linked thread, it looks like one solution would be to ensure that the [<Elements>](https://stripe.com/docs/stripe-js/react#elements-provider) is a parent of the `<ModalProvider>` from react-modal-hook. Would that work for you?

**Comment by picosam** [comment]
Thank you for your response Christopher. This is indeed the work around that I'm using right now. The problem with this is that it requires me to put the Elements provider very high up the component tree￼, which is wasteful. This is why I pointed to Formik's method, since that actually resolves the issue without requiring me to wrap the whole component tree with their provider.

**Comment by dweedon-stripe** [comment]
Hi @picosam, given the efforts we make not to trigger re-renders with our provider, you should be pretty safe to mount it fairly high up in your component tree.

Exposing context directly feels like a potential foot-gun that I want to avoid.

**Comment by picosam** [comment]
Thank you @dweedon-stripe -- any tips on how to avoid loading the stripe JS library when I mount it at the root of my application? That is since it's only required when user proceeds to payment, which happens quite rarely in the lifetime of the application usage. Much appreciated.
