### ISSUE TITLE
Please  add classes + stateless functional components examples to readme.

### ISSUE THREAD

**Issue by iMerica** [stripe/react-stripe-js#15]
Hi,

I understand hooks are fashionable in React at the moment, but people have been writing software using classes and stateless functional components for many years now. It makes more sense to optimize the documentation to be helpful to as many people as possible. Meet people where they are; not where you want them to be.

Specific proposal:

- Example using local state with classes
- Example using Stateless functional components and redux.
- Optional Hooks example.

**Comment by danseaman6** [comment]
https://github.com/stripe/react-stripe-elements/#react-stripe-elements

This is their legacy library, fully supported and mentioned in the README.

**Comment by iMerica** [comment]
Classes are not legacy, they are part of everyday usage of React and are not going anywhere.

The React blog states the same

https://reactjs.org/docs/hooks-intro.html

**Comment by danseaman6** [comment]
My point is that if you're looking to use a stripe library with classes, there it is.

**Comment by Tassfighter** [comment]
They have hooks and class-components in the example folder.

**Comment by dweedon-stripe** [comment]
Hi @iMerica,

This library should work fine with both the Hooks API and traditional class components. We will take a look at updating the readme to make that more obvious. I definitely do not want the impression to be that this library is designed to be Hooks only.

**Comment by iMerica** [comment]
Thank you @dweedon-stripe 🙏
