### ISSUE TITLE
Intermittent appearance of placeholder even when setting it to empty string

### ISSUE THREAD

**Issue by simonsmith** [stripe/react-stripe-js#150]
Hello,

A recent problem we've noticed, just like to clarify whether anything has changed with `placeholder` usage.

Here is a fork of the Stripe Elements 'Split card' demo - https://codesandbox.io/s/zqk9q?file=/src/components/demos/SplitForm.js:348-370

Setting `placeholder: ''`

**Expectation**: Inputs have no placeholder
**Actual**: Every couple of refreshes the default placeholders will appear

We noticed this recently as visual regression tests have started failing, that have always passed.

You can try it here - https://zqk9q.csb.app/split-card-elements

Here is a visual example:

![2021-01-15 11 39 32](https://user-images.githubusercontent.com/360703/104727464-46ecc900-572d-11eb-835b-09887fe883be.gif)

Thanks!

**Comment by givehug** [comment]
We have the same issue

**Comment by christopher-stripe** [comment]
Hi @simonsmith @givehug, thanks for reporting. We have a fix for this issue and will roll it out later today. I'll follow up here when the fix has been published.

**Comment by christopher-stripe** [comment]
The fix is now live, and I verified the issue no longer occurs in reproduction above. Thanks!
