### ISSUE TITLE
Unsecure implementation - Private key exposed with stripePromise

### ISSUE THREAD

**Issue by adriadrop** [stripe/react-stripe-js#155]
I am confused that in examples you are using this line below which will make private key visible to any user, point would be to keep PK secure
`const stripePromise = loadStripe('pk_test_6pRNASCoBOKtIshFeQd4XMUh');`

I was thinking implementation would be that React has public key, sends it to backend that keeps private key and with private key there we get client secret and then send that to react and react can use that then.

**Comment by thetrevdev** [comment]
That pk is public key versus sk for secret key.

https://stripe.com/docs/keys#obtain-api-keys

**Comment by adriadrop** [comment]
Sorry, was consfused :) I just realized myself
