### ISSUE TITLE
typeError i.postMessage is not a function

### ISSUE THREAD

**Issue by Etto91** [stripe/react-stripe-js#157]
i got this error

{"error":"TypeError: i.postMessage is not a function. (In 'i.postMessage(JSON.stringify(se({},e,{__stripeJsV3:!0})),a)', 'i.postMessage' is undefined)","info":{"componentStack":"\n in CardExpiryElement

{"error":"TypeError: i.postMessage is not a function. (In 'i.postMessage(JSON.stringify(se({},e,{__stripeJsV3:!0})),a)', 'i.postMessage' is undefined)","info":{"componentStack":"\n in CardNumberElement

{"error":"TypeError: i.postMessage is not a function. (In 'i.postMessage(JSON.stringify(se({},e,{__stripeJsV3:!0})),a)', 'i.postMessage' is undefined)","info":{"componentStack":"\n in CardCvcElement

in a react website.

this is the website user agent

Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 172.0.0.22.118 (iPhone11,8; iOS 14_3; it_IT; it-IT; scale=2.21; 828x1792; 269286904)

i'm using 1.1.2v

I can't understand why i got this error.

does anyone have any idea what it could be?

thanks

**Comment by hofman-stripe** [comment]
We've seen a few reports of this issue on iOS 14.3+ but haven't been able to reproduce. Do you happen to have a consistent reproduction by any chance? We haven't changed anything that would cause this so right now we suspect a change in WebKit.

**Comment by Etto91** [comment]
i'll try to reproduce it with ios simulator

**Comment by Etto91** [comment]
I can't reproduce the error

**Comment by tylersmith-stripe** [comment]
Thank you for trying to reproduce and reporting back. We're continuing to look into this one.

**Comment by dweedon-stripe** [comment]
We are actively looking into this. The issue is not widespread but we have seen sporadic reports. A consistent reproduction would be extremely helpful.

**Comment by tylersmith-stripe** [comment]
Hey @Etto91 👋 ,

We deployed a fix for this error, and you shouldn't see any future occurrences of it. Feel free to re-open this issue if the problem continues on your side of things. Thank you for flagging this to us!

**Comment by Etto91** [comment]
Ty
