### ISSUE TITLE
Safari Mobile keeps virtual keyboard open on submit.

### ISSUE THREAD

**Issue by smilank3** [stripe/react-stripe-js#158]
clicking on pay button does not hide the keypad and it keeps opening up when clicked on other buttons. please try you example on iphone (ios)  if you don't believe me.

clicking 'Done' keypad button before clicking 'pay' button works fine but clicking 'Done' button after 'pay' and whatever button you click will reopens the number keypad.

follow these steps for testing.
1. go to codesandbox (iphone , ios devices please) https://codesandbox.io/s/react-stripe-official-q1loc?fontsize=14&hidenavigation=1&theme=dark
2. fill the field and click 'Done' keypad and click 'pay'. it works great.
3. again click 'pay' button, no pop ups.
4. now refresh the page and fill the field
5. click 'pay' button . do not click 'Done' keypad yet. Clicking 'pay' button wont hide the keypad.
6. now click 'Done' keypad.  problem solved right?.  Nope. 
7.now click 'pay' button again (or any input field. click 'Options' above), you will see keypad pop up out of nowhere.

my issue: 
wherever i click on my website, keypad pops up.

**Comment by smilank3** [comment]
This issue was discussed here too.https://github.com/stripe/react-stripe-elements/issues/174
 i am using iphone 6 . ios 12.x. please

**Comment by tylersmith-stripe** [comment]
Hi @smilank3 👋 ,

I tried reproducing this issue with on iPhone/iOS, but was unable to. I'll try reproducing on iPhone 6/iOS 12 and follow-up here.
