### ISSUE TITLE
Failed to load stripe.js

### ISSUE THREAD

**Issue by sdankel** [stripe/react-stripe-js#159]
Similar to this: https://github.com/stripe/react-stripe-js/issues/139

This happens frequently in our app. Is this a known issue?

**Comment by hofman-stripe** [comment]
There are currently no known issue besides transient network connectivity problems in customer devices.

Can you define "frequently"? With what frequency does this happen? Is there specific environments (browser, geolocation, etc.) or time where this seem to happen more often?

**Comment by sdankel** [comment]
We've seen this error up to 4x/day. It's happened 40 times since January 11. It happens on Chrome, Safari, and Firefox across Mac, Windows and iPhone (no instances of Android yet). There's no clear pattern around when it happens, other than it's during business hours when most of our customers are online.

The errors are triggered when users load pages that do not have any react-stripe elements. 

It makes sense that it'd be due to customers' having network connectivity issues. Do you have any examples of how to use `Stripe-Should-Retry` with stripe react elements? Thank you.

**Comment by hofman-stripe** [comment]
Depending on your overall load volume, 4x/day might be low or high.

There is no retry logic in the `@stripe/stripe-js` loader. If you're on a page where this happens, one solution if to force a refresh if the promise returned by `loadStripe` rejects. However you can probably expect your customers to try refreshing themselves as well if they had a bad connection and the page partially loaded.

**Comment by sdankel** [comment]
Thanks. It sounds like this is to be expected as long as the error volume stays relatively low. I'll close this out.

**Comment by sladg** [comment]
Hey,
I would like to follow up on this.

We are seeing this issue for some time now, unable to figure out what to do about it. There is a bit of pattern.

99% of issues happen on the following configuration:
- Apple device (iPhone, iPad, Mac, Macbook),
- Happens on Safari 12, 13, 14 - older versions, nothing current

![image](https://user-images.githubusercontent.com/26263265/121878950-95b68300-cd0c-11eb-90cd-a25b4fcbac08.png)
![image](https://user-images.githubusercontent.com/26263265/121878974-9d762780-cd0c-11eb-8d8d-61703cf15e7c.png)

It happens on load (using Next.js) in `_app.tsx`. Seems to be not happening during the checkout process (probably just way lower traffic, so no issues there so far).

**Comment by sladg** [comment]
Any news/updates on this @christopher-stripe @hofman-stripe?

**Comment by mscandal** [comment]
would be great to have retry logic baked in. we're seeing about 100 of these a day right now

**Comment by wobsoriano** [comment]
Here you go https://github.com/wobsoriano/retry-stripe-loader

**Comment by arodik** [comment]
I still have this issue, even with retries :(

**Comment by yashraut19** [comment]
Facing the same issue on chrome win10

**Comment by cyzanfar** [comment]
same issue for Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
