### ISSUE TITLE
Content Security Policy Issue

### ISSUE THREAD

**Issue by bejzik8** [stripe/react-stripe-js#166]
Greetings folks,

I have an issue, when building my app I get this error. My Stripe elements are not showing, anyone knows how can I fix this?

_Refused to load the script 'https://js.stripe.com/v3' because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-wH2mO/2byxNv16xIx2x3eYPsMIhIJvNPadMOkl/ti38=' https://ssl.google-analytics.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback._

![Capture](https://user-images.githubusercontent.com/24759563/110483352-ee60f900-80e9-11eb-8117-7ba8a816d342.PNG)

Thank you.

**Comment by christopher-stripe** [comment]
Hi @bejzik8, it looks like you need to configure your content security policy to allow Stripe.js: https://stripe.com/docs/security/guide#content-security-policy

Going to close this as this sort of question is better directed towards Stripe Support. We keep this issue tracker for bugs with the React Stripe.js specifically.
