### ISSUE TITLE
Is there a way to make CardCvcElement to be displayed with dots (type='password')

### ISSUE THREAD

**Issue by Delagardi** [stripe/react-stripe-js#167]
I want to change CVC code from plain number to dots (as password).

I found [an issue ](https://github.com/stripe/react-stripe-elements/issues/328) in old react-stripe-elements repo.
> Most online checkout forms don't mask out the CVC number. The PCI and other appropriate standards also don't recommend doing so.

and

> there is no way to do this with Stripe Elements.

1) Does **react-stripe-js** have an option to change cvc input to dots?
2) Maybe someone have a link to PCI standard where this behavior is not recommended? I couldn't find any information about this.

**Comment by graceg-stripe** [comment]
Hi @Delagardi, React Stripe.js does not have an option to hide CVC input. We are tracking this feature request internally, but haven’t prioritized any work on it yet. We’ll follow up on this GitHub issue if we have any updates.

Going to close this issue in the meantime, as we keep this issue tracker for bugs with the React Stripe.js specifically.

**Comment by jimthedev** [comment]
> Hi @Delagardi, React Stripe.js does not have an option to hide CVC input. We are tracking this feature request internally, but haven’t prioritized any work on it yet. We’ll follow up on this GitHub issue if we have any updates.
> 
> Going to close this issue in the meantime, as we keep this issue tracker for bugs with the React Stripe.js specifically.

Thanks for tracking this. We are a med-larger size company and currently onboarding to Stripe. Our security team is asking if we can add our name to the list of people asking for this. Thanks!

**Comment by djayaram1995** [comment]
Hi @jimthedev  Is there any update on this fix. Clients are posting this problem as a grave security issue since the person next to the person who pays can see all the necessary payment information and even can take photograph and use the card illegally.

**Comment by IonelLupu** [comment]
I found a ton of issues about this. Any updates or temp fixes for this? @graceg-stripe  @jimthedev

**Comment by osroca** [comment]
Yeah! I'm also looking for something to mask user's input in the card number or cvc. 
Paypal card field has a maskInput option where one can define the mask character and whether to show the last 4 digits when the card input field loses the focus.

**Comment by troyschneringer** [comment]
Is there a way to re-open this issue?  A third party integration is requesting masked inputs for credit card numbers.
