### ISSUE TITLE
Set hidePostalCode on CardElement not working

### ISSUE THREAD

**Issue by Tassfighter** [stripe/react-stripe-js#17]
Example:
`<CardElement hidePostalCode />`

It works for me with the legacy react-stripe-elements.

**Comment by dweedon-stripe** [comment]
👋 Hi @Tassfighter,

All of the Element's options have moved to a general `options` prop. This creates a cleaner separation between [React Stripe.js specific props](https://stripe.com/docs/stripe-js/react#element-props) and [Element options](https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options).

To fix your specific issue, move `hidePostalCode` into the `options` prop.

```jsx
<CardElement options={{hidePostalCode: true}} />
```
