### ISSUE TITLE
Use refs for stripe elements

### ISSUE THREAD

**Issue by williamsidewalk** [stripe/react-stripe-js#171]
Hello,

I have a _hybrid_ form, which has _stripe elements_ and _"vanilla" html inputs_.

I'm trying to validate that my button will **only** submit if all `stripe elements` are filled and validated, I was thinking of using r`e`fs but I am not seeing a `ref` `prop` on the stripe elements.

Is there something I'm missing or does someone else has a better approach?

**Comment by christopher-stripe** [comment]
Hi @williamsidewalk, how were you planning on using a `ref` if it was available?

You can use the [onChange handler](https://stripe.com/docs/js/element/events/on_change?type=cardElement#element_on_change-handler) to listen to changes in validation state from an Element. How exactly you use these events depends on what your particular integration looks like (i.e., your general approach to form validation in React).
```jsx
<CardElement onChange={({empty, complete, error}) =>  {/* ... */}} />
```

**Comment by holdMyTea** [comment]
Hi, wanted to add my use-case here.

I also have mixed form with regular HTML inputs and `react-stripe-js` components. I wanted to automatically focus next field in the form, once the previous is valid and complete. However, passing a ref into `CardExpiryElement`, for example, won't work, and will drop the following error in the console:

> react-dom.development.js?61bb:67 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Comment by christopher-stripe** [comment]
Hi @holdMyTea, you can obtain a reference to an Element instance by calling [elements.getElement](https://stripe.com/docs/js/elements_object/get_element). The Element can then be focused by calling [element.focus](https://stripe.com/docs/js/element/other_methods/focus).

Not sure exactly what your form implementation looks like, but in context that technique might look like this:

```js
const Form = () => {
  const elements = useElements();

  const handleInputCompleted = () => {
    const cardNumberElement = elements.getElement('cardNumber');
    cardNumberElement.focus();
  }

  // ...
}
```

**Comment by bui-stripe** [comment]
Hi! This looks like it's been resolved, closing out the issue for now.

**Comment by PsyGik** [comment]
@bui-stripe technically this hasn't been resolved as the OP asks if there is a way to get the `ref` for the elements. 

I am on the same boat where I use [React Hook Form](https://react-hook-form.com/), for form validation. Translating to code, it looks something like:

```jsx
<input
  type="text"
  id={identifier}
  name={identifier}
  placeholder={placeholder}
  ref={registerRef({
    required: {
      value: true,
      message: MESSAGES.error.required,
    },
  })}
/>;
```

Assuming an ideal case where `ref` is available on the `CardNumberElement`

```jsx
<CardNumberElement
  options={options}
  className="card-element"
  id="cardnumber"
  ref={registerRef({
    required: {
      value: true,
      message: MESSAGES.error.required,
    },
  })}
/>;

```
We can't use it this way because, 
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

Any pointers appreciated

**Comment by brandondurham** [comment]
I’m in the same boat as @PsyGik. I’m using CardElement and trying to register as an input with react-hook-form:
```jsx
<Controller
	control={ control }
	name={ name }
	render={ ({ field }) => (
		<StyledCardElement { ...field } />
	) }
/>
```

**Comment by christopher-stripe** [comment]
Hi @PsyGik and @brandondurham, the `<CardElement />` doesn't render an `<input />` in a way that can be accessed by React Hook Form. For security and regulatory reasons, it instead renders an `<iframe>` which loads an isolated page containing an input. There is no way to pass a ref for an input across the `<iframe>` boundary, which is why we do not support a `ref` option in React Stripe.js.

**Comment by PsyGik** [comment]
@brandondurham Exactly what @christopher-stripe said. To solve my problem, I ended up creating a custom component and a HoC to wrap Stripe elements. Basically the layout looked like:

```
CustomInput:

<div>
<StripeElement/>
<span>{error}</>
```

The HoC:

```js
/**
 * A HoC that takes a StripeElement as prop and returns a component
 * ready with validation for user events
 * @param ElementComponent
 */
 function withStripeElementValidation(ElementComponent) {
    return ({
      name,
      inputProps,
      ...props
    }) => {
      const [elementError, setElementError] = useState(errorProp);
      const onReady = () => {};
      const onFocus = () => {};
      const onBlur = () => {};
      const onChange = ({ elementType, error, complete }) => {
        setElementError(error?.message);
      };
      return (
        <CustomInput
          name={name}
          error={elementError}
          errorMessage={elementError}
          {...inputProps}
          stripeElement={
            <ElementComponent
              onReady={onReady}
              onChange={onChange}
              onFocus={onFocus}
              onBlur={onBlur}
              control={props.control}
              {...props}
            />
          }
        />
      );
    };
  }
  
  /**
   * Using the above HoC, we create Stripe components and use them in the form below.
   */
  const CardNumberWithValidation = withStripeElementValidation(CardNumberElement);
  const CardCodeWithValidation = withStripeElementValidation(CardCvcElement);
  const CardExpiryWithValidation = withStripeElementValidation(CardExpiryElement);
  ```

This worked for our use-case, and was easy to test. YMMV.

**Comment by everdrone** [comment]
I'm also using `react-hook-form` for validation but cannot find a way to use the elements as controlled components

Any advice is welcome
