### ISSUE TITLE
Stripe CardElement iframe does not load in Playwright test

### ISSUE THREAD

**Issue by reidbuzby** [stripe/react-stripe-js#172]
### Summary

I have a simple credit card form in my application that uses Stripe Elements that looks something like this:

```javascript
import { Elements, CardElement } from '@stripe/react-stripe-js';

function CardForm() {
  const [stripe, setStripe] = useState(null);

  useEffect(() => {
    setStripe(Stripe(<stripe_key>));
  });

  return (
    <div>
      <script src="https://js.stripe.com/v3/" />
      <Elements stripe={stripe}>
        <CardElement />
      </Elements>
    </div>
  );
}
```

I am also using Playwright to run e2e tests on my application in a headless Chromium browser. One of the tests fills out the credit card form. Part of that tests looks like this:

```javascript
const frames = page.frames();

// Find the stripe credit card iframe
const cardFrame = find(f => f._name.startsWith('__privateStripeFrame')(frames);

await cardFrame.fill(
  '[data-elements-stable-field-name="cardNumber"]',
  card.number
);
await cardFrame.fill(
  '[data-elements-stable-field-name="cardExpiry"]',
  `${card.exp_month}/${card.exp_year}`
);
await cardFrame.fill(
  '[data-elements-stable-field-name="cardCvc"]',
  card.cvc
);
await cardFrame.fill(
  '[data-elements-stable-field-name="postalCode"]',
  '12345'
);
```

When I run my test locally (in headless mode), everything works perfectly and the Stripe CardElement iframe loads and gets filled successfully. However, when I run my test in Github Actions as a workflow, the iframe fails to render. Even if I wait 10+ seconds, the iframe never gets loaded. I am getting some sort of error in the `useEffect` where I call `setStripe`, but all that logs is `JSHandle@error`. I think it could be an issue loading the Stripe script from a different domain so I added a bunch of args to my browser setup as some similar posts have suggested:

```javascript
browser = await chromium.launch({
  headless: IS_HEADLESS,
  chromiumSandbox: false,
  args: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-web-security',
    '--disable-features=IsolateOrigins,site-per-process',
    '--disable-site-isolation-trials',
    '--allow-running-insecure-content',
    '--ignore-certificate-errors',
    '--allow-insecure-localhost'
  ]
});
```
But none of these have fixed the issue. Again, this only happens in CI and never reproduces locally. I have enabled screen recordings for the CI tests to see exactly what is going on, and the CardElement iframe just never renders. Here is a screenshot of the state it gets stuck in:

<img width="521" alt="Screen Shot 2021-04-08 at 5 26 11 PM" src="https://user-images.githubusercontent.com/19672892/114098710-bd621880-988f-11eb-8426-9c597731c27d.png">

**Comment by reidbuzby** [comment]
I have also tried including stripe as a module instead of including it as a script using `loadStripe`. When I do this, the CardElement does actually load successfully, however when I try to create a token with the successfully inputted card info the `createToken` function hangs forever. Here is my basic function:
```javascript
import { loadStripe } from '@stripe/stripe-js';

const stripe = loadStripe(<stripe_pk>);

async function generateCardToken(card) {
  const res = await (await stripe).createToken(card);

  return res;
};
```
Again, this function works locally without any issues and in the Playwright tests without any issues so I don't think it is a problem with the `generateCardToken` function. It just hangs when running the Playwright tests in Github Actions. The `createToken` call also does not throw an error in this case, it just hangs forever waiting for a response to be returned.

**Comment by vitalyiegorov** [comment]
We have exactly the same problem but with WebdriverIO, have you @reidbuzby Have you found any solution so far?
