### ISSUE TITLE
Minified React error #321

### ISSUE THREAD

**Issue by caranad** [stripe/react-stripe-js#173]
Hi all,

I am currently working on an application and after creating the production build, I get this error stemming from the react-stripe-js module:

![image](https://user-images.githubusercontent.com/16296061/114324113-6a3dcf00-9af6-11eb-85bc-1a141c30e1c8.png)

I've checked the React error page and it seems to me that I'm having duplicate React package instances, based on what I found after running **npm ls react**. From what I know, my application does already have matching versions of react and react-dom, and hook rules are all being followed in my app.

![image](https://user-images.githubusercontent.com/16296061/114324242-12ec2e80-9af7-11eb-9880-b12fbd41aeef.png)

Could anyone provide assistance as to how to move forward with addressing this?

Thanks.

**Comment by caranad** [comment]
bump

**Comment by christopher-stripe** [comment]
Hi @caranad, do you have a way we can reproduce this error?

**Comment by caranad** [comment]
Hi @christopher-stripe ,

Sorry for the delay in response, I hope this reaches you in time. 
The only way I have been able to reproduce this issue is in a private Github repository that I'm currently working on, and I can't make public. Would you be ok if I sent you a zip file of the repository via email or something?

Thanks.

**Comment by caranad** [comment]
False alarm. Your package is not the issue. Closing issue

**Comment by rmakaev** [comment]
Hi @caranad, i have the same problem, can you pls tell how did you solve it
