### ISSUE TITLE
Afterpay not allow in typescript

### ISSUE THREAD

**Issue by Kainkainkain** [stripe/react-stripe-js#174]
Payment_method_type doesn't accept 'afterpay_clearpay' in typescript - unsure which package its defined

**Comment by tylersmith-stripe** [comment]
Afterpay / Clearpay types can be found in [@stripe/stripe-js](https://github.com/stripe/stripe-js). The types were introduced in [PR#162](https://github.com/stripe/stripe-js/pull/162).

Closing this out for now, please re-open a new issue in that repo if you run into issues those types.

**Comment by tylersmith-stripe** [comment]
Hi @Kainkainkain,

Following up on this, we just published a [new version (1.14.0)](https://github.com/stripe/stripe-js/releases/tag/v1.14.0) of [@stripe/stripe-js](https://github.com/stripe/stripe-js), and you should be able to access the Afterpay/Clearpay types now!

My apologies, I didn't realize the types hadn't been released yet. If you pull down the latest version of that package, you should be all set. 👍

**Comment by Kainkainkain** [comment]
Awesome
