### ISSUE TITLE
`canMakePayment` always returns `null`

### ISSUE THREAD

**Issue by MarkRabey** [stripe/react-stripe-js#176]
### Summary

I'm having trouble getting the button to display. The result from `canMakePayment` is always `null`. Code:

```javascript
React.useEffect(() => {
    if (stripe) {
      const pr = stripe.paymentRequest({
        country: 'US',
        currency: 'usd',
        total: {
          label: 'Demo total',
          amount: 1099,
        },
        requestPayerName: true,
        requestPayerEmail: true,
      });

      pr.canMakePayment().then((result) => {
        if (result) {
          setPaymentRequest(pr);
        }
      });
    }
  }, [stripe]);
```

### Other information

I am using https, although it is on localhost. I'm not sure that has an impact at all or not. I have added payment methods as well.

**Comment by graceg-stripe** [comment]
Hi @MarkRabey, can you confirm that you have a payment method saved in your browser when testing it?  This can either be an apple pay card in Safari, google pay card or browser card in Chrome.

Here is our [API reference](https://stripe.com/docs/js/payment_request/can_make_payment) and `canMakePayment` will resolve to `null` outside our supported cases. You can also double check your setup by visiting [this](https://stripe.com/docs/stripe-js/elements/payment-request-button) documentation, and a button should show up on the top of the page if your have everything setup correctly (see the screenshot attached below).

Thanks!

<img width="915" alt="Screen Shot 2021-04-27 at 12 24 22 PM" src="https://user-images.githubusercontent.com/76074026/116300219-8165f900-a753-11eb-8e2c-a61db0271dfe.png">

**Comment by MarkRabey** [comment]
@graceg-stripe The payment button was **not** showing on the documentation screen. Interestingly, I did have a payment method saved and if I had DevTools emulate a mobile browser the documentation showed the button.. What was missing in my settings seems to be that "Allow sites to check if you have payment methods saved" was disabled. That seems to have resolved the issue. Thanks!

![image](https://user-images.githubusercontent.com/5824577/116440151-2f3dda00-a81e-11eb-8e0e-9fc5215094f1.png)
