### ISSUE TITLE
Working Example of PaymentRequestButtonElement with hooks?

### ISSUE THREAD

**Issue by danseaman6** [stripe/react-stripe-js#18]
I've been working on trying to implement your library, and have run into an issue with the PaymentRequestButton. Working off of your `examples` directory and trimming away some of the extras, I've added the element itself along with the required useState and useEffect hooks (typeScript incoming):

```  
const [
    paymentRequest,
    setPaymentRequest,
  ] = useState<stripe.paymentRequest.StripePaymentRequest | null>(null);

  useEffect(() => {
    const pr = stripe.paymentRequest({
      country: "US",
      currency: "usd",
      total: {
        label: "Demo total",
        amount: 100,
      },
    });
    pr.on("paymentmethod", async e => {
      e.complete("success");
    });

    pr.canMakePayment().then(result => {
      if (result) {
        setPaymentRequest(pr);
      } else {
        setError("something went wrong");
      }
    });
  }, [stripe]);

...
return (
  <div>
        {paymentRequest && <PaymentRequestButtonElement options={{paymentRequest}} />}
  </div>
)
```

From what I can see, this should be enough to get the button to render at the least, but the canMakePayment process is resolving with `null` every time without any additional information. I doubt it's an issue with the TS typing I've added or with how I've implemented the useStripe and useElement hooks, as I've got a fully functioning CardElement on the same page. Since this is a beta library, I can't actually find a fully functioning version of this PaymentRequestButtonElement anywhere else to reverse engineer. If the team has any insights or a working demo, I'd love to see them. 

In case there's any chance it's relevant, I've attached [my thin index.d.ts](https://github.com/stripe/react-stripe-js/files/4067928/index.d.ts.txt) which is extending [@types/stripe-v3](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stripe-v3).

I've been testing on Chrome with a loaded payment method. The Button does render and "work" on [this stripe page](https://stripe.com/docs/stripe-js/elements/payment-request-button#testing) with my testing browser, so that shouldn't be the issue either.

**Comment by dweedon-stripe** [comment]
This indeed should be enough to show the button and I suspect the issue is not with the React Stripe.js. I do not think TS types are an issue here. Are you serving your demo over https somehow?

**Comment by danseaman6** [comment]
Testing has taken place on localhost with a dev stripe key, so no. What effect would that have?

**Comment by dweedon-stripe** [comment]
The underlying wallets/payment handlers that we use have an HTTPS requirement. Can you try serving over https with something like [ngrok](https://ngrok.com/)?

There is a bit more detail about how to get the button to show up here:
https://stripe.com/docs/stripe-js/elements/payment-request-button#html-js-prerequisites

This doc does not yet have React specific content, but the "Prerequisites" section should still apply.

**Comment by danseaman6** [comment]
Yup, that solved it. I missed that bullet point, was spending too much time digging through the new library. Thanks for the help!

**Comment by dweedon-stripe** [comment]
👍
