### ISSUE TITLE
CardElement complete attribute not properly updated

### ISSUE THREAD

**Issue by verena91** [stripe/react-stripe-js#185]
I'm experiencing an issue with the **complete** attribute from the CardElement onChange event (that I'm using to enable/disabled a button). 

For reference, this is the event object:
`
{
  brand: "visa"
  complete: true
  elementType: "card"
  empty: false
  error: undefined
  value: {postalCode: ""}
}
`

The steps for reproducing the issue are:

1. In the card element provide a card number to receive a fail (I'm using this `4000000000000119`)

2. Add any future date for the expiration date

3. Add any number for the CVC

4. Add any number for the ZIP code

5. Press "Update" button

6. After receive the error message delete the card number

7. Paste again the same card number

**Bug**: the button is enabled without the ZIP code (it was automatically deleted in the step 6). This button is enabled because after copy/pasting the card number the **complete** attribute is true.

**Expected**: the **complete** attribute should be false because the zip code field is empty.

**Comment by bui-stripe** [comment]
Hi! We are aware of this issue and are looking into a solution on our side. We will update the ticket when we know more. Thanks!
