### ISSUE TITLE
CardElement expiry details overlaps on smaller screen 

### ISSUE THREAD

**Issue by uday420** [stripe/react-stripe-js#187]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md)!

### Summary

Trying to setup stripe for one of the project in react.

Added default CardElement element without any modification and it seems like the styles on mobile screens are overlapping the card number (see attached image).

Is there a way this can be fixed?

Best -Uday

### Other information

![image](https://user-images.githubusercontent.com/5004573/119124367-7b98c600-ba28-11eb-9df2-3a7c22df2402.png)

Testing Browser : Chrome  Version 90.0.4430.212 (Official Build) (64-bit)
Window 10 Machine.

**Comment by hyjiang7** [comment]
I’m having the same issue. How did you get it fixed?

**Comment by alicerocheman** [comment]
Me too, getting this issue with config:

 ```json
    "react": "^17.0.2",
    "@stripe/react-stripe-js": "^1.7.0",
    "@stripe/stripe-js": "^1.22.0",
```

**Comment by alicerocheman** [comment]
I have the same issue and on my end it's very clear the available space is not the issue, seeing as there is available space remaining on the right side on the input.

![Screenshot 2022-02-22 at 13 07 49](https://user-images.githubusercontent.com/21168856/155129297-f5660879-84fa-4329-a910-7d608dcd8712.png)
