### ISSUE TITLE
How can I get the value of cardNumber in CardNumberElement

### ISSUE THREAD

**Issue by s4mukka** [stripe/react-stripe-js#189]
How can I get the value of cardNumber in CardNumberElement?
I needed to be able to use it together with react-credit-cards.

**Comment by bui-stripe** [comment]
We do not expose the value of sensitive input data from Elements. You can take a look at [change event](https://stripe.com/docs/js/element/events/on_change?type=cardElement) as an example for what info we do expose however. 

Thanks!
