### ISSUE TITLE
Fix useLayoutEffect issue with nextjs SSR

### ISSUE THREAD

**Issue by coodoo** [stripe/react-stripe-js#19]
hey @dweedon-stripe , great work on the new hook version of stripe-js, just played around with it a bit and found a minor issue with server-side rendering using nextjs, here's a modified example that worked perfectly, just FYI.

```js
import React, { useState, useEffect, useRef } from 'react'
import Layout from '../components/layout'
import Head from 'next/head'
import { login, invokeAndRedirect, invoke } from '../utils/api'

import {
 CardElement,
 Elements,
 useStripe,
 useElements,
} from '@stripe/react-stripe-js'

const MyCheckoutForm = () => {
 const stripe = useStripe()
 const elements = useElements()

 const handleSubmit = async event => {
  const { error, paymentMethod } = await stripe.createPaymentMethod({
   type: 'card',
   card: elements.getElement(CardElement),
  })

  console.log( '[result] ', error, paymentMethod )
 }

 // early bailout when on server 👈
 if(typeof window === 'undefined') return ''

 return (
  <div >
   <CardElement />
   <button onClick={handleSubmit}>Pay</button>
  </div>
 )
}

export default () => {
 const [stripe, setStripe] = useState(null)

 useEffect(() => {
  console.log('[set stripe] ', window.Stripe)
  setStripe(window.Stripe('pk_test_XXXX'))
 }, [])

 return (
  <React.Fragment>
   <Head>
    <script src="https://js.stripe.com/v3/"></script>
   </Head>
   <Layout>
    <Elements stripe={stripe}>
     <MyCheckoutForm />
    </Elements>
   </Layout>
  </React.Fragment>
 )
}
```

**Comment by dweedon-stripe** [comment]
Hi @coodoo,

Does it actually break without the early bailout, or just warn about how `useLayoutEffect` does nothing on the server.

**Comment by wesbos** [comment]
Having this problem too - you can't run code with window on the server. I'm at this right now. Seems like it could be wrapped into another in this lib? 

```js
function useStripeObject(key) {
  const [stripe, setStripe] = useState(null);

  useEffect(() => {
    console.log('[set stripe] ', window.Stripe);
    setStripe(window.Stripe(key));
  }, [key]);

  return stripe;
}
// ... 
const stripe = useStripeObject('pk_cool');
```

**Comment by dweedon-stripe** [comment]
You should not need to store it in state though. You can make the stripe instance a local variable to the file:

```jsx
const stripe = typeof window === "undefined" ? null : window.Stripe("pk_test_foo");
```

Alternatively, we just shipped an update that makes async loading very easy and that should work with Next.js as well:

```jsx
import { loadStripe } from "@stripe/stripe-js";
import { Elements } from "@stripe/react-stripe-js";

const stripe = loadStripe("pk_test_foo");

export default () => (
  <Elements stripe={stripe}>
    {/* <YourCheckoutComponent> */}
  </Elements>
);
```

To be clear, I do see the warnings about `useLayoutEffect` and we should make those go away, but it should work either way.

**Comment by wesbos** [comment]
Oh man - I had written that code, but my ternary the wrong way haha. Thank you - much better. I can confirm `const stripe = typeof window === "undefined" ? null : window.Stripe("pk_test_foo");` works without issue on Next.js SSR

**Comment by coodoo** [comment]
@dweedon-stripe 

> Does it actually break without the early bailout, or just warn about how useLayoutEffect does nothing on the server.

Nope, not breaking anything, just showing warnings about useLayoutEffect, the early bailout makes that go away and probably also makes the rendering a little bit faster.

**Comment by wesbos** [comment]
I can also confirm loadStripe() works with SSR on Next.js

**Comment by dweedon-stripe** [comment]
Warning should be fixed now.

**Comment by coodoo** [comment]
@dweedon-stripe  finally get around and come back to test this new version, could confirm it's now working reliably without any warning, thanks for seeing it through, great job! 👍
