### ISSUE TITLE
Migrate from 'react-stripe-elements'

### ISSUE THREAD

**Issue by Krausso** [stripe/react-stripe-js#194]
I'm migrating from `react-stripe-elements` to `stripe/react-stripe-js` following next instructions:
https://github.com/stripe/react-stripe-js/blob/master/docs/migrating.md
However, I'm a little bit stuck with the next problem.
In code there's a few places where I'm using `ReactStripeElements` that was imported from `react-stripe-elements` before.
There's an example how it's used:
```
type Props = {
  options: []
} & ReactStripeElements.InjectedStripeProps;
```
So, as you see, it is used to get `InjectedStripeProps`.
I haven't found any helpful information in changelists, or something.
How can I get them now?

**Comment by Krausso** [comment]
P.S. This component is used within `injectStripe` as an argument.
Should I use useStripe instead?

**Comment by christopher-stripe** [comment]
Hi @Krausso, yes use `useStripe` instead to get access to the `Stripe` instance (or `<ElementsConsumer>` if you are using class components). React Stripe.js doesn't wrap components to inject additional props like react-stripe-elements does.

**Comment by Krausso** [comment]
Thanks, Chris:>
I think I'll close this issue in a few days if everything is okay

**Comment by Krausso** [comment]
![image](https://user-images.githubusercontent.com/52201020/121015090-479cff00-c7a3-11eb-9d27-96df471010e6.png)
It's 4 variations of `createToken` within `stripe` that I've seen. I wanna use the second one to pass `StripeCardNumberElement` there, although it expects `StripeIbanElement`.
What should I do?

**Comment by Krausso** [comment]
Btw, I've already seen this issue(https://github.com/stripe/react-stripe-js/issues/47), which doesn't help me
