### ISSUE TITLE
Feature Request: "LastFour" only Card Element

### ISSUE THREAD

**Issue by spencer741** [stripe/react-stripe-js#200]
I am writing a custom integration (very similar to functionality of the Stripe Customer Portal), where the user can update certain billing settings, upgrade or downgrade their subscription, etc.

I have the need for a field that displays the last four digits of the card number, along with the provider (VISA, MasterCard, etc). See below.

<img width="496" alt="Screen Shot 2021-06-26 at 5 37 45 PM" src="https://user-images.githubusercontent.com/35856129/123527444-44f84000-d6a5-11eb-942e-ea0dc21db446.png">

Is this functionality currently possible with the "CardElement" in react stripe js?

It seems that the functionality could easily be created through an extension of props or creation of a new stripe element.

Since all CardElement functionality is a superset of what this new element would be, I don't see any security risks.

If it's not currently possible, I would like to request a feature update to the API.

I think the simplest approach would be to extend the options prop [see here](https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options).

```js
import {CardElement} from '@stripe/react-stripe-js';

<CardElement
    LastFourOnly={true}
    LastFourOnlyOpts={{
        last4:4242,
        brand:"visa",
        exp_month: 8,
        exp_year: 2022,
        default:true
    }}
/>
```
The only props info you would need could easily be obtained through the customer object and the [payment_methods object](https://stripe.com/docs/api/payment_methods/object), for example.
```json
{
    ...
    "card": {
        "brand": "visa",
        "last4": "4242",
        "exp_month": 8,
        "exp_year": 2022,
        ...
    }
    ...
}
```

This field could easily be recreated, but I feel it would be an extremely useful add on to Stripe.js and thus react-stripe-js, especially given the card brand icon and such.

Let me know if this issue needs to be linked to another issue in another repo, since this isn't necessarily just a react-stripe-js addition, but perhaps an addition to the core stripe.js api.

**Comment by graceg-stripe** [comment]
Hi @spencer741,

Thank you for reaching out! This functionality you mentioned is currently not available in the "CardElement", and I'm going to file this feature request in our internal issue tracker.

I am going to go ahead and close this out for now since we try to keep the issues here specific to issues with React Stripe.js. I'll post here if we have any updates.

Thank you!

**Comment by spencer741** [comment]
@graceg-stripe 

Thank you for directing this to the correct channel. I ended up just creating my own element.

If this is thread is not linked directly to the internal issue, could you also add the following? vvv

---

The main hassle when I implemented my own was getting the card brand icons.

I understand from [stripe support](https://support.stripe.com/questions/where-to-find-logos-for-accepted-credit-card-types) that stripe doesn't provide a documented api endpoint for svg icons of supported card brands... since the svg data is small, I think that an alternative to extending stripe elements .js like I mentioned would be to provide endpoints to access svg icons...

With those icon endpoints, a "Last4" card element like I described wouldn't really be necessary, as it could very easily be created by any average dev.

Brand -> icon retrieval is the biggest part of this.

---

Thanks again for your help! I developing on the Stripe platform and appreciate all the work y'all do!
