### ISSUE TITLE
[Help] How to determine if payment sheet is showing?

### ISSUE THREAD

**Issue by PsyGik** [stripe/react-stripe-js#205]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md)!

### Summary

I'm using React and I have an  `useEffect` that tries to update the total in a `paymentRequest.update()` method

When I try to do that, stripe throws an error:

```
Uncaught IntegrationError: You cannot update Payment Request options while the payment sheet is showing.
    at n.<anonymous> (v3:1)
```

…which makes sense. Now my issue is that I don't know how to check if the payment sheet is already open or not to prevent the update from being called.

I'm looking to do something like this:

```js
if (!paymentInProgress()) {
  paymentRequest.update(...);
}
```

How do I implement `paymentInProgress`?

I am using a custom button and calling `paymentRequest.show()` when user clicks on the button. Listening to `paymentRequest.on('click',fn)`, does not work in this case.

### Other information

Tested on Google Chrome. 
```
 "@stripe/react-stripe-js": "^1.4.0",
    "@stripe/stripe-js": "^1.13.1",
```

**Comment by PsyGik** [comment]
🦗

**Comment by tylersmith-stripe** [comment]
Hi @PsyGik ,

Sorry for the delayed reply. This looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for assistance with this question.

Our API reference for [paymentRequest.update()](https://stripe.com/docs/js/payment_request/update) has some suggestions for this flow as well.
