### ISSUE TITLE
Supporting BAC's (UK direct debits)

### ISSUE THREAD

**Issue by wroughtec** [stripe/react-stripe-js#206]
### Summary

Any plans to support a BAC's (UK direct debit) type element for react?

### Other information
 
Currently use Card elements with no issues however getting more and more requests for using direct debit so am looking at adding an option to choose between payment methods of either card or direct debit but as far as I can see BAC's is not currently supported in the React lib (unless I am missing something).

**Comment by tylersmith-stripe** [comment]
We don't have a timeline to share for Bacs support in Elements, but the [new Payment Element (currently in beta)](https://stripe.com/docs/payments/payment-element) will definitely support it at _some point_ in the future!

Closing out the issue for now. For future feature-related questions, feel free to reach out to [Stripe Support](https://support.stripe.com/) for assistance.
