### ISSUE TITLE
StripeCardElementChangeEvent's complete is true with an amex card and 3 digit CVC

### ISSUE THREAD

**Issue by fzembow** [stripe/react-stripe-js#207]
### Summary

**STEPS**

1. Set up a `<CardElement>` and listen to its `onChange`
2. Enter an AMEX card (for example the test card 378282246310005)
3. Enter a 3 digit CVC

**RESULT**

- The `complete` property on the event passed to `onChange` is true

**EXPECTED**

- The `complete` property should be false, because a 3 digit CVC is not valid for Amex. Presumably, the component is aware that it's an Amex card (the icon is displayed), so it would be great if we knew in the embedding component that it's valid or not.

### Other information

Our package versions are the following

```
    "@stripe/react-stripe-js": "^1.1.2",
    "@stripe/stripe-js": "^1.11.0",
 ```

**Comment by christopher-stripe** [comment]
Hi @fzembow, American Express can accept either the CVV (3 digits) or the CID (4 digits) in the `<CardElement>` CVC field. 

Additionally, the `complete` field [does not guarantee that the user is finished entering input](https://stripe.com/docs/js/element/events/on_change?type=cardElement#element_on_change-handler-complete):

> true if the value is well-formed and potentially complete. The complete value can be used to progressively disclose the next parts of your form or to enable form submission.
> 
> It is not an indicator of whether a customer is done with their input—it only indicates that the Element contains a potentially complete, well-formed value. In many cases the customer could still add further input.
>
> The complete value should not be used to perform an action such as advancing the cursor to a subsequent field or performing a tokenization request.

**Comment by fzembow** [comment]
Got it, we were going ahead with the tokenization based on this, we'll have to change to a manual advance instead - thanks for the clarification!
