### ISSUE TITLE
Change border color when input is focused?

### ISSUE THREAD

**Issue by cmacdonnacha** [stripe/react-stripe-js#209]
Hey, just wondering if there's a way to:

* Add a border around the input
* Change the border color when the input is focused?

**Comment by graceg-stripe** [comment]
Hi @cmacdonnacha, you can add a border around the input element by creating a `<div>` around that element and style that `<div>`. For changing the border color when the input is focused, you can use `element.on('focus', handler)` and `element.on('blur', handler)` to determine the state and configure different border color. See the documentation for these methods here: https://stripe.com/docs/js/element/events/on_focus.

Please let me know if you need any other help! Thanks

**Comment by cmacdonnacha** [comment]
Thanks, it looks like there's actually an easier way:

```
.my-base-style {
  border: '1px solid #ccc';
}

.my-focus-style {
  border: '1px solid blue'
}
```

```
  const CARD_OPTIONS: StripeCardElementOptions = {
    hidePostalCode: true,
    classes: {
      base: 'my-base-style',
      focus: 'my-focus-style',
    },
  };
```

` <StyledCardElement options={CARD_OPTIONS} />`
