### ISSUE TITLE
Have an issue with google chrome.

### ISSUE THREAD

**Issue by forbrightworld** [stripe/react-stripe-js#210]
Hi, thank you for your amazing package for stripe.

I develop websites with react native web and I'd like to integrate stripe using this module.
But I have an issue with google chrome.
![Screenshot_48](https://user-images.githubusercontent.com/58917349/131013076-5c2ce226-abb1-4e1e-b5ae-f4662a8aed6b.png)
I think it seems work on Opera.
![image](https://user-images.githubusercontent.com/58917349/131016206-99b9ec27-6a75-4c66-9733-f5db854c14ec.png)

This is the code.
[Payment.txt](https://github.com/stripe/react-stripe-js/files/7061977/Payment.txt)

I have no idea what to do because it seems works on opera but not on chrome.

Please help me with this.

Thank you
Best Regards

**Comment by tylersmith-stripe** [comment]
Hi @forbrightworld, this looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help.
