### ISSUE TITLE
AmEx CVC is not checked correctly.

### ISSUE THREAD

**Issue by AgMUH** [stripe/react-stripe-js#211]
Hi!
American Express payment has 4-digit CVC code, but stripe accepts both 3 and 4 digits. 
I'm wondering if there are any ways to check CVC length?
Thanks.

Link to reproduce: https://codesandbox.io/s/react-stripe-js-card-detailed-omfb3?file=/src/App.js

**Comment by christopher-stripe** [comment]
https://github.com/stripe/react-stripe-js/issues/207
