### ISSUE TITLE
Dropdown rendering depends on the device

### ISSUE THREAD

**Issue by n-srg** [stripe/react-stripe-js#212]
Hello team. I think it is not a bug but rather a feature. But I want to clarify the behavior is intended. 

For bank selection components - which are basically dropdowns, we see they render options in a custom style with bank logos. Then we switch the device display size using the DevTools/Toggle device, we see them rendered as a standard HTML select option components (no logos, just a bank title). I think it is intended and implemented in a way to rely on how mobile browsers show the dropdown selections. 

And I want to confirm my assumption to let the QA departments know that it is not a bug. Is it true?

<img width="644" alt="Screenshot 2021-09-01 at 13 27 39" src="https://user-images.githubusercontent.com/22394106/131663630-db7a06fd-2f2d-4ceb-8d21-2548594cc61f.png">
<img width="646" alt="Screenshot 2021-09-01 at 13 28 06" src="https://user-images.githubusercontent.com/22394106/131663633-687f3095-e42d-4a7d-b121-6a0b61ffafec.png">

**Comment by christopher-stripe** [comment]
Hi @n-srg, that is indeed the case!

**Comment by n-srg** [comment]
great, thank you for a quick response @christopher-stripe 🥇
