### ISSUE TITLE
Local fonts for card details

### ISSUE THREAD

**Issue by vivekvardhanadepu** [stripe/react-stripe-js#223]
Local fonts not working. If I use https://fonts.gstatic.com/s/cantarell/v10/B50NF7ZDq37KMUvlO015jKJrPqySLQ.woff2 in url, it's working, but when I download it pass the local path, it is not working
Source: https://stripe.com/docs/js/appendix/custom_font_source_object

**Comment by christopher-stripe** [comment]
Hi @vivekvardhanadepu, this looks like an issue with your specific integration. We can't provide support for integrations here (the issues here are reserved for possible issues with React Stripe.js itself). Please reach out to [Stripe Support](https://support.stripe.com/) for help.
