### ISSUE TITLE
PaymentRequestButton IntegrationError: Invalid value for paymentRequest(): total.amount should be a positive amount in the currency's subunit. You specified: 220.00000000000003.

### ISSUE THREAD

**Issue by m-nathani** [stripe/react-stripe-js#226]
### Summary
With **PaymentRequestButton**, when using currency **without** zero decimal places like `usd` and amount `$2.20`  i am getting below error:

NOTE: One thing to notice here is that it only happens with the amount become `2.2 * 100  = 220.00000000000003`
For it i tried doing `(+amount * 100).toFixed(2)` but its same error still as show in the screenshot attached below.

_IntegrationError: Invalid value for paymentRequest(): total.amount should be a positive amount in the currency's subunit. You specified: 220.00._

Moreover, i am handling
1. the zero decimal currency,
2. and also fixing the amount to 2 decimal place for cases when we de `amount * 100`

### Other information

Below are version using for stripe:
`    "@stripe/react-stripe-js": "^1.4.1",`
`    "@stripe/stripe-js": "^1.17.1",`
    
and for PaymentRequestButton option i am using this

``` js
   options: {
      country,
      currency: currency?.toLowerCase(),
      total: {
        label: 'total',
        amount: ZERO_DECIMAL_CURRENCIES.includes(currency) ? +amount : +amount * 100
      },
      requestPayerName: true,
      requestShipping: false
    },
```
where as this is ZERO_DECIMAL_CURRENCIES array from docs
Reference for stripe zero decimal:  https://stripe.com/docs/currencies#zero-decimal

```js
export const ZERO_DECIMAL_CURRENCIES = [
  'BIF',
  'CLP',
  'DJF',
  'GNF',
  'JPY',
  'KMF',
  'KRW',
  'MGA',
  'PYG',
  'RWF',
  'UGX',
  'VND',
  'VUV',
  'XAF',
  'XOF',
  'XPF'
];

```

![Screenshot from 2021-10-02 07-43-42](https://user-images.githubusercontent.com/13331386/135696427-f22c1eef-7124-42c6-840e-38cd5bf44935.png)

**Comment by wma-alvin** [comment]
You need an integer rather than a 2-d.p. string

```
parseInt(Math.round(2.2 * 100), 10);
```

or you can use https://github.com/MikeMcl/decimal.js/ for better decimal operations

**Comment by m-nathani** [comment]
> You need an integer rather than a 2-d.p. string
> 
> ```
> parseInt(Math.round(2.2 * 100), 10);
> ```
> 
> or you can use https://github.com/MikeMcl/decimal.js/ for better decimal operations

Hi boss, 

1. its a decimal not a string
2. not really sure about rounding the values.. as while charging with the card,  cents could result in not the exact value to charge

for example: 

`Math.round(2.235 * 100) = 224`   which is resulting in extra charging the users :(

**Comment by tylersmith-stripe** [comment]
Glad you solved, this @m-nathani. 👍
