### ISSUE TITLE
isEqual flawed 

### ISSUE THREAD

**Issue by mattbdc** [stripe/react-stripe-js#230]
isEqual is flawed. returns false for when object is identical. this causes a console warning related to mutable properties

![image](https://user-images.githubusercontent.com/83773047/137620889-e74d3f9c-4803-4935-b66e-cd4ff7d923f2.png)

call site:
```
	  return Object.keys(options).reduce(function (newOptions, key) {
	    var isUpdated = !isUnknownObject(prevOptions) || !isEqual(options[key], prevOptions[key]);

	    if (immutableKeys.includes(key)) {
	      if (isUpdated) {
	        console.warn("Unsupported prop change: options.".concat(key, " is not a mutable property."));
	      }

	      return newOptions;
	    }

	    if (!isUpdated) {
	      return newOptions;
	    }

	    return _objectSpread2(_objectSpread2({}, newOptions || {}), {}, _defineProperty({}, key, options[key]));
	  }, null);
```

surely if they are referentially the same object isEqual should return true

**Comment by christopher-stripe** [comment]
Agreed, that looks suspicious. Can you share the `options` / `prevOptions` object that you are passing to a React Stripe.js component that triggers the warning to be logged?

**Comment by rado-stripe** [comment]
@mattbdc  I found one case where the check was wrong (see #235), but to certain this would fix your problem, can you tell me more about the object that prints in the `Unsupported prop change:` warning.

**Comment by mattbdc** [comment]
Hi rado, I will test this, its a standard object as far as I remember, but we're using preact with react/compat, ill test the above change today and create a repo if still failing

**Comment by rado-stripe** [comment]
odd, I feel that standard objects shouldn't have this issue - at least based on the unit tests here - https://github.com/stripe/react-stripe-js/pull/235/files#diff-12a347fab0cbbe46ec1dfb48553043e794ccf948425f6fcd023a0d330ba0407dR47-R58. If you can make that unit test fail with some object, I can take care of fixing it.
