### ISSUE TITLE
[Bug] CardElement content extends out of bounds of input element + overlays other elements

### ISSUE THREAD

**Issue by ChronSyn** [stripe/react-stripe-js#231]
### Summary

The `CardElement` input does not correctly scroll as the user types their card number, and overlays other elements

### Other information

@stripe/react-stripe-js library version: ^1.4.1

When the user is typing their card number, it does not appear to 'scroll' the text input so that the user can see the last digits of the card number they entered. Additionally, it appears to overlay other elements such as the CVC (see Firefox screenshot below).

Chrome Android Mobile (Samsung Galaxy Z-Fold 2 - front/smaller screen):
![image](https://user-images.githubusercontent.com/12896049/137757877-d7a49dd7-2aa6-4308-89b1-1ed0f68f2d75.png)

Firefox Windows, large scaling
![image](https://user-images.githubusercontent.com/12896049/137758719-b8b56911-6942-4353-b5cf-0b2b0ce9fe6a.png)

Our client requirements define that we use the all-in-one card element (i.e. includes card number, CVC and expiry elements). I have taken a look at the styling options we have available, but could not find a solution with these that resolved this issue.

**Comment by tylersmith-stripe** [comment]
Hi @ChronSyn 👋 ,

Is it possible that the card number was entered incorrectly in your testing? The auto-advance to expiry only works when the card number appears valid. (e.g. try `3333 3333 3333 3333` vs. `4242 4242 4242 4242`)

Regarding the overlapping: the expiry fields are never hidden, even when they overlap with the card number. This is the intended behavior, but I understand that this leads to some challenging UI scenarios at very small screens.

**Comment by ChronSyn** [comment]
> Hi @ChronSyn 👋 ,
> 
> Is it possible that the card number was entered incorrectly in your testing? The auto-advance to expiry only works when the card number appears valid. (e.g. try `3333 3333 3333 3333` vs. `4242 4242 4242 4242`)
> 
> Regarding the overlapping: the expiry fields are never hidden, even when they overlap with the card number. This is the intended behavior, but I understand that this leads to some challenging UI scenarios at very small screens.

Hi - thanks for getting back to me.

The issue isn't that it doesn't automatically switch to the next field (4242 test card number was used) - it's that the last numbers typed in the field aren't visible, as through the field doesn't correctly follow the cursor. The user has no idea how many numbers they've typed, or if they've made a mistake.

As can be seen in the first screenshot in the original report, only the first 6 digits and part of the 7th digit is visible. If I make a mistake on the 11th character (for example), I'm not able to see it, so I have no way of identifying if I typed the correct digits.
