### ISSUE TITLE
How to use PaymentElement without PaymentIntent/SetupIntent? Amount is unknown?

### ISSUE THREAD

**Issue by Noitidart** [stripe/react-stripe-js#240]
Similar to this here - https://github.com/stripe/react-stripe-js/issues/234 - but I don't know the amount ahead of time, the users enter a custom donation amount, so I cannot create a PaymentIntent, which requires "amount". Is there a way to use `PaymentElement` without it?

**Comment by samridh-stripe** [comment]
Hi @Noitidart, this isn't an issue with the React Stripe.js wrapper library. One possible way to handle this might be to use the [UpdatePaymentIntent](https://stripe.com/docs/api/payment_intents/update?lang=node) API.

The issues on this repository are for reporting possible bugs with the React Stripe.js wrapper library itself. For integration questions please reach out to [Stripe Support](https://support.stripe.com/contact).

**Comment by Noitidart** [comment]
Oh thanks for fast reply.

**Comment by Noitidart** [comment]
Oh gosh sorry to bother but Stripe support I have misreable time with, they run in me in circles, its been this experience for last 2 years I've been their customer.

May I ask you please? Is it possible to load up the elements in any way without connectivity? I'm doing an offline first app, so pages need to load without connectivity, and on click of "pay" i then connect, to have minimal connection.

**Comment by alexb-stripe** [comment]
Hi @Noitidart -- I'm Alex on the Elements product team. I just logged your feedback to support a workflow to not require 'amount' when creating the paymentintent to our Payment Element backlog. Would you mind shooting us an email at elements-feedback@stripe.com so we can follow up with you via email in case we 1) end up having follow-up questions or 2) have updates to give you related to the feature? Thanks!

Also, to answer your last question, we aren't able to load up the element w/o connectivity. For PCI compliance reasons, stripe.js needs to be loaded from our servers directly.

**Comment by Noitidart** [comment]
Thanks very much Alex. I was making a mobile app with hybrid web tech, is it even necessary for mobile? Very much appreciate your help!

**Comment by Noitidart** [comment]
I sent this email:

> I have SPA, a long page of announcements, events, and then donations section. It has multiple donation boxes, each one has a donation form. I want to keep my server load to a minimum and want to use Stripe Elements without having to feed it a PaymentIntent until its time to pay. I dont mind doing a two requests when "pay" is pressed, but doing requests for the forms to create 5-10 Payment/Setup intents when there is high chance none of them will be used.
