### ISSUE TITLE
[Bug] CardElement postcode requirement true/false display problems

### ISSUE THREAD

**Issue by tj-kev** [stripe/react-stripe-js#242]
### Summary

I'm having an issue with the card element and switching the postcode requirement true/false. The postcode field isn't available unless one of the other fields is edited when switching from false to true. Also doesn't slide into view when it is activated. Steps to reproduce on the provided example jsfiddle are:
* Enter PAN
* Enter date
* Enter CVV
* Enter postcode/zip (all working so far)
* Tick checkbox to remove postcode requirement (postcode/zip field disappears, all working so far)
* Tick checkbox to enable postcode requirement (postcode/zip field does not reappear and can't be accessed)
* Edit CVV number (postcode field can now be accessed, but does not slide into view. Its hidden)

Example jsfiddle: https://codesandbox.io/s/react-stripe-js-forked-85t9j?file=/src/components/demos/CardForm.js

### Other information

Tested in Chrome 96.

**Comment by tj-kev** [comment]
Any update on this?

**Comment by tylersmith-stripe** [comment]
Hi @tj-kev 👋 

I took a look at your reproduction and can confirm the behavior you're seeing. A caveat I'd add is that you can access the postal code field by focusing into the card number field, then proceeding over through date/cvv. So, in that vein, the Element is definitely still functional across updates.

I can flag this UX edge case internally, but feasible application does seem obscure. Can you describe how you're running into this flow for users, where you're updating postal code requirements _after_ they've already added their payment details?

**Comment by tj-kev** [comment]
The user may tick/untick "Use delivery address as billing address" after they have entered the payment details.

The way we have resolved for now is to clear the card element contents which seems to reset it.

**Comment by tylersmith-stripe** [comment]
Ah, I see.

Another approach for modeling this, that would not involve changing postal code collection in the Element, would be to:
1. Always hide postal code in the `card` Element
2. Pass `payment_method.billing_details.postal_code` to the `stripe.confirmCardPayment()` method, based on the value you have collected elsewhere for shipping and/or billing addresses.
    - https://stripe.com/docs/js/payment_intents/confirm_card_payment
    - https://stripe.com/docs/api/payment_methods/object#payment_method_object-billing_details-address-postal_code

**Comment by tj-kev** [comment]
Yeah, we considered that but liked the integration provided by the card element.

Clearing the card element contents seems to work for now so will stick with that for now.
