### ISSUE TITLE
How can I customize CardElement Form?

### ISSUE THREAD

**Issue by simonsantan** [stripe/react-stripe-js#244]
I search in documentation. But not getting any docs. I need to customize Card Element Form. How Can I customize it. The default `CardElement` show this like image-

![Screenshot 2021-12-07 221045](https://user-images.githubusercontent.com/93183836/145064944-b76d0aa3-7858-4f56-9ab8-d7eb9faed333.png)

Here 3 input filed show in one line-

But I need like this-

![Screenshot 2021-12-07 221304](https://user-images.githubusercontent.com/93183836/145065326-3a9c66c3-084c-4ef0-adcc-5359f0c25f66.png)

Can it be done with customizations?

**Comment by dweedon-stripe** [comment]
Hi @simonsantan , this isn't an issue with the React Stripe.js wrapper library, but this can be done by using the `CardNumberElement`, `CardExpiryElement`, and `CardCvcElement`. 

The issues on this repository are for reporting possible bugs with the React Stripe.js wrapper library itself. For integration questions please reach out to [Stripe Support](https://support.stripe.com/contact).
