### ISSUE TITLE
Stripe Elements confirms the first paymentIntent it receives

### ISSUE THREAD

**Issue by shanemcgraw** [stripe/react-stripe-js#246]
### Summary
After a `paymentIntent` `clientSecret` is created and passed to Stripe Elements via `options.clientSecret`, react-stripe.js appears to hold on to that original `paymentIntent` (and along with it, the amount associated with the intent), even if a new `paymentIntent` + `clientSecret` is created and passed to `<Elements>`.

This can lead to the following scenario:
1. A `paymentIntent` is created by a customer with a large online store checkout amount (e.g. $1000) and a `clientSecret` is passed to `<Elements>`
2. The customer reflects on the large purchase while entering their card number and decides to remove a few items in their order, reducing the amount (e.g. to $500) thus the online store's app creates a new `paymentIntent` (and `clientSecret`).
3. The customer goes back to add their card with `<Elements>` (which is passed in the new `clientSecret` and renders), the customer fills out the card details, and confirms the checkout payment.
4. The customer is charged the original amount of $1000.

### Other information
I created a [sample repo demoing the issue here](https://github.com/shanemcgraw/stripe-react-stripe-js-paymentintent-issue) taken from the Stripe docs site. If one spins it up, clicks the "change amount" button, and confirms the payment, one can inspect the console to see the amount mismatch from the `/confirm` endpoint.

**Comment by christopher-stripe** [comment]
Hi @shanemcgraw, thanks for report (and for the reproduction!)

We don't currently support updating the `clientSecret` prop, and any attempted update will be ignored. This is the warning that is logged to the console when a clientSecret update is attempted:

```
Unsupported prop change: options.clientSecret is not a mutable property. 
    at Elements (http://localhost:3000/checkout/static/js/0.chunk.js:368:30)
    at div
    at App (http://localhost:3000/checkout/static/js/main.chunk.js:105:97)
```

We do have some in-flight work to address your exact use case though (updating the amount on the PaymentIntent after creation). We can post back here once we have a solution.

In the meantime, a possible workaround is to remount the `<Elements />` provider and corresponding `<PaymentElement />` altogether when the client secret changes by updating the `key` for the `<Elements />` provider:

```diff
-<Elements options={options} stripe={stripePromise}>
+<Elements options={options} stripe={stripePromise} key={clientSecret}>
```

**Comment by shanemcgraw** [comment]
Got it- thanks so much for timely response @christopher-stripe! 

Fantastic news that adjusting PaymentIntent amounts is in-flight - yes would love to be updated once it's landed.

**Comment by jthawme** [comment]
was there any update on a method for updating the amount @christopher-stripe ?

**Comment by jackieosborn-stripe** [comment]
Hi @shanemcgraw @jthawme! We recently released a new function, `elements.fetchUpdates`, that will hopefully resolve this issue for you. If you update the amount on the PaymentIntent on the server, then call `fetchUpdates` on the client, you will see the new amount reflected in the Payment Element (for example, in the Google Pay or Apple Pay sheet, or in the Afterpay messaging).

Here are the relevant docs for this function:
* https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements#fetch-updates
* https://stripe.com/docs/js/elements_object/fetch_updates

**Comment by jthawme** [comment]
@jackieosborn-stripe this works perfectly for our use case, thank you so much!!
