### ISSUE TITLE
Unsupported payment methods included in React App(NextJS) when using Payment Elements in India.

### ISSUE THREAD

**Issue by roblonj** [stripe/react-stripe-js#247]
### Summary
This issue is specific to platforms in India and it is occurring in Production/Live code and it can be reproduced as follows:
In a React App, follow the steps given here https://stripe.com/docs/payments/payment-element/migration?html-or-react=react.
1. In the Backend(in my case node js), create payment Intents as given below
**server.js**
`const paymentIntent = await stripe.paymentIntents.create({
    amount: 5000,
    currency: 'inr',
    automatic_payment_methods: {
      enabled: true,
    },
  });`

2. In the Frontend, use a PaymentElement component as below
**App.jsx**
```
const stripePromise = loadStripe('pk_test_51K2uGqSIUeHUcEgJFnCM3XZItwkjhtkbASPleCCOy3b4pXTdS6cLOVcsUfcvIf21Y583sva0s8FxnsipB89OWpdv005tW02uFN');
const options = {
  clientSecret: '{{CLIENT_SECRET}}',
};

function App() {
  return (
    <Elements stripe={stripePromise} options={options}>
      <div className="CheckoutForm">
        <label>
          Card details
          <CardElement />
        </label>
        <PaymentElement />
        <button id="submit" onClick={handleSubmit}>Submit</button>
      </div>
    </Elements>
  );
};
```
3. Confirm the payment 
```
const handleSubmit =()=>{
      const {error} = await stripe.confirmPayment({
        elements,
        confirmParams: {
          return_url: 'https://my-site.com/order/123/complete',
        },
        // Uncomment below if you only want redirect for redirect-based payments
        // redirect: 'if_required',
      });}
```

Payment Elements is supposed to(as per the docs) 
> "Automatically adjusts input fields to collect information based on the payment method and country."

But it is showing unsupported payment methods to some customers. Stripe supports only Cards payment method in India and thus only cards should displayed as input. However, Google Pay is being shown to customers. Majority of customers attempt to pay by Google Pay as it is very popular here. Then payment will fail as shown in the screenshot with message.
[Google Pay screenshot](https://user-images.githubusercontent.com/63639117/146721547-aef7e7c9-8955-4f2c-a234-507c14d1cda5.jpeg)
> Request Failed
> The selected payment method is not usable. Please select another and try again.

There is no way of knowing how many customers are shown unsupported payment methods(GPay) as this error is not visible in Stripe Dashboard. We found out after enquiring customers whose payment intents were shown as `incomplete`. After calling about 100 + customers, it is confirmed that GPay is shown to at least 50% of customers.
This issue makes customers leave the site altogether thinking that either the site is down or it is glitchy resulting negative customer experience and business outcomes.

**Comment by christopher-stripe** [comment]
Hi @roblonj, thanks for reporting this, we are looking in to it. In a meantime, one workaround would be to disable Google Pay so that it never shows in the Payment Element: https://stripe.com/docs/js/elements_object/create_payment_element#payment_element_create-options-wallets

**Comment by roblonj** [comment]
Hi @christopher-stripe, thank you for the response. Seems like Gpay is working for some users who fall under the following criteria
i) Using Android device,
ii) Using Chrome browser, and
ii) Have installed Gpay app.

**Comment by jackieosborn-stripe** [comment]
@roblonj do you happen to have more information on the devices and browsers where it is failing? Customers should only see the Google Pay button if they are using Chrome on web or Chrome on an Android device, and have an activated [Google Pay](https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel) card or a [saved card](https://support.google.com/chrome/answer/142893?co=GENIE.Platform%3DAndroid&hl=en).

An additional thing to check - are you able to make a test payment using Google Pay in test mode on a Chrome browser (on web or android device, with a Gpay card active)?

**Comment by roblonj** [comment]
@jackieosborn-stripe It is hard to gather information when using Payment Elements as we cannot see from dashboard which payment methods are shown to users. 
Nonetheless, yes I can confirm that Google Pay option is shown to users **_using Chrome on web or Chrome on an Android device, and have an activated Google Pay card or a saved card_**. But after following up with multiple users who have left the checkout page on our website without entering any payment method, it seems there are two sets of users who are facing issues with Google Pay, 
i) Users who have used **Rupay** card to activate Google Pay aren't able to complete transactions as Rupay cards are not supported by Stripe,
ii) Some users who have activated Google Pay using UPI(Unified Payments Interface) are also shown Google Pay button but cannot complete transaction(shown a pop up that the payment method is not usable). I understand that stripe's implementation of UPI is still in beta phase and we are not part of the early access rollout yet.(We have expressed interest in the early access of UPI beta program but we need to use Connect which is not available in beta UPI implementation yet).

**Comment by jackieosborn-stripe** [comment]
@roblonj 
i) I see now. Thank you for the clarification!
ii) Thanks for flagging this to us - definitely helpful to know

For now, I would suggest disabling Google Pay as Christopher [suggested](https://github.com/stripe/react-stripe-js/issues/247#issuecomment-1008802980), since Stripe does not accept Rupay cards and UPI does not seem to be working correctly. We will look into UPI to see if there is anything we can do.

I'm going to close this issue out, but feel free to create another one if you come across a separate issue. We'll update here if we have a better path forward with regards to using a Rupay card or UPI 👍
