### ISSUE TITLE
3D secure iFrame not opening up because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

### ISSUE THREAD

**Issue by Johan-Liebert1** [stripe/react-stripe-js#249]
While integrating stripe into our website, ran into the issue of the 3D secure modal showing up for a fraction of a second then disappearing with this message in the console

```
[Report Only] Refused to frame 'https://hooks.stripe.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

I've updated the CSP directives on our website and the same is given below

```
content-security-policy: default-src *;img-src * *.stripe.com data:;style-src * 'unsafe-inline';script-src * 'self' 'unsafe-inline' 'unsafe-eval';connect-src * 'self' *.stripe.com;frame-src 'self' *.stripe.com *.stripe.network *.firebaseapp.com;frame-ancestors 'self' *.stripe.com *.stripe.network *.firebaseapp.com
```

This issue is present in http and https domains and in all browsers. 

These are the response headers sent back from hooks.stripe.com

![image](https://user-images.githubusercontent.com/39958783/148327818-ced4bc7c-6bf9-42ac-b5bc-43b6ba2f0e70.png)

The packages and their versions I'm using 

```
"@stripe/react-stripe-js": "^1.7.0",
"@stripe/stripe-js": "^1.22.0",
"stripe": "^8.195.0",
```

**Comment by chnn** [comment]
Hi @Johan-Liebert1, is this issue still occurring for you? I tried to reproduce using the CSP you have provided, but was able to complete a test mode 3DS transaction without issue.

**Comment by Johan-Liebert1** [comment]
Hello @chnn , I managed to solve it by passing a `return_url` parameter while confirming the card payment, but I'm still not able to complete a 3DS transaction in test mode while on `http`. On `https` everything works as expected , but on `http` I get this error in the console

```
[Report Only] Refused to frame 'http://localhost:3000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'https'".
```
Is there any way to solve this? My CSP is still the same and I'm passing `window.location.href` as the `return_url` parameter. This is the code snippet I have for payment confirmation. Thanks again

```typescript
                const { error: stripeError, paymentIntent } = await stripe.confirmCardPayment(clientSecret!, {
                    payment_method: {
                        card
                    },
                    return_url: window.location.href,
                    receipt_email: email
                });
```

**Comment by christopher-stripe** [comment]
Where is the `frame-ancestors` directive being set? Is that on your site, or in one of the iframes loaded by Stripe.js?

**Comment by Johan-Liebert1** [comment]
It's in one of the frames loaded by Stripe.js as on my side the frame-ancestors property is set to be a wildcard "*"

**Comment by imabhijith25** [comment]
Did anybody solve this issue?

**Comment by christopher-stripe** [comment]
Would either of you be able to provide a reproduction? Something on CodeSandbox or Glitch would be ideal. I'm unable to reproduce this myself.
