### ISSUE TITLE
Stripe infinite loop api call (Promise Error)

### ISSUE THREAD

**Issue by prakashkanagarajan57** [stripe/react-stripe-js#250]
Summary:

When i open application, Stripe Api continuously get's called and  app is getting crashed,
![stripe_issue1](https://user-images.githubusercontent.com/70878198/149689008-61fb52b1-068e-4866-95ec-c483b4519a0a.png)
![stripe_issue2](https://user-images.githubusercontent.com/70878198/149689011-9bf50746-d10e-4b9e-8708-4257b59fbcd0.png)

stripe version : latest version

**Comment by WOGBOY696** [comment]
When will I ever receive payment

**Comment by graceg-stripe** [comment]
Hi @prakashkanagarajan57, this looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help.
