### ISSUE TITLE
onBlur Not triggering for react-stripe elements

### ISSUE THREAD

**Issue by fredlemieux** [stripe/react-stripe-js#252]
### Summary
I need to hook into onBlur for react-stripe elements, and onBlur does not get triggered.  The components I have tried are:

- CardCvcElement,
- CardExpiryElement, and
- CardNumberElement

I haven't tried all props, but onChange works fine.

### Other information
Version being used:
- "@stripe/react-stripe-js": "^1.6.0",
- "@stripe/stripe-js": "^1.21.1",

SImple test:
```
<CardNumberElement
  className={classNames('col-span-3 px-8 py-4', classes.input)}
  options={{
    showIcon: true,
    style: {
      base: {
        fontFamily: "'GT Walsheim', sans-serif",
      },
    },
  }}
  onBlur={async () => {
    console.log('bluuuuured');
    await trigger('cardNumberValid');
  }}
 
/>
<CardExpiryElement
  className={classNames('px-8 py-4', classes.input)}
  onBlur={() => {
    console.log('CARD EXP BLUR');
  }}
/>
<CardCvcElement
  className={classNames('px-8 py-4', classes.input)}
  onBlur={() => {
    console.log('CARD CSV BLURRR');
  }}
/>
```

**Comment by jackieosborn-stripe** [comment]
Hi, I just tried testing this out in a [code sandbox](https://codesandbox.io/s/crimson-night-krlbd?file=/src/App.js), and it appears that `onBlur` works for me. I tried this by tabbing and clicking off of the element with a mouse. Are you able to send a link to a sandbox or glitch where the issue can be reproduced?

**Comment by fredlemieux** [comment]
Ah! I'm using it with NextJS, which sometimes removes event listeners for various reasons (I don't understand the intricacies of what's happening under the hood yet).  I've had this happen in another case where multiple rerenders in quick succession would load the component but lose the event listeners such as this.   
You are totally right it works fine.  If anyone else runs into this problem with NextJS just stop the dev environment are restart.  Sorry to post an issue needlessly, hopefully this might help someone else running into the same problem.  I'll edit the original to specify it is in Next JS and close.  Thanks for the prompt reply and the code sandbox demo 👍

**Comment by jackieosborn-stripe** [comment]
That's very strange! Thanks for posting a followup 😄
