### ISSUE TITLE
Add methods to validate bank value for Eps/p24/iDeal

### ISSUE THREAD

**Issue by n-srg** [stripe/react-stripe-js#253]
### Summary

So consider I use iDeal/p24/Eps - all these payment methods require customer to select a bank they are customers of.

for (iDeal) the simple example would be:

```typescript
import { IdealBankElement } from '@stripe/react-stripe-js';

export const IDealForm = (savedBank: string) => (<IdealBankElement options={{value: savedBank} />)
```

now I can send any kind of value as a `savedBank` property, right. And the component does not validate the bank value
is valid or not. it is okay for me to send `savedBank = 'test'` and on the UI the dropdown will render correctly without any bank selected. This also means the onChange events fires with this wrong bank-like value and I technically allow user to submit the payment form.

I want to validate the value is one of the really allowed banks. I can hardcode the list of banks accepted by Stripe [from there](https://stripe.com/docs/payments/ideal/accept-a-payment#bank-reference)

But, since Stripe own this, I rather want to ask you if we can implement something like this:

```typescript
// for iDeal

// Option 1
export const validareIdealBank = (bank: string): boolean => supportedIdealBanks.includes(bank);
// OR Option 2
export const validareIdealBank = (bank: string): string | null => supportedIdealBanks.includes(bank) ? bank : null;
// for p24
// for eps.....
```
Looks the same as I can do in my code, but it is rather up to Stripe to update this supported banks list.

Another option is to validate the value inside the `IdealBankElement` and fire the onChange event with some error information

what do you think?

**Comment by n-srg** [comment]
up ⬆️

**Comment by christopher-stripe** [comment]
Hey @n-srg, those both seem like nice improvements to me. I'm going to log this as a feature request internally, and we can post back here if we have any updates to share. In the meantime I am going to close this—we generally only keep these issues open for bugs with the React Stripe.js wrapper itself.

**Comment by n-srg** [comment]
@christopher-stripe great to hear from you, thank you!

Yes I could imagine this can be implemented in many ways. for instance it can be a generic API in the main Stripe-js library. It also can be implemented as part of the prop validation inside the React components. So decided to raise a discussion in the `react-stripe-js` considering this. 


I am happy that you found this makes sense, looking forward to follow up on it. obviously I understand it is not urgent and high priority, but rather a nice to have feature so I do not expect it to be released soon-ish.
