### ISSUE TITLE
Refused to frame 'http://localhost:3000/' because it violates the following Content Security Policy directive: "frame-src https:".

### ISSUE THREAD

**Issue by imabhijith25** [stripe/react-stripe-js#254]
Getting this error after I entered all the credit card information. Been stuck with this for a while now

**Comment by Babbili** [comment]
for Development environment,  localhsot, use stripe test keys and test credit cards only such as 4242 4242 4242 4242, 
then for Production environment, frame-src https, you can use the stripe live keys and actual credit cards

**Comment by Babbili** [comment]
> Getting this error after I entered all the credit card information. Been stuck with this for a while now

for Development environment, localhsot, use stripe test keys and test credit cards only such as 4242 4242 4242 4242,
then for Production environment, frame-src https, you can use the stripe live keys and actual credit cards

**Comment by christopher-stripe** [comment]
Hello, I'm unable to reproduce this. Are either of you able to provide a reproduction?

**Comment by mkpasala** [comment]
@Babbili I am using 4242 4242 4242 4242 and test keys only, still I m getting the same error. Do you have any suggestion to by pass this error through proxy.

**Comment by tylersmith-stripe** [comment]
Closing out this issue for now until more information can be surfaced that points to an issue with our React wrapping library, specifically.

If you continue to experience `localhost` related issues, please reach out to [[Stripe Support](https://support.stripe.com/)](https://support.stripe.com/) for help with your integration.
