### ISSUE TITLE
`PaymentElement` background color collides with `color-scheme: dark;`

### ISSUE THREAD

**Issue by baristikir** [stripe/react-stripe-js#257]
### Summary
The `PaymentElement` component should have a `background-color` of `transparent`, but whenever a custom `color-scheme` is defined with `dark`, in my case its on the root level of the DOM, then the `PaymentElement` gets a white background.

This is how it looks with the css styling property `color-scheme: dark;`

![paymentelement](https://user-images.githubusercontent.com/44122379/153023040-654778ab-b3df-48ef-959c-54c6f40e5ec2.png)

My current workaround for the `color-scheme` is by resetting it for the `PaymentElement` component manually like so
```css
.payment-element-container {
     color-scheme: normal;
}
```
```ts
<Elements stripe={stripePromise} options={{ clientSecret, appearance: { theme: "night" } }}>
	<PaymentElement id="payment-element" className="payment-element-container" />
</Elements>
```

Now the background is transparent as expected.

![Bildschirmfoto 2022-02-08 um 16 52 12](https://user-images.githubusercontent.com/44122379/153024317-520e89a1-5fa4-48a1-a071-3beeffdcb004.png)

### Other Information
- Tested on Google Chrome.

**Comment by tylersmith-stripe** [comment]
This fix has been deployed. `color-scheme: normal !important` is now applied directly to Element iframes. Thanks again for flagging this issue with us!
