### ISSUE TITLE
CORS Policy issue with PaymentElement

### ISSUE THREAD

**Issue by benjy344** [stripe/react-stripe-js#259]
I'm facing an issue using the `PaymentElement` from `@stripe/react-stripe-js`.

in my console i can see the issue :  “Access to XMLHttpRequest at ‘https://r.stripe.com/0’ from origin ‘https://js.stripe.com/’ has been blocked by CORS policy” ... this Error came from the HTML in the Iframe generated by PaymentElement . So, it looks like the iframe load a HTML and this HTML load a JS file that try to make some calls to the https://r.stripe.com/0 's API .. but the CORS between [js.stripe.com](http://js.stripe.com/) and [r.stripe.com](http://r.stripe.com/) are not configured properly.

I can see the same issue on the doc  [https://stripe.com/docs/stripe-js/appearance-api](https://stripe.com/docs/stripe-js/appearance-api) so i presume I am not an isolated case.

```json
"dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "@stripe/react-stripe-js": "^1.6.0",
    "@stripe/stripe-js": "^1.21.2"
}
```

**Comment by christopher-stripe** [comment]
Hi @benjy344, sorry for the noise here. These errors don't affect any essential functionality of Stripe.js (the requests are logs we use to monitor the health of Stripe.js).

We just rolled out a change a few minutes ago that should fix the issue. Can you check one more time and let me know if this is resolved for you?

**Comment by christopher-stripe** [comment]
Great, glad to hear it.
