### ISSUE TITLE
loadStripe promise is not working correctly

### ISSUE THREAD

**Issue by umar0107** [stripe/react-stripe-js#26]
I spend 1 day on trying to use loadStripe function but it always through promise error by using
const stripePromise = loadStripe('pk_test_6pRNASCoBOKtIshFeQd4XMUh');
Error:
`Uncaught Error: Invalid prop stripe supplied to Elements. Please pass a valid Stripe object or null. You can obtain a Stripe object by calling window.Stripe(...) with your publishable key.`

but when I use `window.Stripe("api_key") ` it works perfectly.
So, there are just 2 possibilities, loadStripe not work correctly or I'm using it wrongly.
Guys please have a look if anyone have solution of it

**Comment by dweedon-stripe** [comment]
Sorry this isn't working, and thanks for the report. Can you share some additional context? A reproduction with in something like CodeSandbox or jsfiddle would be very helpful.

**Comment by umar0107** [comment]
Hi @dweedon-stripe ,
Thanks for your response!
This function `loadStripe("api_key")` is working according official documentation. I also checked demo on CodeSandbox [https://codesandbox.io/s/react-stripe-official-q1loc?fontsize=14&hidenavigation=1&theme=dark](url) which looks fine.
But not works for me so, I have to use old function `window.Stripe("api_key")`.
If you need any additional information please ask.

**Comment by dweedon-stripe** [comment]
Yeah... I am curious about the exact shape of your integration. `loadStripe()` should work everywhere.

**Comment by umar0107** [comment]
Hmm.. `loadStripe()` is not working. So, I have done!
Firstly load script in public.html
`<script src="https://js.stripe.com/v3/"></script>`
and then add below code in component
`const stripePromise = window.Stripe("pk_test_key");
const Pay = () => {
    return (
        <Elements stripe={stripePromise}>
            <InjectedCheckoutForm />
        </Elements>
    );
};
export default Pay;`

instead of 

`import { loadStripe } from "@stripe/stripe-js";

const stripePromise = loadStripe("pk_test_key");
const Pay = () => {
    return (
        <Elements stripe={stripePromise}>
            <InjectedCheckoutForm />
        </Elements>
    );
};
export default Pay;`

**Comment by dweedon-stripe** [comment]
@umar0107 are you using the latest version of React Stripe.js? We did not add support for passing a Promise until [v1.0.0-beta.2](https://github.com/stripe/react-stripe-js/releases/tag/v1.0.0-beta.2).

**Comment by umar0107** [comment]
Yes, I'm using 
@stripe/react-stripe-js: ^7.0.0-beta.1
@stripe/stripe-js: ^1.0.0-beta.4

**Comment by dweedon-stripe** [comment]
That makes sense then. We did a version reset. I will mark the older versions (anything v7) as deprecated.

Please remove and re-install `@stripe/react-stripe-js` and that should fix it. Sorry for the version churn.

**Comment by umar0107** [comment]
Ah! you are right this was version issue. Thank for helping out till issue solved.
You guys are doing great job but i'm curious about version issues because you mark the older back and suddenly we move back from `7.0.0-beta.1` to `1.0.0-beta.3`.

**Comment by dweedon-stripe** [comment]
Yeah, sorry for the churn on this. The legacy `react-stripe-elements` package was on v6. We had originally planned to have some continuity and to start React Stripe.js off at v7. We later decided to restart from `1.0.0` to create a cleaner changelog while we are still in beta. This versioning issue should only affect very early adopters.
