### ISSUE TITLE
Finalize payments on the server using PaymentElement

### ISSUE THREAD

**Issue by diegodiazbarroso** [stripe/react-stripe-js#260]
Is it possible to finalize payments on the server using `PaymentElement`?
I have researched in the Stripe doc and it seems `PaymentElement` requires to create a `setupIntent` or `paymentIntent` before to render the component so then we can confirm the payment in the front-end, sending the `elements` object (I guest it sends the card data). 
I would like to implement PaymentElement (for UI purposes) but I need to finalize the payment in my server side. To do it, it seems I need to create first a `paymentMethod` and it only accepts `CardElement` or `CardNumber` to include the card data in the request. Then I need the `paymentMethodId` to create the `paymentIntent` in my server.
Is that correct or is there any chance to confirm a payment in the server side using `PaymentElement`? Some way to send a paymentMethodId or the card data in the confirmation.
Many thanks!

**Comment by jackieosborn-stripe** [comment]
@diegodiazbarroso Unfortunately, this is not currently possible with the `PaymentElement` (see our Payment Element and Card Element [comparison doc](https://stripe.com/docs/payments/payment-card-element-comparison)).  However, we are actively working on bringing this functionality to the Payment Element!

**Comment by jackieosborn-stripe** [comment]
@diegodiazbarroso Unfortunately, this is not currently possible with the PaymentElement (see our Payment Element and Card Element [comparison doc](https://stripe.com/docs/payments/payment-card-element-comparison)). We are still looking into how to support flows that require server-side confirmation with the Payment Element. Would you mind sharing a bit around your use case for this?

**Comment by diegodiazbarroso** [comment]
It is ok, many thanks for the answer.
CardElement or CardNumberElement work ok for our case, but I need a UI similar than PaymentElement.
CardElement has CVC, expirations and ZIP in the same text field. We need an aspect like PaymentElement.
Then CardNumberElement does not have the card icons inside (according I could research it is not possible to add it).
Our scenario, when a user click the button to place an order we are creating a payment method, then we create a payment intent with manual capture (like a pre authorization). Then we obtain the confirmation or handle the extra required action until have the confirmation.
So now we can create now the order in our side. If it fails we cancel the payment intent. If it works we capture the funds.
We would need to do it in this way, the functionality is great (congratulations and thanks for it) but we would need the same aspect PaymentElement has.
Thanks!

**Comment by jackieosborn-stripe** [comment]
@diegodiazbarroso Thanks for sharing a bit about your use case! In terms of showing the card icons - would the `showIcon` [option](https://stripe.com/docs/js/elements_object/create_element?type=cardNumber#elements_create-options-showIcon) on the `CardNumberElement` work for you?
