### ISSUE TITLE
User agent parsing and upcoming Chrome & Firefox versions 100

### ISSUE THREAD

**Issue by smschick** [stripe/react-stripe-js#261]
### Summary
Chrome and Firefox will both be releasing a 3 digit version of 100 shortly and I wanted to bring up the issue of UA parsing within `react-stripe-js`and the dependency `stripe-js`.  Is there any UA parsing being done and if so has there been any testing or investigation if this could potentially cause issues?  I have also reached out to Stripe customer support directly.

### Other information
Mozilla article on the subject matter from Feb 15th:
https://hacks.mozilla.org/2022/02/version-100-in-chrome-and-firefox/

**Comment by jackieosborn-stripe** [comment]
Hi @smschick, thanks for raising this to us! We will investigate this :)
