### ISSUE TITLE
Error in console when open stripe session 

### ISSUE THREAD

**Issue by EarlOld** [stripe/react-stripe-js#262]
### Summary

macOS 12.0.1, Firefox 97.0.1

<img width="753" alt="image" src="https://user-images.githubusercontent.com/24506752/156720508-6baceaa8-078e-4f39-8a85-cad743614c26.png">

Error 1: 
Content Security Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). Source: t. customer-portal.vendors~customer_portal.22e4748fe2fbbbe0ff6b.min.js:1:279477

Error 2: 

Content Security Policy: Параметры страницы заблокировали загрузку ресурса https://www.google.com.ua/ads/ga-audiences?t=sr&aip=1&_r=4&slf_rd=1&v=1&_v=j96&tid=UA-12675062-1&cid=1474683402.1646335893&jid=914123645&_u=QCCAgEABAAAAAE~&z=1698087650 («img-src»). analytics.js:31:82

**Comment by bmathews-stripe** [comment]
Hi @EarlOld! It looks like you're seeing this error while on a Stripe billing or invoice page, is that correct? 

I've given a heads up to the team that owns that page, but please reach out to [Stripe Support](https://support.stripe.com/contact) if you're still seeing this problem. The issues on this repository are for reporting possible bugs with the React Stripe.js wrapper library itself.

**Comment by EarlOld** [comment]
@bmathews-stripe Thanks
