### ISSUE TITLE
CSS Variables on ::placeholder

### ISSUE THREAD

**Issue by everdrone** [stripe/react-stripe-js#265]
### Summary

Cannot pass css color variables to the ::placeholder pseudo element.

There is no way that i know of for dynamically changing the `style` object in the `options` prop so that it re-renders the components when the style changes. So an alternative could be using css variables but for some reason the `::placeholder` pseudo element doesn't work.

**Comment by tylersmith-stripe** [comment]
Hi @everdrone,

This looks like an integration question, and we aren't able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help. As a starting point, see our [API Ref for the Style Object](https://stripe.com/docs/js/appendix/style).

I'm going to close this issue, as this is not an issue with the React Stripe.js wrapper itself.
