### ISSUE TITLE
PaymentElement has padding issues when using US bank account 

### ISSUE THREAD

**Issue by sprakash93** [stripe/react-stripe-js#275]
### Summary

The PaymentElement has padding issues when using `US Bank account` and terms is set to `never`.

When `terms`  is set to `never`:

`<PaymentElement  options={{ terms: { usBankAccount: 'never' } }} />`

<img width="432" alt="image" src="https://user-images.githubusercontent.com/43352105/161474480-88fba19c-220d-4b92-86fd-6b9ae3a1c6cd.png">

When `terms`  is set to `auto`:

`<PaymentElement  options={{ terms: { usBankAccount: 'auto' } }} />`

<img width="427" alt="image" src="https://user-images.githubusercontent.com/43352105/161474673-b0c68fc6-b65f-453b-aab2-e4b4c007476e.png">

### Other information

Chrome:  99.0.4844.74
React 17.0.2

**Comment by graceg-stripe** [comment]
Hi @sprakash93, thank you for reporting this issue! We're working on a fix and will post status updates here as well.

**Comment by graceg-stripe** [comment]
Hi @sprakash93, the padding issue with US bank account should now be fixed! Closing this issue for now, and please let us know if you have any other questions.
