### ISSUE TITLE
Example for using Appearance with React Stripe JS?

### ISSUE THREAD

**Issue by grafficmedia** [stripe/react-stripe-js#281]
### Summary
Hello! I've been having a tough time getting the appearance prop of the options to be accepted by `Elements` and have the style propagate to other react elements. Is there an example of how to do this using the React library?

**Comment by jackieosborn-stripe** [comment]
Hi @grafficmedia! You can see how we pass `appearance` to `Elements` in our [accept a payment doc](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements&html-or-react=react#web-collect-payment-details). In general, if you have integration questions, please reach out to [Stripe Support](https://support.stripe.com/contact) or chat with us on the [Stripe Discord Server](https://discord.com/invite/stripe).

**Comment by grafficmedia** [comment]
Hi @jackieosborn-stripe , this isn't working for me. Is the client secret necessary in order to get the appearance to work?

**Comment by jackieosborn-stripe** [comment]
@grafficmedia For Stripe integration and Stripe.js questions, the Stripe Support team is much better equipped to provide a complete and timely answer to your question.

**Comment by grafficmedia** [comment]
Yes, looks like that is required. Just a bit of documentation feedback: It wasn't clear to me that the appearance API was only useful for the new PaymentElement. I was attempting to use it for your other elements, which it didn't work for.

**Comment by tylersmith-stripe** [comment]
@grafficmedia https://stripe.com/docs/stripe-js/appearance-api

![image](https://user-images.githubusercontent.com/72463083/163036573-6f94e2ce-6a44-4b5d-8f06-c3c1a558540a.png)

Hope that helps!

**Comment by RubenZx** [comment]
Hi! I'm trying to style the `CardElement` but the style object in the `options` prop doesn't produce any results. Example below: 

```jsx
<CardElement
  options={{ style: { base: { color: '#ffffff' } } }}
/>
```

Any help on this? I thought I was using the `options` prop with style properly 🤔
