### ISSUE TITLE
[BUG]: Elements component doesn't have children in typescript props definition

### ISSUE THREAD

**Issue by lucien-perouze-cezembre** [stripe/react-stripe-js#285]
### What happened?

When I try to wrap my App with the Elements provider component. Typescript throw the error :

TS2322: Type '{ children: Element; stripe: Promise<Stripe | null>; }' is not assignable to type 'IntrinsicAttributes & ElementsProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & ElementsProps'.

It seems that the Elements component doesn't specify accepting children on Typescript.

Here are my packages versions :
@stripe/stripe-js : 1.27.0
@stripe/react-stripe-js : 1.7.1
react : 17.0.2
typescript : 4.6.3

Here is my tsconfig.json :
``` json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react-jsx",
    "declaration": true,
    "allowJs": true,
    "removeComments": false,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "outDir": "./dist",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "include": [
    "./src"
  ]
}
```

### Environment

Chrome 100.0.4896.75

**Comment by cyberwombat** [comment]
@lucien-perouze-cezembre  Appears to be React@18 incompatibility. See https://github.com/stripe/react-stripe-js/pull/283

**Comment by lucien-perouze-cezembre** [comment]
> @lucien-perouze-cezembre Appears to be React@18 incompatibility. See #283

That's right, I was using version 18 of @types/react. Downgrading it to 17.0.2 solved the problem. This is still an issue for whoever wants to use the latest version of react but not a bug per say so I'm closing this issue.
