### ISSUE TITLE
[BUG]:  Can't Type OTP When payment with 3DS secure, in modal

### ISSUE THREAD

**Issue by mmestiyak** [stripe/react-stripe-js#288]
### What happened?

Can't Type in OTP Payment in 3DS Secure, in the payment modal

**Comment by jackieosborn-stripe** [comment]
Hi @mmestiyak, this looks like it’s an issue with the underlying Stripe.js script. React Stripe.js is a wrapper around that, so we don’t track those issues here. Please reach out to [Stripe Support](https://support.stripe.com/) so that we can track and prioritize this issue internally.

**Comment by ibharat** [comment]
still this issue repro. Waiting for more than 10 days with Stripe support.

**Comment by ReMuSoMeGA93** [comment]
still an issue. MAJOR ISSUE
