### ISSUE TITLE
[Support]:  PaymentElement feature and PaymentIntent

### ISSUE THREAD

**Issue by businsolution** [stripe/react-stripe-js#289]
### What happened?

I am using PaymentElement component using React 17.
When I recharge a customer, I dont want ask card detail to customer.
i.e. I want to display all card list that customer used before, then they can select one method. if customer is new on our app, he/she have to input card detail.
Even If I dont use PaymentElement on client-side,  how can I complete PaymentIntent as paid status. I know Invoice Api has pay endpoint using DefaultPaymentMethod.

 `$paymentIntent =PaymentIntent::create([ 
   "customer" => $user->stripeId(),
  'amount' => $totalPrice * 100,
  'currency' => 'usd',
  'confirm' => true,
  'description' => 'Down Payment',
  'metadata' => [
      'appointmentId' => $newAppointment->id,
      'u_id' => $user->id
  ],
  'payment_method' => 'pm_XXXXXXXXXXXXXX',
  'transfer_data' => [
      'amount' => ceil(($totalPrice - ($totalPrice * 0.029 + 0.3)) * 100),
      'destination' => 'acct_XXXXXXX'
  ],
  "receipt_email" => 'email'
]);`

Thank you

**Comment by jackieosborn-stripe** [comment]
Hi, this looks like more of an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help.
