### ISSUE TITLE
"Add Payment" with PaymentRequestButton

### ISSUE THREAD

**Issue by danseaman6** [stripe/react-stripe-js#29]
From what I can see from current implementation, you can have the PaymentRequestButton's canMakePayment method return non-null if you're on a supported browser with a payment method already loaded. Is it possible to support _adding_ a payment method if you're on a supported browser but don't have one integrated yet? On our site, it feels like we're missing a subset of people who would happily do a faster checkout with GooglePay but we don't even have a button to display to them if they haven't loaded a card before. I know there are ways to do this when inegrateing with GooglePay and ApplePay directly, is this something Stripe's wrapper can also support?

**Comment by dweedon-stripe** [comment]
Hi @danseaman6,

On-boarding a wallet is generally _more_ friction than just checking out with Elements, so we don't get a lot of asks for this. That said, I don't see why we couldn't support something like this as an opt-in API. I will add this to our feature requests for Stripe.js.

I am going to close this issue though. We can't really add support for this at the React Stripe.js level.
