### ISSUE TITLE
[Stripe Files]: load failure can't catch error

### ISSUE THREAD

**Issue by wendylw** [stripe/react-stripe-js#290]
### What happened?

![image](https://user-images.githubusercontent.com/4416839/166866032-f67d8ecd-3a75-469b-a5c0-1a0185b7a385.png)
How catch this error?

Visitors visit the CVV page, the network is suddenly broken. Some files load failure, loadStripe function how can catch this error?

![image](https://user-images.githubusercontent.com/4416839/166866331-f14230dc-36da-488c-820a-3d9ba066583c.png)
currently can not enter catch

**Comment by jackieosborn-stripe** [comment]
Hi @wendylw! This looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) or chat with us in the [Stripe Discord](https://discord.com/invite/stripe) for help.
