### ISSUE TITLE
[BUG]: Elements component can create multiple instances of stripeJs.StripeElements

### ISSUE THREAD

**Issue by randypuro** [stripe/react-stripe-js#296]
### What happened?

[Recent changes](https://github.com/stripe/react-stripe-js/commit/85cccb7ab9aabd023e7b3a6493aabab4f06268ee) to this library have changed [when and how often the `useEffect` which creates the `StripeJs.StripeElements` instance runs](https://github.com/stripe/react-stripe-js/blob/master/src/components/Elements.tsx#L152).

Because of the addition of `options` to the dependency list, it reruns on every render for those who have configured the Elements component with a non-memoized set of options. This a a reasonable assumption since:
1. [The examples in the docs](https://stripe.com/docs/stripe-js/react) do it this way
2. The docs state "Once the stripe prop has been set, these options can’t be changed." implying they are basically read once.

If we pass a promise to the Elements `stripe` attribute, and there are multiple renders prior to that promise resolving, the effect will run multiple times and attached multiple resolvers to the promise and therefore create multiple elements instances.

In the typical flow, the first resolution will create any child PaymentElements attached to the first elements instance.
Subsequent `useElements` in child instances will get the newer elements instances after that.

When trying to checkout (`confirmPayment` with `useElements`), the checkout fails and we then get the error "Invalid value for stripe.confirmPayment(): elements should have a mounted Payment Element."

For others facing this issue, one of many ways to work around it is to wrap the options argument in a `useMemo`, or to pass a Stripe instance to Elements component rather than a Stripe promise.

**Comment by bmathews-stripe** [comment]
Thanks for the report and the helpful investigation @randypuro! We'll get this fixed.

**Comment by pascuflow** [comment]
Dropping back to "@stripe/react-stripe-js": "^1.7.1" until this is fixed.

**Comment by bmathews-stripe** [comment]
@randypuro I'm having trouble reproducing this! Any more insight into how you're running into this issue? Here's what I tried: https://codesandbox.io/s/react-stripe-js-forked-vvddpn?file=/src/index.js based on the scenario you described.

When the `options` prop changes, the effect's [cleanup](https://github.com/stripe/react-stripe-js/blob/master/src/components/Elements.tsx#L149-L151) is ran which sets a local variable `isMounted` (misleading name) to false. When the stripe promise resolves, `isMounted` is used to determine if the context should be updated. 

In your scenario, that means:

1) Elements instance initially rendered with promise provided as `stripe` prop.
2) The effect is ran (effect instance 1), `isMounted` initializes to true, and the promise is awaited
3) The parent is re-rendered, options change and the effect's cleanup function is invoked which sets isMounted to false.
4) The effect is ran again (effect instance 2), `isMounted` is true, and the promise is awaited
5) Effect instance 1's promise resolves, but `isMounted` is false, so it bails
5) Effect instance 2's promise resolves, isMounted is true, so it sets the stripe/elements instance on context.

**Comment by mnpenner** [comment]
FWIW I hit this a couple days ago too. Details here: https://stackoverflow.com/q/72334261/65387

**Comment by randypuro** [comment]
HI @bmathews-stripe . Yes, hard for me to effectively repro using your codesandbox as well. Definitely seems like a race condition. FWIW, our integration specs were consistently flaky at a 50% rate until we memoized our options to Elements. I wonder if the amount of work done in the real world app is sufficiently large to cause react to breakup operations more, or if there's something else subtle with React 18's concurrent renderer.

Thanks for your explanation of the logic - it makes sense, but my guess is that there are windows where both promise callbacks can run (or rather, the first can run while the second is being created at which point the second will run as well on immediate promise resolution). For instance, it's my understand the useEffect callbacks don't necessarily run synchronously with the render - there can be a timeout between where the old callback can still fire before the new callback is created.

The other issue is that the gate to prevent re-creation of the context runs in one frame, whereas the actual creation runs in another. One quick solution could be to use the functional argument version of setContext to accurately check the prior value at the time of the promise callback.

Anyway, my apologies I can't put something together that's more definitive, but I do think it's worth thinking about how the functionality could be broken up to a single series of gates that are more guaranteed to run linearly (eg. multiple effects to chain the operations with specific dependencies for each step).

I hope that helps.

**Comment by bmathews-stripe** [comment]
Thanks @randypuro! Super helpful to know that it was intermittent in your test environment. 

Two last questions:

1) Which version of react were you using?
2) Were you using StrictMode?

**Comment by randypuro** [comment]
React 18.1, not using StrictMode.

**Comment by bmathews-stripe** [comment]
@randypuro and @mnpenner: We've released a (likely) fix in v1.8.1. Thanks!

**Comment by randypuro** [comment]
@bmathews-stripe , thank you! Given our consistently flaky integration specs, I was able to confirm the fix has addressed the issue.

Small thought to do with as you please. Should you run into issues again in the future, or want to simplify (eliminate the local closure gate), I think it might make sense to split this effect in 2. One to set a new state variable with the resolved stripe instance from the passed in stripe option (or `parsed` in this case), and the second to create the context based on the resolved stripe and varying options. This would simplify the dependencies so that the first only depends on a single unchanging arg (so only one event listener added to the promise), and the second gates running exclusively through the state (whether stripe exists and context not yet created).

Anyway, regardless, thank you for the fix!

**Comment by bmathews-stripe** [comment]
@randypuro Nice, thanks for testing that out and confirming. 

That's a good idea. Thanks for the suggestion!

**Comment by martin3walker** [comment]
Hello,

I'm running into this same error: `IntegrationError: Invalid value for stripe.confirmPayment(): elements should have a mounted Payment Element or Pay Button Element.` I'm using version 1.16.0 of `@stripe/react-stripe-js`.

Following the workaround advice above, I'm passing in a resolved instance of the stripe.js SDK, initialized with the `loadStripe` method from `@stripe/stripe.js` into the `stripe` prop of the `Elements` provider. I'm also memoizing the options object where I pass in the client secret.

```
const PaymentDetails = ({
  formState,
  setIsLoading,
  setCurrentFormStep,
  stripe,
}: FormStepProps) => {
  const options = useMemo(() => {
    const { clientSecret } = formState;
    return {
      clientSecret,
    };
  }, [formState]);

  return (
      <Elements stripe={stripe} options={options}>
          <StripePaymentForm />
      </Elements>
 )
```

In the  `<StripePaymentForm />` component I'm calling the following click handler to submit the data from a `<PaymentElement />` from stripe:

```
const clickHandler = async (event: any) => {
    event.preventDefault();
    setIsLoading(true);

    if (!stripe || !elements) {
      return;
    }

    try {
      await stripe.confirmPayment({
        elements,
        confirmParams: {
          return_url: window.location.href,
        },
        redirect: 'if_required',
      });

    } catch (error) {
      console.log(error);
    }
  };
```

The error is being thrown at `stripe.confirmPayment`. The `<PaymentElement />` is rendered, so I'm confused as to why it says it isn't mounted.

Do we think this is the same bug? Perhaps it is a mistake on my end as I'm relatively new to Stripe 🤷

**Comment by martin3walker** [comment]
I've added the following to my click handler just to make sure the <PaymentElement /> really is mounted.

```
const paymentElement = elements?.getElement('payment');
paymentElement?.mount('#payment');
```

Those two lines throw the following error: `IntegrationError: This Element is already mounted. Use `unmount()` to unmount the Element before re-mounting.`

**Comment by martin3walker** [comment]
@martinalong-stripe @tylersmith-stripe Do you think this is worth reopening?

**Comment by martin3walker** [comment]
My problem ended up being unrelated to this. I set a loading state in the click handler that was replacing the `PaymentElement` with a loading component. This was messing with Stripe's flow. Just FYI in case anyone else runs into a similar issue.

**Comment by oscyp** [comment]
We had a same issue as @martin3walker.

Code snippet which was breaking elements component: 

```
if (isLoading) {          <---------------- removing this if statement solves the problem
 return <Spinner />
 }
 
 return (
 ...
 <PaymentElement />
 ...
 )
```

**Comment by mario-garcia** [comment]
Heads up, I am absolutely still seeing this exact issue. I'm on `"@stripe/react-stripe-js": "^1.16.5",`.  Am I really going to have to downgrade to `1.7.1` just to get around this bug?

**Comment by bmathews-stripe** [comment]
@mario-garcia:

> And I don't really understand the "get rid of the loader/spinner" suggestion

The PaymentElement has to be mounted and on the page when calling stripe.confirmPayment. The folks above were replacing the PaymentElement with a load spinner in their pay/click handler, which was causing the `IntegrationError: Invalid value for stripe.confirmPayment(): elements should have a mounted Payment Element or Pay Button Element.` error.

Let me know if that clarification helps.

**Comment by mario-garcia** [comment]
> @mario-garcia:
> 
> > And I don't really understand the "get rid of the loader/spinner" suggestion
> 
> The PaymentElement has to be mounted and on the page when calling stripe.confirmPayment. The folks above were replacing the PaymentElement with a load spinner in their pay/click handler, which was causing the `IntegrationError: Invalid value for stripe.confirmPayment(): elements should have a mounted Payment Element or Pay Button Element.` error.
> 
> Let me know if that clarification helps.

aaaaahhh.  thanks @bmathews-stripe.  that clarifies it and indeed was my issue.  thanks again.

**Comment by Sliffcak** [comment]
interesting that fixed the error on my end. If you want the loader, just ensure to put it inside where you are returning the payment form or card element

```
 return (
<>
  {loading && <Spinner />}
 <PaymentElement />
 </>
 )
```

that fixed me issue. Thanks!

**Comment by k1sul1** [comment]
I had the same issue.

Turns out I had accidentally used `<Elements></Elements>` twice while adapting the official example to my needs.

Did not have to useMemo or the like.

**Comment by lexy8168** [comment]
still stuck here any help will appreciate [https://stackoverflow.com/questions/72334261](https://stackoverflow.com/questions/72334261)

**Comment by anshumangogate** [comment]
Hi, I'm also facing the same issue. I'm using stripe version 2.3.1
The moment I click on submit, my Payment Element gets unmounted & remounted on the screen and I get this error.
I have tried all possible solutions, nothing works.
