### ISSUE TITLE
[Not really a bug]: Checkout form takes long to load leading to poor UX

### ISSUE THREAD

**Issue by zehawki** [stripe/react-stripe-js#304]
### What happened?

The standard flow is as follows:
1. Create PaymentIntent on server
2. Get back client secret
3. Use client secret to collect payment details, (as given here https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements&html-or-react=react#web-collect-payment-details)

All this working fine and tested, so no issue here. However:

There is a UX fail in Step 3 where the checkout form takes a significant amount of time to load and show up.

1. Is this expected? If so, what can be done to reduce this delay, or make it a better experience?
2. If this is not expected, what might I be doing wrong?

https://user-images.githubusercontent.com/8095144/176896251-48e2f6a8-3e67-4520-8967-ba7b5c75ed90.mp4

### Environment

Any browser

### Reproduction

https://live.maincross.org/topics/560/event/7304/canada-day-at-fort-calgary

**Comment by thommor** [comment]
I'm in the process of migrating to PaymentElement and am getting the same thing.

**Comment by tylersmith-stripe** [comment]
@zehawki Two suggestions:

1. Give `loader: 'auto'` a try in your Element options ([API Reference](https://stripe.com/docs/js/elements_object/create#stripe_elements-options-loader)). This will render a skeleton loading UI, automatically styled to match your `appearance` settings, while the Payment Element instantiates.
2. Can you create the `PaymentIntent` any earlier in the flow, so that you already have the `clientSecret` when "Register for event" is pressed?

**Comment by zehawki** [comment]
@tylersmith-stripe thank you. I will try # 1 and revert. As you may see in the recording I shared, there are 2 stages. In Stage 1, I show a spinner when the `clientSecret` is being retrieved. This is not so much of an issue since the spinner is being shown, so the user knows something is going on. I'm more worried about the 2nd stage when the `clientSecret` is sent to Stripe and there is a wait for the iframe to load up with nothing showing. Creating `PaymentIntent` earlier in the flow will not change the stage 2 behavior. The loader: 'auto' will certainly help.

**Comment by zehawki** [comment]
So there is still a perceptible delay between the interaction and the skeleton loader showing up, as you may see in this latest recording. Note that I've throttled the internet speed a bit to emulate real world mobile connections.

https://user-images.githubusercontent.com/8095144/177526064-545d07a1-9d81-413a-8630-c1d699947360.mp4

Is there a prop I can use which will allow me to show an instantaneous local loader, and then replace that with the PayoutElement once its loaded?

PS: it would be good if the docs for **Payment Element** options (https://stripe.com/docs/js/elements_object/create_payment_element#payment_element_create-options) are updated with the `loader` option. I would not have known this is supported if you had not directed me to the section on **Elements**.

**Comment by tylersmith-stripe** [comment]
> Is there a prop I can use which will allow me to show an instantaneous local loader, and then replace that with the PayoutElement once its loaded?

Unfortunately, not quite. The loading is generally pretty fast, but there is a small amount of async delay where we measure the `appearance` styles before creating the loader UI. This delay is what you're seeing here.

We are considering introducing a new event soon, something like a `loaderready` event, which would allow you to listen for when the loader UI is mounted to the DOM. This would allow you in your setup to wait until that event fires to switch from the loading dots to the modal view, so the loader UI is available instantly.

Does that type of event sound useful to you?

**Comment by zehawki** [comment]
Yes, an event would be quite perfect, thank you.

**Comment by AndrewRayCode** [comment]
Or take a loading component as a prop. I'm getting this too, `loader: 'auto'` is almost worse because it makes the component go from 0 to too tall to then shrinking down, lots of jumping

**Comment by graceg-stripe** [comment]
@zehawki We have created a new event `loaderstart` that will be triggered when the loader UI is mounted to the DOM and ready to be displayed. You can find more documentation [here](https://stripe.com/docs/js/element/events/on_loaderstart), and we've also added a new prop [`onLoaderStart`](https://github.com/stripe/react-stripe-js/blob/c6abf678/src/types/index.ts#L300-L303) to our react wrapper. 

Hopefully this new event can help to mitigate some of the UX issues you are running into! We'll close this ticket for now, and please let us know if you need any other help.

**Comment by zehawki** [comment]
@graceg-stripe Thank you. I've used the new prop successfully.
