### ISSUE TITLE
[BUG]: the stripe checkout session isn't appearing 

### ISSUE THREAD

**Issue by abdoufaci** [stripe/react-stripe-js#305]
### What happened?

this is what appears when i redirect to the stripe checkout session
![photo_2022-07-04_12-30-22](https://user-images.githubusercontent.com/64759461/177146091-0542f622-6c14-4802-bf30-b80f00e7f05b.jpg)
i don't know if the problem is in my code or not

### Environment

Chrom

**Comment by tylersmith-stripe** [comment]
Hi, this looks like an integration question related to Checkout, and we aren’t able to answer those here on GitHub. Please reach out to [[Stripe Support](https://support.stripe.com/)](https://support.stripe.com/) for help.
