### ISSUE TITLE
[BUG]: Wechat payment QR code disappears after 3 seconds

### ISSUE THREAD

**Issue by georgepickfu** [stripe/react-stripe-js#310]
### What happened?

Hi there,

Not sure if this is a bug - whenever I try to do a payment in test mode, using wechat payment, the QR code frame shows up for 3 seconds and then disappears, making it impossible to scan it and approve/decline the payment. I tried using the prod keys, and the same thing happens. I've been using stripe elements with automatic payment methods. 

Thanks in advance

### Environment

Any browser

**Comment by bmathews-stripe** [comment]
Hi @georgepickfu! It looks like this wechat pay flow currently requires a newer API version than you might be running. Can you set your Stripe API version to `2020-08-27`? 

See: https://stripe.com/docs/api/versioning, or https://stripe.com/docs/js/initializing#init_stripe_js-options

**Comment by georgepickfu** [comment]
@bmathews-stripe  indeed, that was the issue! i have overidden the stripe version and it works now. Many thanks, marking it as closed
