### ISSUE TITLE
[BUG]: elements.getElement(CardElement) return null

### ISSUE THREAD

**Issue by OooCleMooO** [stripe/react-stripe-js#314]
### What happened?

Hi,

Since few days, the function getElement return null all the time, but before all worked well.

Stripe is well loaded with the Elements wrapper, and the elements object (via useElements hook) is not null, but when I call elements.getElement(CardElement), it return now a null object.

I tried to update the library to the latest version, but not work.

Anyone has the same problem ?

### Environment

macOS 12.3.1

**Comment by bmathews-stripe** [comment]
Hi @OooCleMooO,

I haven't had luck reproducing the issue: https://codesandbox.io/s/clever-lovelace-x9v71m?file=/src/CheckoutForm.js

Are you able to put together a codesandbox that reproduces the issue?

Thanks!

**Comment by OooCleMooO** [comment]
Hello @bmathews-stripe,

Thanks a lot for your reply and your example. I finally found the problem, my card element is in a MaterialUI Dialog component, and on my submit function, I added a Redux dispatch for the loading state. Seems there is a compatibility problem with that in a MUI Dialog, so I just changed the loading state using a local loading variable with useState, and it works again !

So it's not at all an issue with the react-stripe-js library 🙂

Thanks again !
