### ISSUE TITLE
[BUG]: No tutorials work - who's actually running Stripe?!?

### ISSUE THREAD

**Issue by chrisbward** [stripe/react-stripe-js#317]
### What happened?

Hi,

On the official website there are examples of how to use [react-stripe-js](https://github.com/stripe/react-stripe-js).

confirmPayment no longer exists on useStripe, and all your official tutorials are now broken

They say Stripe is a developer-first product. 

Nah.

**Comment by chrisbward** [comment]
User error - was an older copy of the library hanging around I think, and then some frustrations with yarn

**Comment by tylersmith-stripe** [comment]
No problem! Was this perhaps caused by the older, deprecated https://github.com/stripe-archive/react-stripe-elements package?

Sorry for the confusion, and glad you got it sorted out. 👍
