### ISSUE TITLE
[BUG]: paymentRequest.abort() doesn't do anything

### ISSUE THREAD

**Issue by orionharrys** [stripe/react-stripe-js#325]
### What happened?

I'm working on implementing `PaymentRequestButtonElement` with `stripe.paymentRequest()`. I'm collecting shipping with `requestShipping: true` and have handlers for the `shippingaddresschange` and `shippingoptionchange` events, and I would like to be able to close the payment interface in the event of a serious error. According to the docs/types, there is an `abort()` method that has the same functionality as the `PaymentRequest` standard, but when I use it nothing happens.

My implementation is similar to the examples I've seen, but I'm doing something like:

```js
const [paymentRequest, setPaymentRequest] = useState(null);

useEffect(() => {
  const pr = stripe.paymentRequest({ [options] });

  pr.on('shippingaddresschange', (event) => {
    return getUpdatedPricing(event.shippingAddress).then(data => {
      updateWith({ [etc] });
    }).catch(err => {
      pr.abort();
    });
  });
  
  pr.canMakePayment().then(result => {
    if (result) {
      setPaymentRequest(pr);
    }
  });
}, [])
```

That's a simplified version; I actually have a handler function that I reset in a `useEffect` because there are inputs that change, and I've passed the state variable `paymentRequest` to it to do `paymentRequest.abort()`.

I've stepped through the minified Stripe code and seen that it _is_ executing, all the way to sending a `stripe-pr-abort` event to the `_frame` of the payment request's `_activeBackingLibrary`. Can't see much in the minified code but I don't see anything that seems to handle that event.

Anyway, I did see this issue in the stripe-js repo that mentions `abort`: https://github.com/stripe/stripe-js/pull/302
It says something about not being supported. Is there a reason why it shouldn't be used to begin with?

**Comment by orionharrys** [comment]
> Hi @orionharrys! The `abort` method will only work if the backing library supports it. For instance [Apple Pay does support it](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778022-abort) but Google Pay does not.

Ahh I see, thank you! Is there any way to close the interface for Google Pay then, or alternatively to display an error/disable the interface so the user must close it?

**Comment by arashn-stripe** [comment]
No problem! You can call `updateWith({ status: 'fail' })` and that will show a shipping error message.

**Comment by orionharrys** [comment]
I know about that, and that is perfect for an error where the shipping address is indeed invalid, but I'm thinking about a case like some internal error that has nothing to do with the shipping address. Aside from `paymentRequest.abort()` with Apple Pay, is there any way to display a custom error, disable the payment interface, or close it?

**Comment by arashn-stripe** [comment]
The functionality you mentioned is currently not available but I'm going to file this feature request in our internal issue tracker! We'll post here if we have any updates. Thank you!

**Comment by orionharrys** [comment]
Awesome, thanks :)
