### ISSUE TITLE
[BUG]:  Black Inputs

### ISSUE THREAD

**Issue by Gherciu** [stripe/react-stripe-js#326]
### What happened?

For some reason, CardElement inputs have a Black background when resizing the screen...or sometimes even randomly these become black if this element is in a modal or resizable element.

<img width="695" alt="Screenshot 2022-10-05 at 00 51 53" src="https://user-images.githubusercontent.com/30025953/193937111-3466917f-2084-4807-b7f7-96279aef8935.png">

From my investigation, it happens because of this line of code which I don't have access to override since it is in an iframe..

<img width="695" alt="Screenshot 2022-10-05 at 00 54 09" src="https://user-images.githubusercontent.com/30025953/193937399-c5758bea-6075-41a0-9273-bce0e5d42e94.png">

If disabling manually this transition then everything works perfect and black background disappear.

Is there a way to override this??

### Environment

Chrome last version on Mac M1 Monterey

**Comment by arashn-stripe** [comment]
Hi @Gherciu, thank you for reaching out! Would you be able to provide a codepen to reproduce this behavior?
