### ISSUE TITLE
[BUG]: The type Stripe.confirmSetup and Stripe.confirmPayment is not compatible with the documents

### ISSUE THREAD

**Issue by taco-chen** [stripe/react-stripe-js#336]
### What happened?

The type `options.redirect?` is not compatible with the documents. Currently the library only allow the type `"always" | undefined`, but it should be `"if_required" | "always" | undefined` as the document mentioned.

### Stripe.comfirmSetup(options)

From Documents: 
```
redirect
'always' | 'if_required'
By default, stripe.confirmPayment will always redirect to your return_url after a successful confirmation. If you set redirect: "if_required", then stripe.confirmPayment will only redirect if your user chooses a redirect-based payment method.
```

From Library:
```
(method) Stripe.confirmSetup(options: {
    elements: StripeElements;
    confirmParams: ConfirmPaymentData;
    redirect?: "always" | undefined;
}): Promise<{
    error: StripeError;
}> (+1 overload)
```

### Stripe.confirmPayment(options)

From Documents:
```
redirect
'always' | 'if_required'
By default, stripe.confirmPayment will always redirect to your return_url after a successful confirmation. If you set redirect: "if_required", then stripe.confirmPayment will only redirect if your user chooses a redirect-based payment method.
```

From Library:
```
(method) Stripe.confirmPayment(options: {
    elements: StripeElements;
    confirmParams: ConfirmPaymentData;
    redirect?: "always" | undefined;
}): Promise<{
    error: StripeError;
}> (+1 overload)
```

### Environment

macOS 12.6 / Chrome Version 106.0.5249.119 (Official Build) (arm64)

**Comment by christopher-stripe** [comment]
Hi @taco-chen! There are multiple signatures for `stripe.confirmPayment` defined: https://github.com/stripe/stripe-js/blob/master/types/stripe-js/stripe.d.ts#L47-L75

This is because the return type of the method changes when `if_required` is passed.
