### ISSUE TITLE
[BUG]: Apple Pay button doesn't load properly

### ISSUE THREAD

**Issue by dimylkas** [stripe/react-stripe-js#340]
### What happened?

Sometimes (4 / 10 tries) apple pay button doesn't load properly for the React component, see image from your example ![image](https://user-images.githubusercontent.com/22882779/199843239-428bf24e-095c-4fe1-bcf0-197b4a0cf5c8.png) 
https://stripe.com/docs/stripe-js/elements/payment-request-button?client=react

### Environment

IPhone XS / IPhone 14

### Reproduction

https://stripe.com/docs/stripe-js/elements/payment-request-button?client=react

**Comment by tylersmith-stripe** [comment]
Hey @dimylkas 👋,

Thank you for raising this issue with us! We're investigating the root cause and will update here when we have more insight to share.

**Comment by jima-stripe** [comment]
Hi @dimylkas!

We were able to get to the root cause of the issue and have a fix that is scheduled for deploy tomorrow. I'll be keeping an eye out as this release tomorrow, but if you continue to see issues, please let us know.

Thanks!

**Comment by dimylkas** [comment]
Hi @jima-stripe,

Is there any comment about the fix / version, is it available already? Where?

**Comment by dimylkas** [comment]
Thanks a lot!
