### ISSUE TITLE
[BUG]: Memory leak when calling window.postMessage

### ISSUE THREAD

**Issue by Regaddi** [stripe/react-stripe-js#341]
### What happened?

I'm not exactly sure if this originates from react-stripe-js or stripe-js.

**Reproduction steps:**

1. Open this [Codesandbox with a minimal reproduction](https://codesandbox.io/s/objective-hellman-3f62c1?file=/src/App.js)
2. Open Chrome DevTools with `Performance monitor` and have a look at the `DOM Nodes` count
3. Uncomment line 13 (👻) `window.postMessage('test')`
4. Watch `DOM Nodes` closely as it will increase quite rapidly

Here's also a Screencast for your convenience: https://share.cleanshot.com/wv1Z3F

**Background**

A customer of [ours](https://github.com/daily-co) reached out to us mentioning that they're experiencing a memory leak when they use our product in combination with Stripe, however they weren't able to reproduce the issue with _only_ Stripe and _only_ Daily at first. After investigating the issue I found that there _seems_ to be a `postMessage` handler in Stripe v3, which creates an `a` element, but it's not cleaned up, hence leading to an increased count of detached HTMLAnchorElements with each `postMessage`.

![image](https://user-images.githubusercontent.com/1336590/200542913-4bcdfa98-baf6-48b1-9bff-4dd24170520d.png)

I hope this report is helpful, so you're able to fix the issue right away. In case you need any additional information, please feel free to @ me.

Have a great rest of your day!
Cheers
Christian

### Reproduction

https://codesandbox.io/s/objective-hellman-3f62c1?file=/src/App.js

**Comment by jima-stripe** [comment]
Hi @Regaddi! Thanks for the quality repro steps. I'll be taking a look at this today.

**Comment by jima-stripe** [comment]
Hey @Regaddi, I was able to take a look at this, and have a couple of updates.
* The browser built-in garbage collection seems to be cleaning up those detached DOM nodes (looks like every 10 seconds). You can see the climb followed by the drop of DOM nodes in the screencast you shared. So I'm not sure there's an actual issue.
* That being said, the creation of an anchor tag DOM node to parse a URL is a bit of anti-pattern these days. I've updated stripe-js to use the [URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL) (when available) which won't require the create of a DOM node. This change is scheduled for deploy tomorrow.

**Comment by Regaddi** [comment]
Thank you, @jima-stripe!

> The browser built-in garbage collection seems to be cleaning up those detached DOM nodes (looks like every 10 seconds).

Interestingly I was only able to trigger garbage collection when resizing the browser _or_ taking a heap snapshot. I haven't seen the garbage collection in my browser kick in automatically, neither did our customer.

> This change is scheduled for deploy tomorrow.

Awesome! Thank you so much for jumping in here 🙌
