### ISSUE TITLE
[BUG]: Card element displays Link payment method by default.

### ISSUE THREAD

**Issue by vatsal-gadhiya-searce** [stripe/react-stripe-js#349]
### What happened?

We are using Card element to take payments via card. Suddenly it started displaying Link payment methods. We don't want it to get display on our checkout page. I have read stripe document and is seems they are adding it by default.

How to turn off Link payment method for my checkout page and keep only card element? Please see attached SS of the UI.
<img width="1205" alt="Screenshot 2022-11-18 at 11 43 37 AM" src="https://user-images.githubusercontent.com/75298917/202633773-e3a577a7-a48e-469d-a860-b986eac9014c.png">

EDIT: we have not  enabled Link payment methods from our stripe developer platform.

**Comment by tylersmith-stripe** [comment]
Hey @vatsal-gadhiya-searce 👋 ,

To clarify, this Link button is presenting from the [Payment Request Button Element](https://stripe.com/docs/stripe-js/elements/payment-request-button). It's correct that Link is now an option from this Element, and will display when Apple Pay and Google Pay aren't available!

You can disable the Link in PRB in a few different ways:
- From the [settings in your dashboard](https://dashboard.stripe.com/settings/link)
- From your code by passing `disableWallets: ['link']` to the options in `paymentRequest` ([API Reference](https://stripe.com/docs/js/payment_request/create#stripe_payment_request-options-disableWallets))

I hope that helps. Sorry for any confusion this caused you!

**Comment by doubleforte** [comment]
Disabling client-side doesn't work with TypeScript just yet. 

https://github.com/stripe/stripe-js/issues/390
