### ISSUE TITLE
[BUG]: Issue with creating custom prices

### ISSUE THREAD

**Issue by OllieJW** [stripe/react-stripe-js#358]
### What happened?

When using a custom price I get an error 500 while attempting to make a subscription.

```
const price = await stripe.prices.create({
      unit_amount: planPrice,
      currency: "GBP",
      recurring: {
        interval: "month",
      },
      product_data: {
        name: "Monthly subscription",
      },
    });
```
planPrice is declared as a Number so I'm really confused at what might be the issue.

Will return an error 500 whilst typing a number will work properly.
```
const price = await stripe.prices.create({
      unit_amount: 1000,
      currency: "GBP",
      recurring: {
        interval: "month",
      },
      product_data: {
        name: "Monthly subscription",
      },
    });
```

**Comment by martinalong-stripe** [comment]
Hi! For help with integration we recommend contacting [Stripe Support](https://support.stripe.com/contact/login) or asking in the [Stripe Developer Discord](https://discord.com/invite/RuJnSBXrQn). You'll be able to get more hands-on support there!
