### ISSUE TITLE
When load paymentElement component, Uncaught (in promise) TypeError: Failed to retrieve dependencies of service

### ISSUE THREAD

**Issue by jsdude0220** [stripe/react-stripe-js#362]
### What happened?

When load the PaymentElement component, there is uncaught type error in the production only.
This below console error does not happen in the local development environment, but when I deploy to the production, then faced such below issue.
Not sure what is the issue, I have disabled the google pay in the stripe dashboard, but it is still showing like that error.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/58881761/206821299-c209a71d-08e5-4df0-999e-079312c828b9.png">
 Thanks in advance if anyone experience to fix like this issue.

**Comment by cgarrovillo** [comment]
Were there any other errors alongside this? 

Does it happen constantly or is the error intermittent?

**Comment by jakeorr** [comment]
I'm seeing this occur on every load of our pages using `PaymentRequestButtonElement` and the `useStripe` hook. It doesn't appear to be affecting the ability to run transactions using the payment request button. We've tested this with apple pay and google pay, both succeed even with this error showing up.

@stripe/react-stripe-js: 1.38.1
react: 17.0.2
next: 11.1.4
nodejs: 16.18.1

**Comment by jackieosborn-stripe** [comment]
Hi! This seems to be an issue with the [Google Pay library](https://developers.google.com/pay/api/web/guides/resources/demos) we use. You can see the same console error on that page I linked. We have reached out to Google and are awaiting a response, and will report back here when we get more information.

As @jakeorr correctly pointed out, this should not affect your ability to accept payments with Google Pay.

**Comment by jackieosborn-stripe** [comment]
This now seems to be resolved - closing this issue out!
