### ISSUE TITLE
Loading Elements without blocking on a server call

### ISSUE THREAD

**Issue by justswim** [stripe/react-stripe-js#363]
### What happened?

This is half bug / half question.

The `<Elements>` provider will not render correctly without a clientSecret correctly set (it throws this error: `Uncaught IntegrationError: Invalid value for elements(): clientSecret should be a client secret of the form ${id}_secret_${secret}. You specified: .`)

However, in order to create a clientSecret, I need to make a call to the server to fetch a clientSecret, then continue rendering my app once this call returns.

In my app, the code has a check that looks something like this:
```
{ clientSecret ? (
  <Elements options={stripeOptions} stripe={stripe}>
      <MyLargeSinglePageApp />
  </Elements> )
 : null }
```

But, this means that my whole app has to block on rendering on this server call to fetch the clientSecret. This is a performance issue, as my app can't start rendering until the stripe API returns the clientSecret. Only a small fraction of my app's users will actually go through the paywall, and it would be bad to make all of them wait for the clientSecret to return. It also means that if Stripe's API goes down for any reason, then our entire app will not render while it waits for the clientSecret to return. 

The alternative is that I could wrap ONLY our paywall with the `<Elements>` provider, but Stripe seems to say that this would be worse for collecting fraud signals as users click around the application (is this true)?

Ideally I'd like to be able to render the `<Elements>` component WITHOUT a legit clientSecret, and then re-render it later when my server call returns successfully. Is there any feature or flag that would make this possible? 

If not, is there a recommended way to handle this performance issue? 

Thanks!

**Comment by jackieosborn-stripe** [comment]
Hi @justswim! You may be interested in a new beta feature we're building to make this experience better. If you visit [this docs page](https://stripe.com/docs/payments/defer-intent-creation) and click "contact us", we'll be in contact shortly!
