### ISSUE TITLE
[Enhancement]: Please add official support for Vue JS

### ISSUE THREAD

**Issue by talhameer** [stripe/react-stripe-js#364]
### What happened?

The Verified Partner of Stripe for Vue JS is no more maintaining the project, the [@vue-stripe](https://github.com/vue-stripe) is not compatible with newer versions of VueJS. Please add official support for it.

Please follow this issue [https://github.com/vue-stripe/vue-stripe/issues/289](https://github.com/vue-stripe/vue-stripe/issues/289)

**Comment by jofftiquez** [comment]
Hello @talhameer, I'm Joff author of Vue Stripe. First of all I would like to apologize for the delay, I don't wanna say it but the reasons boils down to personal issues. But, that shouldn't be an excuse, it's my fault and I will take responsibility about this soon. Thank you for your patience. Please close this issue now as it is unrelated to react-stripe-js, I how you understand.

**Comment by 1cor13** [comment]
@christopher-stripe any update on this feature request?

**Comment by brendanm-stripe** [comment]
No, we don't have any updates to share around this.
