### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by tsansome** [stripe/react-stripe-js#366]
### What happened?

When trying to load the PaymentElement i am seeing:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2570105/209833787-ca3eb855-1bfa-4b57-8a42-c88adcfe86d9.png">

Just looking for a direction on troubleshooting and a possible lead to a solution.

`<Elements stripe={stripePromise} options={{ clientSecret: props.new_vendor.stripe.setupIntent.secret }}>
      <CheckoutForm /> 
  </Elements>`
`

Then CheckoutForm is simply
`<PaymentElement />`

my packages
"@stripe/react-stripe-js": "1.16.1",
"@stripe/stripe-js": "1.46.0",
"next": "13.1.1",
"react": "^18.2.0",

**Comment by christopher-stripe** [comment]
Hi @tsansome, this looks like an issue with your integration. We aren't able to help with those here—this repository is for filing bugs with the React Stripe.js library itself, and I don't believe this is such a bug. Try [Stripe Support](https://support.stripe.com/)—they are staffed and able to help with questions like this one.
