### ISSUE TITLE
Stripe cookies set before consent

### ISSUE THREAD

**Issue by Mario8419** [stripe/react-stripe-js#367]
### What happened?

I've integrated Stripe into my app and seeing that cookies are always set immediately without, for example, giving my customers the choice of whether they want to pay with Stripe at all or not... Setting cookies without customer willing is not GDPR compliant in the EU. Does anyone have a fix for proper implementation that cookies are not set automatically with an import of stripe components?
Cookies which are set immediately in my case are for e.g:

__stripe_orig_props
stripe.csrf
private_machine_identifier
machine_identifier

thanks

**Comment by tylersmith-stripe** [comment]
Hey @Mario8419,

Please see our [Cookie Settings](https://stripe.com/cookie-settings) page for more details on when cookies are set, and how they are classified in terms of GDPR compliance. 

Stripe.js sets `private_machine_identifier` and `machine_identifier` as part of fraud prevention, and are required to function.

`__stripe_orig_props` and `stripe.csrf` are not set from Stripe.js, but rather from stripe.com

**Comment by Mario8419** [comment]
Thanks for the link, but this link is for me as a supplier and not for my application where stripe is implemented and users are faced with this type of problem! Cookies are set without consent and this is a big problem regarding GDPR in the EU. What can I do to have a compliant implementation of this plugin?

**Comment by tylersmith-stripe** [comment]
Hey @Mario8419,

Gaining consent is one of six legal justifications for data processing under GDPR. Please read more about the other five here: https://gdpr.eu/gdpr-consent-requirements/

**Preventing fraud** falls under these other 5 categories, and the two cookies I listed above, `private_machine_identifier` and `machine_identifier`, are required for that to function. Therefore, they don't require consent to be set, and you are within GDPR compliance while using Stripe.js.

Hover the tooltip on any of the cookies in our [Cookie Settings](https://stripe.com/cookie-settings) page to see our listed justification for setting of a required or optional cookie.

> `__stripe_orig_props` and `stripe.csrf` are not set from Stripe.js, but rather from stripe.com

For the other two, like I mentioned above, they did not come from Stripe.js. You received these cookies by viewing [stripe.com](https://stripe.com/) at some point in time.

All cookies set from Stripe.js are set on `js.stripe.com` domains, within our iframes in a 3rd party context to your page. I hope this helps settle your concerns! 👍

**Comment by davidfarinha** [comment]
@tylersmith-stripe 

After integrating with the plugin I get quite a few Stripe related cookies
<img width="798" alt="image" src="https://user-images.githubusercontent.com/3890344/221966512-3649a106-b818-42a4-a960-dbe15c5939bf.png">

Can you confirm if these are all 3rd party, or 3rd party in the context of the page in my application? Just trying to double-check if my usage is GDPR compliant. Cheers!

**Comment by tylersmith-stripe** [comment]
I can confirm we have not introduced any new cookies to Stripe.js, and you acquired these by visiting some other pages on https://stripe.com, or https://stripe.com/docs. Like I mentioned above, check out the [Cookie Settings](https://stripe.com/cookie-settings) page for a full breakdown on these!

Ensuring that you all are within GDPR compliance is always top of mind for us!
