### ISSUE TITLE
[BUG] [1.16.3]: IntegrationError: Can only create one Element of type card

### ISSUE THREAD

**Issue by mattmcdonald-uk** [stripe/react-stripe-js#375]
### What happened?

When including `<CardElement />` using 1.16.3 I get the error `Uncaught IntegrationError: Can only create one Element of type card`.

Rolling back to 1.16.2 fixes this without any other code changes.

**Comment by awalker-stripe** [comment]
Hi @mattmcdonald-uk,

Thank you for reporting this. I just pushed out a change in #376 that should fix this.

Could you try upgrading to version 1.16.4 and let me know if that resolves it? In the meantime, I'm going to close out the issue, but please feel free to re-open it if you have any other questions or if the issue persists.

Thanks!
