### ISSUE TITLE
[BUG]:  RTL locale is using wrong "direction"

### ISSUE THREAD

**Issue by eladchen** [stripe/react-stripe-js#379]
### What happened?

Hi,

A few issues I noticed when trying to use an RTL locale "he" (Hebrew)

- Alignment is off, even though "he" was specified as the locale, the rendered "direction" is "ltr".
- The label "CVC" is using english.

<img width="1062" alt="Screen Shot 2023-01-30 at 09 42 08" src="https://user-images.githubusercontent.com/3628913/215420813-6d190cf6-cdc0-44ea-a99f-147866aea408.png">

<img width="1055" alt="Screen Shot 2023-01-30 at 09 59 49" src="https://user-images.githubusercontent.com/3628913/215420854-be395964-7a81-4c16-a51f-cd85d5bdc5d0.png">

P.S:
- Is there an API that controls the direction?
- Is there a way to provide elements with custom texts for a locale?

**Comment by jima-stripe** [comment]
Hi Elad!

Thanks for reaching out to us.

I'll be the first to admit that RTL locales are not what I'm most familiar with. That said, here's what we do with the Payment Element to [support several locales](https://stripe.com/docs/js/appendix/supported_locales).

* We inherit the direction parameter `dir` from the host page. So our iframe will add `dir="rtl"` or `dir="ltr"` based on what is already set on the page. If the alignment is off, check that the page hosting the Payment Element has the correct `dir` property on the `<html>` tag.
* We also do translations based on the `locale` passed in. I'm not sure why CVC isn't being translated. Can you tell me what it should be translated as?

Unfortunately, the text translation is using a service and not setup to receive custom text on a merchant-by-merchant basis.

**Comment by jima-stripe** [comment]
Marking as closed since we haven't heard back. Feel free to reach back out if you have other questions/concerns.

**Comment by eladchen** [comment]
The text should be "קוד אימות"
