### ISSUE TITLE
TypeError: createElement is not recognized as a function

### ISSUE THREAD

**Issue by danseaman6** [stripe/react-stripe-js#38]
Poking around in the new beta V.6, I got the following error when attempting to load the portion of my webapp that actually contains the stripe Elements provider:

![Screenshot from 2020-02-12 07-09-48](https://user-images.githubusercontent.com/9471363/74334229-7ea60080-4d67-11ea-9904-5091c390dea6.png)

This appears to be coming from [the useEffect return statement in Elements.tsx, line 162](https://github.com/stripe/react-stripe-js/blob/7419d57ea75ad8077c506f10bfbae52898c32cd4/src/components/Elements.tsx#L169) - looks like The Provider might not be implemented properly, at first glance?

**Comment by hofman-stripe** [comment]
@danseaman6, would you be able to share a reproduction or more information on your build? E.g. what version of `react` (or preact) you're using, relevant rollup / webpack config, etc.

**Comment by danseaman6** [comment]
react-stripe-js beta.6, stripe-js beta.8
React version 16.9, and broccoli rollup. I have a component importing Elements:
`import {Elements} from "@stripe/react-stripe-js";`
and then simply wrapping a checkout form in <Elements>.

**Comment by christopher-stripe** [comment]
@danseaman6 Are you able to share your `Brocfile.js`?

**Comment by danseaman6** [comment]
It's not something I'd like to share publicly, unfortunately it's for my company's product. 
Can I give you more details about a specific part though?

**Comment by danseaman6** [comment]
IF it happens to be useful, this is the source from our compiled main.js that's throwing the error above. I'm pretty sure it's that line I identified earlier:
![Screenshot from 2020-02-12 14-22-11](https://user-images.githubusercontent.com/9471363/74369338-33a9de80-4da3-11ea-854e-8ee27a1a3e4e.png)

**Comment by danseaman6** [comment]
We load the stripe library very early on in our apps life cycle, I confirmed it's present and being pass to the Elements component correctly.

**Comment by christopher-stripe** [comment]
> It's not something I'd like to share publicly, unfortunately it's for my company's product.
Can I give you more details about a specific part though?

That's understandable. If you're OK to share: are you using any Rollup plugins? If so, which ones and what does the configuration for them look like? Particularly interested in any config for rollup-plugin-commonjs, if you're using it.

**Comment by danseaman6** [comment]
Yes, that we've got. We use `rollup-plugin-commonjs-alternate` (imported as `commonjs`), and our Brocfile has the following plugin specification:
```
        commonjs({
          ignoreGlobal: true,
          include: "node_modules/**",
          namedExports: {
            "node_modules/react/index.js": [
              "forwardRef",
              "useCallback",
              "useContext",
              "useDebugValue",
              "useEffect",
              "useImperativeHandle",
              "useLayoutEffect",
              "useMemo",
              "useReducer",
              "useRef",
              "useState",
              "createContext",
            ],
            "node_modules/react-dom/index.js": [
              "createPortal",
              "findDOMNode",
              "hydrate",
              "render",
              "createRoot",
              "unmountComponentAtNode",
            ],
          },
        })
```

**Comment by christopher-stripe** [comment]
Ah, it looks like `createElement` is missing from the `namedExports` for React. There may be other exports missing. Try this:

```
import * as React from "react";
import * as ReactDOM from "react-dom";

// ...

// In commonjs config:
namedExports: {
  react: Object.keys(React),
  "react-dom": Object.keys(ReactDOM)
}
```
