### ISSUE TITLE
[BUG]: Requires 'unsafe-eval' in Content Security Policy directive

### ISSUE THREAD

**Issue by MyHouseIsBig** [stripe/react-stripe-js#381]
### What happened?

#380

**As I wrote in the Bug Report** I followed the instructions on how to setup CSP and I correctly set up them. I'm sure about that because in the errors **that I posted** the correct headers are mentioned.

**Comment by madhav-stripe** [comment]
Hello @MyHouseIsBig. 

I saw in the previous issue that you are using Brave as your browser. Brave is currently not one of the [browsers that we support](https://stripe.com/docs/js/appendix/supported_browsers).

Can you try:
1. Loading your site in another browser?
2. Try disabling [Brave Shields](https://brave.com/shields/) to see if they're affecting the site in any way?

**Comment by MyHouseIsBig** [comment]
> Hello @MyHouseIsBig. 
> 
> 
> 
> I saw in the previous issue that you are using Brave as your browser. Brave is currently not one of the [browsers that we support](https://stripe.com/docs/js/appendix/supported_browsers).
> 
> 
> 
> Can you try:
> 
> 1. Loading your site in another browser?
> 
> 2. Try disabling [Brave Shields](https://brave.com/shields/) to see if they're affecting the site in any way?

I don't think the problem is Brave since it's based on chromium but I just tried with Firefox, Chrome and Edge. Same result.

I also tried disabling brave shields.

**Comment by MyHouseIsBig** [comment]
If that might help you I can privately send you the website link alongside temporary credentials to access it.

**Comment by madhav-stripe** [comment]
> I don't think the problem is Brave since it's based on chromium but I just tried with Firefox, Chrome and Edge. Same result.
> 
> I also tried disabling brave shields.

Is it possible to reproduce this issue in CodeSandbox or similar? We are unable to reproduce this issue on our side.
It might be caused by another script. It seems like you are loading google maps as well. Have you looked at their [CSP requirements](https://developers.google.com/maps/documentation/javascript/content-security-policy)?

**Comment by MyHouseIsBig** [comment]
I fixed the issue implementing SSR dynamic headers for ReactJs inline scripts because the headers I set up client-side weren't working correctly.
