### ISSUE TITLE
[BUG]: Elements is not reactive

### ISSUE THREAD

**Issue by armandocin** [stripe/react-stripe-js#385]
### What happened?

I would like to update the `clientSecret` if a user adds a Coupon Code after the checkout form has been rendered.

I wrote a `StripeWrapper` component that wraps the checkout form, loading the `clientSecret` and initializing `Elements`. The `useEffect` that loads the `clientSecret` is fetched whenever the cart changes in order to be reactive if a user adds a coupon.

```
const StripeWrapper = ({children}) => {
  const [clientSecret, setClientSecret] = useState('')
  const cart = useSelector(state => state.cart)

  useEffect(() => {
    if (cart) {
      let clientSecretTypePromise = (
        cart.coupon
          ? getStripeCheckoutWithCouponSecret(cart.id, cart.coupon)
          : getStripeCheckoutSecret(cart.id)
      )

      clientSecretTypePromise
        .then(({ clientSecret }) => setClientSecret(clientSecret))
    }
  }, [cart])


  if (!clientSecret) {
    return null
  }

  return (
    <Elements
      options={{ clientSecret }}
      stripe={stripePromise}
      locale='en'
    >
      {children}
    </Elements>
  )
}
```

The issue is that Elements doesn't update if the `options` prop changes. Also visiting your code base it seems that if an instance of `stripe` already exists in `Elements` the context `ctx` is not updated.

This makes a React component un-reactive.   
For this reason, the user gets billed the amount without a coupon.

This update of `clientSecret` is also a problem for performances as reported in https://github.com/stripe/react-stripe-js/issues/363
That is, we have to wait to load the clientSecret before rendering `Elements`.

Am I missing something?

Thanks!

**Comment by jackieosborn-stripe** [comment]
Hi @armandocin! You may be interested in a new beta feature we're building to make this experience better. If you visit [this docs page](https://stripe.com/docs/payments/defer-intent-creation) and click "contact us", we'll be in contact shortly!
