### ISSUE TITLE
[BUG]: `.Input:hover` styles overriding `.Input:focus`

### ISSUE THREAD

**Issue by philiplindberg** [stripe/react-stripe-js#390]
### What happened?

I'm trying to change the appearance of Stripe Elements using the following rules of the [Appearance API](https://stripe.com/docs/elements/appearance-api):

```ts
import { Elements } from '@stripe/react-stripe-js'

<Elements
  ...
  options={{
    ...
    appearance: {
      rules: {
        '.Input': {
          boxShadow: 'none',
          border: `1px solid ${colorWithOpacity(theme.colors.foreground, 0.2)}`,
        },
        '.Input:hover': {
          borderColor: colorWithOpacity(theme.colors.foreground, 0.35),
        },
        '.Input:focus': {
          borderColor: theme.colors.primary,
          boxShadow: 'none',
        },
      },
    },
  }}
>
  <CheckoutForm ... />
</Elements>
```

However, I'm noticing that the `.Input:hover` styles are overriding the `.Input:focus` styles when an input is both focused and hovered. Is it possible to have the `.Input:focus` styles take precedent in this scenario?

### Environment

Chrome 111 on macOS 13.2.1

**Comment by christopher-stripe** [comment]
Hi @philiplindberg, try changing the `.Input:hover` selector to `.Input:hover, .Input:hover:focus`. I believe that should resolve the issue.
