### ISSUE TITLE
[BUG]: Elements options dont match stripe docs

### ISSUE THREAD

**Issue by mPaella** [stripe/react-stripe-js#392]
### What happened?

The [stripe docs detail this use case](https://stripe.com/docs/payments/payment-element/migration?integration-path=one-time&client=react#one-time-update-elements), where the `mode`, `currency`, and `amount` as well as some other options are passed to the `Elements` options

However, the `Elements` options dont allow for these props

```typescript
<Elements
         stripe={stripePromise}
         options={{
            mode: "payment",
            currency: "usd",
            amount: 1000,
            captureMethod: "manual",
        }}
>
```

Type error
```
Type '{ mode: string; currency: string; amount: number; captureMethod: string; }' is not assignable to type 'StripeElementsOptions'.
  Object literal may only specify known properties, and 'mode' does not exist in type 'StripeElementsOptions'.ts(2322)
react-stripe.d.ts(671, 5): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & ElementsProps & { children?: ReactNode; }'
```

Adding a `@ts-expect-error` allows the `PaymentElement` to render accordingly with the docs

https://stripe.com/docs/payments/payment-element/migration?integration-path=one-time&client=react#one-time-update-elements

### Environment

@stripe/react-stripe-js@2.1.0, @stripe/stripe-js@1.52.0

**Comment by bmathews-stripe** [comment]
@mPaella The types are looking correct on the latest versions:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/93609068/228321658-0bc956fa-c124-4a8e-bedf-61e9c0f866d6.png">

https://codesandbox.io/s/react-stripe-js-392-dhnw14?file=/src/index.tsx

Can you triple check that your dependencies are up to date and your editor is restarted?

**Comment by mPaella** [comment]
That was it 🤦

Thank you, closing

**Comment by nkeil** [comment]
I fixed the type error by setting the types of appearance and options explicitly:
```tsx
import {
  type Appearance,
  type StripeElementsOptions,
} from '@stripe/stripe-js';

...

const appearance: Appearance = {
  theme: 'stripe',
};

const options: StripeElementsOptions = {
  clientSecret,
  appearance,
};
```
