### ISSUE TITLE
[BUG]: createPaymentMethod doesnt return any errors

### ISSUE THREAD

**Issue by ertemishakk** [stripe/react-stripe-js#393]
### What happened?

```
return await stripe
          .createPaymentMethod({
            type: 'card',
            card: cardElement,
            billing_details: {
              name: fullName,
              email: email!,
              phone: mobile!,
            },
          })
          .then(({ paymentMethod, error }) => {
            console.log(paymentMethod, error);
          })
          .catch(e => {
            throw e;
          });
```
          
          I cant get createPaymentMethod to return any error messages using any of the test cards
          
          4000000000000002
          4000000000000127

### Environment

chrome and mac

**Comment by christopher-stripe** [comment]
Hi, this looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help.
