### ISSUE TITLE
[BUG]: firefox with uBlock generates a lot of request (always retrying) even after successful payment

### ISSUE THREAD

**Issue by severinwullschleger** [stripe/react-stripe-js#394]
### What happened?

When visiting https://stripe.dev/elements-examples/ the page is slowed down because of many requests even after the payment was successful.

### Environment

Firefox 111.0.1 (64-bit) with uBlock Origin 1.48.2

**Comment by willf668** [comment]
Also happening for me with Firefox 112.0.2 and UBlock Origin.
