### ISSUE TITLE
[BUG]:  SETUP INTENT DOUBLE CLICK

### ISSUE THREAD

**Issue by laneazzi** [stripe/react-stripe-js#395]
### What happened?

I have to call setup intent twice the first time I try to add a payment method for a user that does not have a customer id. We are using the full code implementation, and customer id is being created and properly sent to the setup intent api.

### Environment

Chrome, VScode, Linux

**Comment by brendanm-stripe** [comment]
Hey @laneazzi can you please provide more details of the issue you're experiencing? What do you mean by:
> I have to call setup intent twice
Can you share the requests you're making and some example snippets and/or any related errors?

**Comment by laneazzi** [comment]
Hey, will get back to you with the details once my BE dev is available.
