### ISSUE TITLE
[Feature]: Expose BIN for CardElement

### ISSUE THREAD

**Issue by sebastienlabine** [stripe/react-stripe-js#397]
### What happened?

Hi,

We have a use case where we need to access the user's BIN number for the credit card.

As it's not considered sensible information for PCI Compliance, we would love to know if this information could be exposed and retrieved on our end.

Thanks

**Comment by brendanm-stripe** [comment]
Hey @sebastienlabine -- you should write in to our support team [here](https://support.stripe.com/contact) with a description of your use case / need for this to determine what options are available for your account.
