### ISSUE TITLE
[FEATURE]: Pricing Table Element

### ISSUE THREAD

**Issue by Redskinsjo** [stripe/react-stripe-js#398]
### What happened?

I am trying to customize my pricing table and this using React, but @stripe/react-stripe-js doesn't include a PricingTable element in its API

**Comment by brendanm-stripe** [comment]
The Pricing Table is implemented as a [web component](https://stripe.com/docs/no-code/pricing-table#embed) -- there is no corresponding Element in Stripe.js (or react-stripe-js). The customization is done in the Dashboard UI, then the web component can be included in any client application. The docs show how to do this in React, too, by ensuring `pricing-table.js` is included in your root `index.html` file.

**Comment by Redskinsjo** [comment]
I know how to integrate it with a <script> and the web component, but I'd like to do it with a React component. Customizing font and colors is possible in the dashboard, but I need to customize font size, padding, etc

**Comment by brendanm-stripe** [comment]
That pattern is not supported, but you could take the generated structure produced by our Pricing Table to recreate as your own customizable component with the buttons using individual payment links that you manage yourself.
