### ISSUE TITLE
[BUG]: Unable to load elements on initial load of page (using v2 & v3)

### ISSUE THREAD

**Issue by george-aidonidis** [stripe/react-stripe-js#399]
### What happened?

Hello! We are using the `<Elements />` from the react-stripe-js package and we are getting the following error on the first load:

```
Uncaught (in promise) Error: Invalid prop `stripe` supplied to `Elements`. We recommend using the `loadStripe` utility from `@stripe/stripe-js`. See https://stripe.com/docs/stripe-js/react#elements-props-stripe for details.
```

Our app uses both v2 & v3 that the docs specify it's possible to do
https://stripe.com/docs/stripe-js/elements/migrating#setup

### Environment

Firefox 113.0b9, MacOS 13.3.1

### Reproduction

https://codesandbox.io/s/stripe-elements-error-u9opfx?file=/src/App.js

**Comment by brendanm-stripe** [comment]
I don't really understand your `load` event listener to add stripe.js v2, but if I modify your example to load both using the script tags as shown in the docs the elements appear to work as expected:
https://codesandbox.io/s/stripe-elements-error-forked-kp8opb?file=/public/index.html:230-350

I'm also curious on your use case for this, and what part of your react app integration depends on v2.

**Comment by george-aidonidis** [comment]
Hey, thank you for the support. Indeed adding both versions work and I think the reason behind it is the [stripe-js](https://github.com/stripe/stripe-js/) logic when checking `Window.stripe` here:

https://github.com/stripe/stripe-js/blob/2f515ce6af32957fc654c9be42c8bfae5709244b/src/shared.ts#L87-L90

Which when using only V2 was not enough and it didn't move further to inject the V3 script

Something worth mentioning is that after both scripts are attached the window.Stripe object has:

```
window.Stripe.version -> 2
window.Stripe.StripeV3
```

I assume that helps supporting both versions.

Thanks again for the help 🙇‍♂️
