### ISSUE TITLE
[BUG]: blocked frame with origin "https://example.com" from accessing frame with origin "https://js.stripe.com"

### ISSUE THREAD

**Issue by bebeun** [stripe/react-stripe-js#405]
### What happened?

We use a basic react stripe integration with react-stripe-js.

Everything works well with chrome & firefox. But with Safari (15.6 & +) stripe iframe creates the following error and crash our app : 

<img width="1394" alt="Screenshot 2023-05-22 at 15 59 17" src="https://github.com/stripe/react-stripe-js/assets/11339074/08c4b653-96e3-460d-ae48-ad32ab77ea71">

Nothing in our app interacts with stripe so this bug is quite difficult to investigate.

any idea ? help welcome...

**Comment by brendanm-stripe** [comment]
Can you clarify if/how you app is integrating Stripe & `react-stripe-js`? In particular I don't understand what you mean here:
> Nothing in our app interacts with stripe 

Is there a public site we can access to see this behaviour? Are there any steps to follow to reproduce?
