### ISSUE TITLE
[BUG]: TypeError: Network request failed

### ISSUE THREAD

**Issue by mxevilll** [stripe/react-stripe-js#407]
### What happened?

import React, { useState } from 'react';
import { View, Text, Button } from 'react-native';
import { CardField, useStripe } from '@stripe/stripe-react-native';
import axios from 'axios';

const BASE_URL = 'http://localhost:4242'; // Базовый URL вашего локального сервера Stripe

const PaymentScreenEnglish = () => {
  const { confirmPayment, handleCardAction } = useStripe();
  const [loading, setLoading] = useState(false);

  const makePaymentRequest = async (paymentData) => {
    try {
      const response = await axios.post(`${BASE_URL}/make-payment`, paymentData);
      return response.data;
    } catch (error) {
      throw new Error('Payment request failed.');
    }
  };

  const handlePayment = async () => {
    try {
      setLoading(true);
      const paymentData = {
        type: 'Card',
        billingDetails: {
          name: 'John Doe',
        },
        amount: 1499, // сумма платежа в центах (1499 центов = $14.99)
        currency: 'usd', // валюта платежа
        paymentMethodType: 'card', // тип платежного метода
      };
      const { paymentIntent, error } = await makePaymentRequest(paymentData);

      if (error) {
        // Обработка ошибки при подтверждении оплаты
        console.log('Payment failed:', error);
      } else if (paymentIntent) {
        if (paymentIntent.status === 'succeeded') {
          // Оплата прошла успешно
          console.log('Payment succeeded!');
        } else if (paymentIntent.status === 'requires_action') {
          // Дополнительные действия требуются от пользователя
          const { error: actionError, paymentIntent: updatedPaymentIntent } = await handleCardAction(paymentIntent.clientSecret);
          if (actionError) {
            // Обработка ошибки дополнительных действий
            console.log('Error handling card action:', actionError);
          } else if (updatedPaymentIntent.status === 'succeeded') {
            // Оплата прошла успешно после выполнения дополнительных действий
            console.log('Payment succeeded!');
          }
        }
      }
    } catch (e) {
      // Обработка общих ошибок
      console.log('Error:', e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <View>
      <Text>Payment Screen</Text>
      <CardField
        postalCodeEnabled={false}
        placeholder={{
          number: '4242 4242 4242 4242',
        }}
        cardStyle={{
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
        }}
        style={{
          width: '100%',
          height: 50,
          marginVertical: 10,
        }}
      />
      <Button title="Pay" onPress={handlePayment} disabled={loading} />
    </View>
  );
};

export default PaymentScreenEnglish;

help me please

 LOG  Error: [Error: Payment request failed.]

**Comment by mxevilll** [comment]
server code is
// server.js
//
// Use this sample code to handle webhook events in your integration.
//
// 1) Paste this code into a new file (server.js)
//
// 2) Install dependencies
//   npm install stripe
//   npm install express
//
// 3) Run the server on http://localhost:4242
//   node server.js

// The library needs to be configured with your account's secret key.
// Ensure the key is kept out of any version control system you might be using.
const stripe = require('stripe')('sk_test_5**************');
const express = require('express');
const app = express();


// This is your Stripe CLI webhook secret for testing your endpoint locally.
const endpointSecret = "whsec_************";

app.post('/webhook', express.raw({type: 'application/json'}), (request, response) => {
  const sig = request.headers['stripe-signature'];

  let event;

  try {
    event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret);
  } catch (err) {
    response.status(400).send(`Webhook Error: ${err.message}`);
    return;
  }

  // Handle the event
  switch (event.type) {
    case 'payment_intent.amount_capturable_updated':
      const paymentIntentAmountCapturableUpdated = event.data.object;
      // Then define and call a function to handle the event payment_intent.amount_capturable_updated
      break;
    case 'payment_intent.canceled':
      const paymentIntentCanceled = event.data.object;
      // Then define and call a function to handle the event payment_intent.canceled
      break;
    case 'payment_intent.created':
      const paymentIntentCreated = event.data.object;
      // Then define and call a function to handle the event payment_intent.created
      break;
    case 'payment_intent.partially_funded':
      const paymentIntentPartiallyFunded = event.data.object;
      // Then define and call a function to handle the event payment_intent.partially_funded
      break;
    case 'payment_intent.payment_failed':
      const paymentIntentPaymentFailed = event.data.object;
      // Then define and call a function to handle the event payment_intent.payment_failed
      break;
    case 'payment_intent.processing':
      const paymentIntentProcessing = event.data.object;
      // Then define and call a function to handle the event payment_intent.processing
      break;
    case 'payment_intent.requires_action':
      const paymentIntentRequiresAction = event.data.object;
      // Then define and call a function to handle the event payment_intent.requires_action
      break;
    case 'payment_intent.succeeded':
      const paymentIntentSucceeded = event.data.object;
      // Then define and call a function to handle the event payment_intent.succeeded
      break;
    // ... handle other event types
    default:
      console.log(`Unhandled event type ${event.type}`);
  }

  // Return a 200 response to acknowledge receipt of the event
  response.send();
});

app.listen(4242, () => console.log('Running on port 4242'));

**Comment by brendanm-stripe** [comment]
@mxevilll it sounds like either the client or server is unable to reach Stripe's API servers (IPs [here](https://stripe.com/docs/ips#ip-addresses))

You should try running our reachability script ([here](https://github.com/stripe/stripe-reachability#usage)) from both machines to ensure you're able to reliably reach Stripe's servers, and reach out via support if you need further assistance: https://support.stripe.com/contact
