### ISSUE TITLE
[BUG]: hsl support in appearance rules

### ISSUE THREAD

**Issue by shshaw** [stripe/react-stripe-js#411]
### What happened?

I'm trying to use some brand colors in the Stripe Elements Appearance values. We store all of those colors as `hsl()` in a totally normal CSS color value format ( `hsl(227.37deg 12.26% 30.39%)` for example).

Here's what I'm passing to Stripe Elements:
```
{
    "appearance": {
        "variables": {
            "colorBackground": "hsl(227.37deg 12.26% 30.39%)",
            "colorDanger": "hsl(358.46deg 100% 61.76%)"
        }
    }
}
```

Here are the errors I get in the browser console:
```
stripe.elements(): "hsl(227.37deg 12.26% 30.39%)" is not a supported value for the "colorBackground" property; the "%" character is not supported
stripe.elements(): "hsl(358.46deg 100% 61.76%)" is not a supported value for the "colorDanger" property; the "%" character is not supported
```

Hex and `rgb()` values seem to be fine when I test them.

Does Stripe Elements support `hsl()` values? (The documentation does not clarify what color formats are supported anywhere I could see.)
If so, can this `%` validation check account for `hsl()` values? There's no other way to declare saturation and lightness than with the `%` values.

### Environment

@stripe/react-stripe-js 2.1.1, Chrome 114.0.5735.133, macOS 13.4.1

**Comment by brendanm-stripe** [comment]
Hey @shshaw thanks for sharing -- I'm looking into this

**Comment by alexoser-stripe** [comment]
This fix actually has been deployed and you should be able to pass hsl colors now in the format `hsl(hue, saturation, lightness)`. For example:

```
{
  "appearance": {
    "variables": {
      "colorBackground": "hsl(227.37deg, 12.26%, 30.39%)",
      "colorDanger": "hsl(358.46deg, 100%, 61.76%)"
    }
  }
}
```

Let me know if this works for you!

**Comment by brendanm-stripe** [comment]
@shshaw notice in @alexoser-stripe 's example above, the `hsl()` value specifically needs to include the comma separated values, rather that space separated as used in your original description.

**Comment by shshaw** [comment]
This does seem to be fixed. I did have to adjust our setup to produce comma separated values, but otherwise it worked as expected. 

I wrote a little helper that can pull our values directly from the CSS variables in the page which is super helpful for light & dark toggles.

```
function getCSSValue(variableName) {
  return getComputedStyle(document.documentElement).getPropertyValue(variableName);
}

export function getStripeElementsAppearance() {
  const textColor = getCSSValue('color');
  const tabBackground = getCSSValue('--brand-color-12');

  return {
    variables: {
      fontFamily: getCSSValue('--brand-font-family'),
      colorBackground: getCSSValue('--brand-color-button'),
      colorPrimary: textColor,
      colorPrimaryText: textColor,
      colorText: textColor,
      colorDanger: getCSSValue('--brand-color-red')
    }
    ...
  };
}
```

Thanks so much for patching!
