### ISSUE TITLE
[BUG]: Network request pending causes `stripe.confirmCardPayment` to hang indefinitely

### ISSUE THREAD

**Issue by jsindos** [stripe/react-stripe-js#413]
### What happened?

I am running an automated Puppeteer test that utilises `@stripe/stripe-js`. Occasionally, the following resource fails to load `https://js.stripe.com/v3/controller-40ef05cf99ae2bbb99aaa40e0ab1ce9c.html`.

This can be seen in network tab:

<img width="728" alt="image" src="https://github.com/stripe/react-stripe-js/assets/8110172/e854e013-0970-42ae-92da-27d8fbc57364">

<hr />

When this occurs, calling `await stripe.confirmCardPayment(paymentIntent.client_secret)` hangs indefinitely.

I'm wondering if anyone else has encountered a similar issue or knows how to fix?

### Environment

Chrome Version 114.0.5735.106 (Official Build) (x86_64) on macOS 12.6.1

**Comment by fruchtose-stripe** [comment]
Hi, this looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help.
