### ISSUE TITLE
[BUG]: IntegrationError Apple Pay, Chrome iOS

### ISSUE THREAD

**Issue by nikita-s-sauce** [stripe/react-stripe-js#414]
### What happened?

After trying to pay by Apple Pay error "Something went wrong. Unable to show Apple Pay. Please choose a different payment method and try again.

I have a checkout page where users can change different parameters for buying goods and after changing them price is recalculated and the user could pay the changed price.

#### Reproduces on
- Safari 16.5 / MacOsX 10.15.7
- Chrome 114.0.5 / iPhone 12 mini, iOS 16.1, 
- Mobile Safari 16.0 / iPhone 11 Pro, iOS 16.0.2, 

#### mobile and desktop Safari: console errors
```
1. IntegrationError: show() must be called from a user gesture handler (such as a click handler, after the user clicks a button).
2. IntegrationError: You cannot update Payment Request options while the payment sheet is showing.
```

#### package.json
```
    "@stripe/react-stripe-js": "^2.1.0",
    "@stripe/stripe-js": "^1.52.1",
```

1. Other payment methods work well -  card + google pay on different devices, OSs, and browsers.
2. On Mobile Chrome reproduces every 9th click on the pay button
3. On Safari and Mobile Safari every 6-9th click on the pay button caused this error
4. Mobile Chrome I can't debug. Maybe there are some good instruments to look into the console and find Errors?
5. So the main problem on a Mobile Chrome because it showing very often

![image](https://github.com/stripe/react-stripe-js/assets/127029613/75170337-b75a-4ef0-9040-c092980e04b4)

### Environment

Iphone 12 mini, iOS 16.1, Chrome 114.0.5

**Comment by brendanm-stripe** [comment]
hey @nikita-s-sauce can you share exactly how you're integrating here? ie, how are you initializing and loading the react Elements and the repro steps to see this (even if not 100% consistent).

**Comment by nikita-s-sauce** [comment]
@brendanm-stripe Thanks, sure

Here is a simplified version of our integration https://gist.github.com/nikita-s-sauce/bb7e8f77a9318486d7ab6f0b3f3a06e8
I've imported all in one file to make it more transparent to view.

We are using
- `stripe.confirmPayment`
- `elements.fetchUpdates()`
- `loadStripe`

**Comment by bmathews-stripe** [comment]
Hi @nikita-s-sauce,

I didn't see this in your example integration, but are you running anything async after the submit is clicked but before confirmation? E.g.,:

```
async function handleSubmit() {
 setLoading(...)
 await doSomethingAsync();
 const result = await stripe.confirmPayment({ ... });
}
```

If so, that will trigger the errors you're seeing if the 'doSomethingAsync' takes longer than 1 second. Apple Pay requires that it's spawned within 1 second of a click event. A way to mitigate this is to call `const { error: validationError } = await elements.submit()` immediately in the click event handler, like:

```
async function handleSubmit() {
 setLoading(...)

 const { error: validationError } = await elements.submit();
 if (validationError) return ...

 await doSomethingAsync();

 const result = await stripe.confirmPayment({ ... });
}
```

`elements.submit()` triggers form validation and collects wallet information.

**Comment by nikita-s-sauce** [comment]
@bmathews-stripe Thanks, you are right, I am sending a request to my backend to check finally all data of a checkout page between `handleSubmit` and `stripe.confirmPayment`.

I will try to do it before a user clicks on a submit button.

**Comment by nikita-s-sauce** [comment]
After I removed the backend request after submitting the button and confirming payment, Apple Pay had begun to work.

Also, I measured my request to the backend, and the duration is between 400-600ms, and in iOS Chrome it isn't working with such timings, so even if I speed up this request, I don't think it will start to work also.
