### ISSUE TITLE
[BUG]: Autocompleted Addresses Not Populating Accurately 

### ISSUE THREAD

**Issue by luckyape** [stripe/react-stripe-js#415]
### What happened?

When filling out AddressElement some auto completions do not get populated accurately when selected. 
For example the address api successfully finds and completes this address:

10968 Hwy 217 Tiverton, Nova Scotia, Canada

Selecting the autocompleted address results in the following data being populated:

Line 1: Highway 217
Line 2: 
City: Tiverton 
Province: Nova Scotia 
Postal Code: 
![Screenshot 2023-07-01 at 8 13 58 AM](https://github.com/stripe/react-stripe-js/assets/793936/b334694c-7da8-4ce9-93bd-bcbf45221ced)
![Screenshot 2023-07-01 at 8 13 47 AM](https://github.com/stripe/react-stripe-js/assets/793936/4159af04-0d4c-42de-a31e-cf735d8f6723)

### Environment

Safari Version 16.4 (18615.1.26.110.1), Chrome Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by brendanm-stripe** [comment]
Hey @luckyape I don't think this is directly related to use of `react-stripe-js` unless you've found the same works as expected with a vanilla HTML/JS integration. I can try that repro myself, though.

Could potentially be related to browser autofill issue already being investigated: https://github.com/stripe/stripe-js/issues/457

For this issue, are you finding this is a category of issues for a particular address pattern/group you can describe, or fails for this particular example without other samples?

**Comment by luckyape** [comment]
@brendanm-stripe upon more diligent investigation I was able to confirm you are correct.

the google api return this object as a prediction:
```
[
    {
        "description": "10965 Hwy 217, Digby, NS, Canada",
        "matched_substrings": [
            {
                "length": 7,
                "offset": 6
            }
        ],
  ...
        "terms": [
            {
                "offset": 0,
                "value": "10965"
            },
            {
                "offset": 6,
                "value": "Hwy 217"
            },
            {
                "offset": 15,
                "value": "Digby"
            },
            {
                "offset": 22,
                "value": "NS"
            },
            {
                "offset": 26,
                "value": "Canada"
            }
        ],
        "types": [
            "route",
            "geocode"
        ]
    }
] 
```

However the data in the response to the user selection of the prediction is as follows:

```
[
  {
    "long_name": "Highway 217",
    "short_name": "Hwy 217",
    "types": [
      "route"
    ]
  },
  {
    "long_name": "Digby",
    "short_name": "Digby",
    "types": [
      "administrative_area_level_2",
      "political"
    ]
  },
  {
    "long_name": "Nova Scotia",
    "short_name": "NS",
    "types": [
      "administrative_area_level_1",
      "political"
    ]
  },
  {
    "long_name": "Canada",
    "short_name": "CA",
    "types": [
      "country",
      "political"
    ]
  }
]
```

Thanks for your time.
