### ISSUE TITLE
[BUG]: LinkAuthenticationElement placeholder text

### ISSUE THREAD

**Issue by mPaella** [stripe/react-stripe-js#416]
### What happened?

The `LinkAuthenticationElement ` doesn't have any placeholder value, and cannot set through props

![image](https://github.com/stripe/react-stripe-js/assets/93682696/467e3729-23a1-4196-a508-0748a919e45f)

**Comment by brendanm-stripe** [comment]
Thanks for raising this @mPaella -- we're working on it! 

I can update here when there's news to share.

**Comment by brendanm-stripe** [comment]
Hey there -- you should now see "email address" (localized) as a placeholder in the link authentication element. Please let me know if you still have any issue!
