### ISSUE TITLE
[BUG]: ExpressCheckout - onShippingRateChange, inconsistent event structure.

### ISSUE THREAD

**Issue by james-william-r** [stripe/react-stripe-js#417]
### What happened?

_Fully appreciate that the Express Checkout is still in beta, but thought this was worth mentioning._

I'm running a function via the onShippingRateChange prop on the ExpressCheckoutElement:
<ExpressCheckoutElement options={elementOptions.expressElement} onConfirm={handleSubmit} onReady={onReady} onClick={onClick} onShippingRateChange={onShippingRateChange} />

It all works, however according to the API docs (https://stripe.com/docs/js/elements_object/express_checkout_element_shippingratechange_event) the shipping rate should be available at `event.shippingRate`, but it is not.

When using Link, it's available at: event.data.req.shippingOption, and when using Apply Pay it's: event.shippingMethod, not sure about the other express methods.

Maybe it's something I'm doing? 🤷

Here's the function as I'm currently having to run it:
```
const onShippingRateChange = async ({ resolve }) => {
    console.log(event);
    try {
      const response = await fetch(`/api/checkout/${checkout.id}`, {
        method: "PUT",
        headers: {
          Accept: "application/json, text/plain, */*",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ shipping_rate: event.shippingMethod?.identifier || event.data?.req.shippingOption.id }),
      });

      if (response.ok) {
        console.log("[Express Checkout] Shipping Rate Changed.");
        const res = await response.json();
        elements.update({ amount: res.total });
        console.log("[Express Checkout] Total updated: " + res.total);
      } else {
        throw new Error("[Express Checkout] Unable to Change Shipping Rate.");
      }
    } catch (error) {
      console.log(error);
    } finally {
      resolve();
    }
  };
```

### Environment

Safari and Arc (Chrome) - macOS 14.0 Beta (23A5286g)

**Comment by brendanm-stripe** [comment]
Hey @james-william-r thanks for reporting this, however after setting up a test integration with this event I am not able to reproduce what you describe. For all Express Checkout button types I'm seeing the `shippingratechange` event with the expected `shippingRate` on the event object.

Can you share more detail about your integration so we can try to reproduce or identify a potential issue for you? Do you have a minimal reproduction we could access to inspect?

**Comment by brendanm-stripe** [comment]
Actually, in looking at your snippet again I think I see the issue:
```
const onShippingRateChange = async ({ resolve }) => {
    console.log(event);
    // ...
}
```

What is `event` here? It's not assigned in the signature of `onShippingRateChange`. With the destructuring pattern, can you try changing your function to this:

```
const onShippingRateChange = async ({ resolve, shippingRate }) => {
    console.log(shippingRate);
    // ...
}
```
With `shippingRate` taken from the new event, you should find this consistently populated as documented.

Let me know if you still have trouble after that change!

**Comment by james-william-r** [comment]
Oh boi, yeah that was it, thanks! 😅

Was following one of the Stripe docs somewhere that made it seem like it should've been available from event, will see if I can find it again so it can be updated.

**Comment by james-william-r** [comment]
@brendanm-stripe Here we are, this is the example I was following: https://stripe.com/docs/elements/express-checkout-element/accept-a-payment#handle-click-event

Maybe I'm missing something obvious? Looks like shippingRate should be available from the event here though...

---
<img width="834" alt="Screenshot 2023-07-12 at 12 30 44 pm" src="https://github.com/stripe/react-stripe-js/assets/66140148/1ca16d00-a8fb-4961-a9f9-7fa340111679">

**Comment by brendanm-stripe** [comment]
Hmm are you seeing an outdated snippet? When I view those docs I see:
```
expressCheckoutElement.on('shippingratechange', async (event) => {
[...]
});
```
Note the event handler signature is `async (event) =>` instead of `async ({resolve}) =>` like you show. Which is the different leading to `event` not being defined as expected. Your code needs to either destructure `shippingRate` alongside `resolve` or switch to take the entire `event` argument.

Can you make either change to retest it works as you need? I'll review the docs again to ensure they are showing the correct pattern.

**Comment by brendanm-stripe** [comment]
Oh, I see the issue now. What you showed is in the snippets on the React tab only, not the HTML+JS tab. I will get that fixed.

**Comment by brendanm-stripe** [comment]
The docs are now corrected -- thanks for filing this to let us know so we could fix it!

<img width="837" alt="ece-events" src="https://github.com/stripe/react-stripe-js/assets/57721954/8f41c39e-0570-4bbe-958f-b316ada35b1b">
