### ISSUE TITLE
[BUG]: Using "locale" prints a warning

### ISSUE THREAD

**Issue by eladchen** [stripe/react-stripe-js#418]
### What happened?

When the elements options has "locale" a warning is printed.

```jsx
<Elements stripe={stripe} options={{ locale: "en", ... }}>
...
</Elements>
```

The above used to work, and is actually [documented as a valid parameter](https://stripe.com/docs/js/elements_object/create).

<img width="835" alt="Screenshot 2023-07-13 at 20 43 18" src="https://github.com/stripe/react-stripe-js/assets/3628913/787f73d3-ab43-4bc1-883d-293a4ea252ec">

**Comment by brendanm-stripe** [comment]
Hey @eladchen thanks for the report! We're working on a fix for this. Just want to make sure, you're not having issues with blocked payment related to this, correct?

**Comment by eladchen** [comment]
No, everything works.

**Comment by brendanm-stripe** [comment]
The warning is incorrect, and `locale` should work as expected. We'll be fixing this in an upcoming release.

**Comment by brendanm-stripe** [comment]
This should now be resolved. If you continue to see the warning, please let us know!
