### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by talkingtab** [stripe/react-stripe-js#42]
When running the example hooks/2-split card with react 16.12, built with parceljs
I get this error:
Uncaught ReferenceError: regeneratorRuntime is not defined
This is in the handleSubmit method of CheckoutForm.
It can be fixed by removing "async" on the declaration for handleSubmit() and then 
having stripe.createPayment({blah}).then(payload => { etc})

Tried this on both Chromium and Firefox

**Comment by dweedon-stripe** [comment]
Hi @talkingtab,

Thanks for the report, but given the prevalence of `create-react-app` which bundles `regeneratorRuntime` by default, I think we will keep the `async`/`await` syntax for now.

There is an open issue in the Parcel repo that might help you resolve this:
https://github.com/parcel-bundler/parcel/issues/1762

**Comment by talkingtab** [comment]
Thats fine. I would suggest that you consider testing in a parcel environment as well. It is trivial to set up, convert a project and use parcel. I've been an avid fan of CRA for several years and just converted four projects @ about 5 minutes per project.  I'm only suggesting that you document any gotcha's for converts. 

And BTW, my impression is this is much cleaner and better than the old system! Thanks!
