### ISSUE TITLE
[BUG]: Stripe form in a dialog => We could not retrieve data from the specified element

### ISSUE THREAD

**Issue by lokomass** [stripe/react-stripe-js#420]
### What happened?

Hi,

I wrapp a card form in a dialog component to change user payment card.
This work fine, if the user fill form once, complet this and submit.

To reproduce the problem, open dialog, and close it, then re-open it and type a char in the card form => this trigg the error

![image](https://github.com/stripe/react-stripe-js/assets/7886368/240b55d5-ded8-4e4f-9665-fc1024e92cd6)

My code : 

Compte.js
```
...
<Elements stripe={key}>
    <Stripe
        open={editCard}
        setOpen={setEditCard}
    />
</Elements>
...
```

Stripe.js
```
...
return (
    <Dialog>
        <DialogContent>
            <form onSubmit={Submit} className="stripe-form stripe-form-modal">
                ...
            </form>
        </DialogContent>
    </Dialog>
)
...
```

**Comment by brendanm-stripe** [comment]
Can you share more detail about how you're using Elements inside that form, and what `Dialog` does?

It seems like the Dialog might lead to the contained `PaymentElement` from being unmounted, but if it's re-mounted on the next open I would expect this to work.

Can you share a minimal/barebones reproduction in something like CodeSandbox?

**Comment by lokomass** [comment]
Thanks for reply
Yes i can push a sansbox but can I set my Stripe key safely ?

**Comment by brendanm-stripe** [comment]
A publishable key is safe, yes, but never include a secret key. If you don't want to use the `pk_test_123` of your main account, you can quickly create a separate test mode only account using the Account Switcher in the dashboard and use the test PK from that:
<img width="526" alt="create-new-account-dash" src="https://github.com/stripe/react-stripe-js/assets/57721954/9eefc378-8a6c-4572-983e-3be7d08d35b5">

**Comment by lokomass** [comment]
Here is a sandbox with the strictly same code... but the problem isn't exist on sandbox, I really don't understand ....

https://codesandbox.io/s/laughing-dew-ms7yh7?file=/src/App.js

**Comment by brendanm-stripe** [comment]
Thank you for sharing that! But, yes if this does not reproduce your issue it's going to be difficult to review for issues.

The error you shared up top sounds like it relates to reading from an Element. You'll need to review how your actual code differs from this sandbox to identify the potential issue. Are there other event handler or state not reflected here?

**Comment by lokomass** [comment]
Ok, after many searches, I found differents in PLIs versions of sandbox.
I've updated sandbox according to my locales versions, and I can reproduce the problem, so I think I use an older version that contains the bug.

Here is the updated sand : https://codesandbox.io/s/laughing-dew-ms7yh7?file=/src/index.js

To reproduce, you can open popup, close it, re-open it and type something in card input.

Thank you very much for helping.

**Comment by lokomass** [comment]
Upgrade to 2.1.0 fix this issue, thanks !
