### ISSUE TITLE
[BUG]: Google Pay wait payment stub appear in wrong moment

### ISSUE THREAD

**Issue by danilkinkin** [stripe/react-stripe-js#421]
### What happened?

On IOS Google Pay wait payment stub appear in wrong moment when I use `ExpressCheckoutElement` component.

I need to validate my custom fields to click pay button. Now I make it in method `onClick`, if my fields have errors I don't call `resolve()`. I searched your docs, but you not implement reject method, so I simply don't call anything. 

Anywhere its work good but on ios Google Pay show this stub:
<img width="442" alt="Screenshot 2023-07-27 at 12 26 53" src="https://github.com/stripe/react-stripe-js/assets/10831688/31e96b10-a771-4adc-b41a-a7fa68092026">

I think this stub show have to appear only after call `resolve()` callback method

### Environment

Safari IOS 16.4

**Comment by brendanm-stripe** [comment]
Hey @danilkinkin -- can you share the implementation details (code snippets) of your integration and how you use the express checkout element? I'd like to try to reproduce this and give you some guidance or file a bug internally if needed.

**Comment by danilkinkin** [comment]
Yep, of course. Also, I wrote on [discord server](https://discord.com/channels/841573134531821608/1134073883759214633) and we reproduced this bug there

```jsx
function GooglePayButton({ onPay, onValidateFields }) {
  const stripe = useStripe();
  const elements = useElements();

  const handleConfirm = async (event) => {
    if (!stripe) {
      // Stripe.js hasn't loaded yet.
      // Make sure to disable form submission until Stripe.js has loaded.
      return;
    }

    onPay({
      stripeElements: elements,
      stripe,
    });
  };

  const handleClick = ({ resolve }) => {    
    // I call external validation. If this function return `true` then all ok and we can pay
    if (onValidateFields()) {
      resolve();
    } else {
      // I really want call here reject() that say stripe for prevent click action
    }
  };

  return (
    <ExpressCheckoutElement
      options={{
        wallets: { applePay: 'never', googlePay: 'always' },
      }}
      onClick={handleClick}
      onConfirm={handleConfirm}
    />
  );
}
```

Steps:
1. Open in IOS Safari
2. Click Google Pay
3. If `onValidateFields()` return `false` (and not call `resolve()`), stub appearing anyway

Its solution works on all platforms, expect IOS, on IOS stub appearing too early. When `onClick` fired, but I think it should be happened after call `resolve()` callback.

**Comment by danilkinkin** [comment]
Also, I think it's intuitive when we have `resolve`, then we should have `reject` option. Or naming is wrong and method should name different. For example, `update` or `setOptions`

**Comment by brendanm-stripe** [comment]
Thanks for the details here! We're still looking into this and I can update here when we have something to share.

**Comment by danilkinkin** [comment]
Problem is actual

**Comment by danilkinkin** [comment]
Problem is actual

**Comment by danilkinkin** [comment]
@brendanm-stripe any updates?
