### ISSUE TITLE
[BUG]: i have an issue with msi implementation

### ISSUE THREAD

**Issue by Arturopaz19** [stripe/react-stripe-js#422]
### What happened?

I did setup MSI and enabled installments that are available in my React app
<img width="693" alt="Captura de pantalla 2023-07-29 a la(s) 16 37 26" src="https://github.com/stripe/react-stripe-js/assets/38510513/98949aeb-bdbc-4b7f-987f-4151e12490fa">

I followed the documentation that the Stripe team recommended to me via email: 
https://stripe.com/docs/payments/installments/meses-sin-intereses?platform=web&ui=api

I did various tests of the msi implementation, but in the response I get an empty array, where I should get the information of the "available installments"

I attach the components created in React:

this endpoint was created with express to get the client Secret from the paymentIntent with the information from the PaymentMethod:
<img width="519" alt="Captura de pantalla 2023-07-29 a la(s) 16 43 39" src="https://github.com/stripe/react-stripe-js/assets/38510513/b10e957a-8ed8-4546-b9b0-e66d195d29a2">

this component has a Submit function that creates a paymentMethod to send to the service that creates the new PaymentIntent
<img width="550" alt="Captura de pantalla 2023-07-29 a la(s) 16 43 54" src="https://github.com/stripe/react-stripe-js/assets/38510513/c4c8c2e3-7720-4f3d-9b1b-1859a6190d3a">

<img width="483" alt="Captura de pantalla 2023-07-29 a la(s) 16 44 16" src="https://github.com/stripe/react-stripe-js/assets/38510513/3b88721c-39b5-405b-a4aa-e6d32f6a45e0">
<img width="672" alt="Captura de pantalla 2023-07-29 a la(s) 16 44 29" src="https://github.com/stripe/react-stripe-js/assets/38510513/db42d87d-2b23-4618-b9dd-057b2a98824c">

Results of tests:

Response of PaymentMethod obtained to send it to the service that generates the PaymentIntent:
<img width="342" alt="Captura de pantalla 2023-07-29 a la(s) 16 44 56" src="https://github.com/stripe/react-stripe-js/assets/38510513/db5cf767-e4e5-44f8-b79a-644c5c8946b7">

when generating the Intent, the payment_method_options.card.installments.available_plans node, the array is empty:
<img width="466" alt="Captura de pantalla 2023-07-29 a la(s) 16 45 32" src="https://github.com/stripe/react-stripe-js/assets/38510513/971a608a-1f03-4dfc-9a5b-00dbb2578d7a">

The Stripe Support team I was in contact with via email told me to describe the Issue to them here on github

**Comment by brendanm-stripe** [comment]
It looks like the test `amount` value you're using is `1000` which would be MXN 10.00 and too low for MSI to be offered. Can you try a larger value like MXN 1500.00 (`amount=150000`) and see if you get the expected installment plan options?

**Comment by Arturopaz19** [comment]
thanks @brendanm-stripe it works for me 🎉🎉🎉🎉
I didn't remember how Stripe handles amounts 

One more question, can the PaymentElement component be used to collect the array of months without interest?
