### ISSUE TITLE
[BUG]: Conflicting documentation about <Elements>

### ISSUE THREAD

**Issue by pauldraper** [stripe/react-stripe-js#423]
### What happened?

The docs say

> Render an Elements provider at the root of your React app so that it is available everywhere you need it.
>
> https://stripe.com/docs/stripe-js/react#elements-provider

But also

> Once the stripe prop has been set, these options can’t be changed. If you want to use Payment Element, it is required to pass in the clientSecret.

And `clientSecret` is scoped to a specific PaymentIntent/SetupIntent.

---

So which is it?

One global `<Elements>` for the whole app and all payments?

Or one local one for each payment? 

Hopefully I'm not being dense....it just seems this library is shaped in a really weird way.

**Comment by brendanm-stripe** [comment]
Yes we recommend that inclusion of the Elements provider near the root to make sure you can leverage the hooks in any component that needs it. Certainly you could choose a more tightly scoped implementation as long as you're careful the stripe/element instance remain referencable.

As for the comment about `clientSecret`, this is a bit outdated now that you can use the payment element before creating an intent ([docs](https://stripe.com/docs/payments/accept-a-payment-deferred?platform=web&type=payment)).

I can raise this internally so we can revisit the language used here.
