### ISSUE TITLE
[BUG]: Security Vulnerability

### ISSUE THREAD

**Issue by mfernandes-alcumus** [stripe/react-stripe-js#424]
### What happened?

When I use stripe elements, it creates Iframe, as part of our security scan from netsparker its been advised that we put a sandbox attribute on the iframe however there is no documention to support this.

This is causing some concerns around the business with the use of Stripe, it'll be good if you have a workaround to resolve this or possible fix.

**Comment by brendanm-stripe** [comment]
There is no support for adding this to the iframes created and controlled by Stripe.js. If you have a specific security concern about this, please describe the vulnerability in detail to security@stripe.com and it will be investigated promptly.
