### ISSUE TITLE
[BUG]: PaymentElement with ExpressCheckoutElement and setup_future_usage parameter

### ISSUE THREAD

**Issue by billypap1** [stripe/react-stripe-js#425]
### What happened?

I have integrated PaymentElement & ExpressCheckoutElement to my ReactJS App but I have an issue.
My component structure is below: 

```
<div>
<ExpressCheckoutElement  onConfirm={this.handleSubmitExpressBtn} />
<PaymentElement
options={{
    wallets: {
        applePay: 'never',
        googlePay:'never'
    },
    fields: {
    billingDetails: {
        email: 'auto',
        name: 'auto',
        phone:'auto'
    }
}}}/>
</div>
```

When the form is rendered without the setup_future_usage to "on_session" or "off_session" it displays the 2 buttons (wallets - GPay and Paypal)  to the "ExpressCheckoutElement" and the PaymentElement displays only the card form. 

But if the setup_future_usage is "on_session"/"off_session" it displays in ExpressCheckoutElement only the Google Pay and in PaymentElement it displays Card and Paypal tabs. Even if I change the setup_future_usage to null, it doesn't return to previous state.

Without setup_future_usage
<img width="574" alt="Screenshot at Aug 02 00-29-46" src="https://github.com/stripe/react-stripe-js/assets/44657902/3159d8f6-bada-4e58-97f9-b0e24b3c4e29">

With setup_future_usage: "on_session"
<img width="564" alt="Screenshot at Aug 02 00-30-04" src="https://github.com/stripe/react-stripe-js/assets/44657902/b547c789-1aa6-4c0a-9b52-ac93f84da26e">

react-stripe-js: v2.1.1
stripe-js: v1.54.2

### Environment

Chrome 115.0.5790.114 on MacOs Venture 13.5

**Comment by brendanm-stripe** [comment]
Hey @billypap1 we've been looking into this and at this time the Express Checkout Element does not support setting up future usage for Paypal. It's expected behaviour for that to be unavailable in when you enable `setupFutureUsage`, and since this is possible with the Payment Element it's included there instead.

Can you say more about what you mean by:
> Even if I change the setup_future_usage to null, it doesn't return to previous state.

What are you trying to do and what are you expecting to see vs what actually happens?

**Comment by brendanm-stripe** [comment]
> Is there any way to prevent Paypal button to be rendered in PaymentElement?
No, because unlike the others you reference `paypal` is a separate payment method type you can include or not based on your payment method settings or specifying `payment_method_types`.
