### ISSUE TITLE
[BUG]: cant prefill email value for LinkAuthenticationElement

### ISSUE THREAD

**Issue by sauarts** [stripe/react-stripe-js#428]
### What happened?

checked everywhere, tried setting value, defaultValue, etc, dont know how i can prefill the email of the user in this LinkAuthenticationElement for react

**Comment by brendanm-stripe** [comment]
Hey @sauarts you should be able to provide this using `defaultValues.email` in the options you pass: https://stripe.com/docs/js/elements_object/create_link_authentication_element#link_authentication_element_create-options-defaultValues-email

**Comment by brendanm-stripe** [comment]
In HTML+JS apps, you'd provide the option like this:
```
linkAuthenticationElement = elements.create("linkAuthentication", {
    defaultValues: { email: 'default@example.com' }
  });
```

for React apps, you provide the options to the component:
```
<LinkAuthenticationElement options={{ defaultValues: {email: 'reactdefault@example.com'} }} />
```

You can preview a live demo of this here: https://react-stripe-js-defer-elements.glitch.me/payment
