### ISSUE TITLE
[BUG]: not compatible with @stripe/stripe-js@2.0.0 ?

### ISSUE THREAD

**Issue by boredland** [stripe/react-stripe-js#429]
### What happened?

The peer dependency indicates those not being compatible (points to `"@stripe/stripe-js": "^1.44.1",`. Is that true or just a matter of updating the peerDependency?

**Comment by Scott-Fischer** [comment]
I just had this same issue as well. 
I tried to update `react-stripe-js` and `stripe-js` at the same time to the following versions:
```
    "@stripe/react-stripe-js": "^2.1.1",
    "@stripe/stripe-js": "^2.0.0",
```

But I'm getting this error:
<img width="674" alt="image" src="https://github.com/stripe/react-stripe-js/assets/8835133/5e632e3c-9c48-4477-8843-42a7febd11d2">

**Comment by brendanm-stripe** [comment]
We're working on getting a release out to resolve this shortly, thanks for filing the issue!

**Comment by brendanm-stripe** [comment]
Version 2.1.2 resolves this peer dependency error: https://github.com/stripe/react-stripe-js/releases/tag/v2.1.2
