### ISSUE TITLE
Feature request: Render elements while stripe.js is loading, gives a way to handle loading and error states

### ISSUE THREAD

**Issue by hinok** [stripe/react-stripe-js#43]
#### Summary

> A brief of the new API, including a code sample. Consider where this feature
> would fit into our documentation, and what the updated documentation would
> look like.

```js
import React from "react";
import { Elements } from "@stripe/react-stripe-js";
import CardForm from "./../demos/CardForm";

const wait = n => new Promise(resolve => setTimeout(resolve, n));

const loadStripeAsync = () =>
  wait(3000).then(() =>
    import("@stripe/stripe-js")
      .then(module => module.loadStripe)
      .then(loadStripe => loadStripe("pk_test_6pRNASCoBOKtIshFeQd4XMUh"))
  );

const AsyncCardForm = () => (
//               I know that it may not be the best name for such behaviour
//                                              |
//                                              |
//                                              |
  <Elements stripe={loadStripeAsync()} aggresiveRendering>
    <CardForm />
  </Elements>
);

export default AsyncCardForm;
```

It'd be better for the user from the ux perspective to show `stripe elements` (`CardElement` etc) in a `loading`, `disabled`, `skeleton` state when `stripe.js` is loading.
It opens opportunity to load `stripe.js` on demand (150kb, 40kb[gzip] less for the whole website or app).

At the moment, `stripe elements` are not rendered until `stripe.js` is loaded.

**Demo:** https://codesandbox.io/s/react-stripe-js-cmm5m

#### Motivation

> Describe the problem you are trying to solve with this API change. What does
> this API enable that was previously not possible?

Better UX and showing user as quickly as possible the "most final" state of the UI.

#### Similar APIs

> Is this new API similar to an existing Stripe API? Are there similar APIs or
> prior art in other popular projects?

At the moment `stripe elements` are not rendered until `stripe.js` is fully loaded.
Developer may use simple conditions like `stripe ? <Loaded /> : <Loading />` to render some kind of loaders, spinners or even fake inputs or forms. The problem is that it's quite annoying to duplicate the exact look of `stripe elements`.

#### Alternatives

> How else could we implement this feature? Are there any existing workarounds
> that would offer the same functionality? Why should we chose this
> implementation over another?

Creating fake `stripe elements` by developers.

#### Scope

> Which interfaces will this apply to? For example, is this specific to one
> component, or does it affect all Element components? Does this set a precedent
> for future interfaces we'll add?

It will apply to all Element components.

Developer could choose the way how stripe elements should be rendered:
a) the current behaviour which means - render stripe elements when stripe is loaded
b) new behaviour which means - render stripe elements in disabled/skeleton state and when stripe.js is loaded, stripe elements are unblocked and ready to use by the user

This would also require a way to handle errors of loading `stripe.js`.

#### Risks

> Are there any security implications (for example, XSS)? What are some ways
> users might get confused or misuse this feature?

The most serious risk is what should happen if `stripe.js` fails to load, what if it's loading for a long time (10s, 15s etc).

**Comment by dweedon-stripe** [comment]
Hi @hinok,

I like this idea and have considered something like this before. I especially like the idea of doing it as an opt-in. This is a big feature, we would need this library to re-create some part of the options parsing that Elements does. I think, at most, we would render a simple placeholder that keeps the page from jumping when the real Element is mounted.

That said, you should be able to avoid a visible load time entirely by loading Stripe.js earlier in your flow. To utilize our fraud detection you should really load Stripe.js on every page (in the root of your React app). Ideally, it should have downloaded long before the user reaches your checkout page where Elements are rendered.

**Comment by hinok** [comment]
> That said, you should be able to avoid a visible load time entirely by loading Stripe.js earlier in your flow. To utilize our fraud detection you should really load Stripe.js on every page (in the root of your React app). Ideally, it should have downloaded long before the user reaches your checkout page where Elements are rendered.

I know about fraud detection and we load `stripe.js` for all users on every page. At the moment I want to change implementation in a such way that it will be loaded only for logged in users at certain part of the application (during order/payment flow).

Thank you very much for such quick response. Is there anything I can help you with?

**Comment by dweedon-stripe** [comment]
If you feel strongly about this feature, I would start by writing a companion library that is designed to render a placeholder for Elements. 

I would not wait around for us to implement this feature directly, but if there is a lot of demand for this kind of thing, we would definitely consider it.

**Comment by alexilyaev** [comment]
We're having trouble providing a good UX on mobile without knowing when the Stripe elements actually load.

```js
const stripePromise = loadStripe(process.env.STRIPE_PUBLISHABLE_KEY);

function PaymentForm() {
  const elements = useElements();

  return (
    elements && (
      {/* Form with Stripe elements here */}
    )
  );
}

function Payment() {
  return (
      <Elements stripe={stripePromise}>
        <PaymentForm />
      </Elements>
  );
}
```

The form UI loads but the actual Stripe elements in the iframe's take some time, creating a situation where the user is seeing a form but can't do anything with it and has no progress indication.

Having a way to know when the actual Stripe components have rendered is crucial to build the optimal UX.

**Comment by Sphinxs** [comment]
Same issue here. I want to block the `<Button type="submit"/>` if Stripes changes the status of `<CardElement />` to error, i.e the user has not informed a value value, but for now I can only do this at the `onsubmit = () => {}` function, which is not what I want cause I can't update the state and make a re-render / use reference to block another request...

**Comment by hofman-stripe** [comment]
> Having a way to know when the actual Stripe components have rendered is crucial to build the optimal UX.

@alexilyaev, you can use the [`ready` event](https://stripe.com/docs/js/element/events/on_ready) of each element to know when the element is fully loaded and able to accept user input. This event is available on all Element Component with the `onReady` prop.

@Sphinxs, this is not quite the same issue. While there is no aggregated validation at the `Elements` group level, you could listen to the [`change` event](https://stripe.com/docs/js/element/input_validation) of each individual element to make sure they contain a valid value. There is also the [`invalid` class for the `style` option](https://stripe.com/docs/js/appendix/style) of each element to help you change the appearance of the Element if invalid.

If these don't work for you, please let us know why. And if you have suggestions on other APIs we could provide to help handling invalid input, please let us know what you think those could look like.

**Comment by Darshan4114** [comment]
@hofman-stripe That was really helpful
This is how I implemented it
```
import {
  PaymentElement,
  useStripe,
  useElements,
} from "@stripe/react-stripe-js";
<PaymentElement
          id="payment-element"
          onReady={() => setIsLoading(false)}
        />
```

**Comment by Noitidart** [comment]
What about when stripe as loaded but then the iframe is shown and it fails to load, is it possible to detect and tell user to please reload. There is only `onReady`, in case of iframe not loaded due to network for instance, onReady never fires. Is there any event handler that fires?
