### ISSUE TITLE
[BUG]: Not Possible to hide Paypal in Express Checkout Element

### ISSUE THREAD

**Issue by zant23** [stripe/react-stripe-js#431]
### What happened?

I am using the ExpressCheckoutElement and am trying to hide only Paypal, but display GooglePay and ApplePay.. 

Unfortunately there is no option for that currently.  Or have i overlooked something?
Will you support that in the near future? 

Thanks for you help

**Comment by zant23** [comment]
I have solved it with specifying the payment methods explicitly in the Element options. 
Yet of course the automatic payment method was a lot more confinient to use. 

My use case is the following: 

I am using Stripe Connect and use two instances of Express Checkout buttons. 

As Paypal Checkout Button lags the support for direct charges for the time beeing. I am currently showing one instance f for Google Pay and Apple Pay with direct Charges enabled and one for Paypal directly connected to the account via publishable and  secretKey.

**Comment by brendanm-stripe** [comment]
Great, glad to hear you found something that works for you!

We're working on making automatic payment methods more flexible to support flows like yours :)
