### ISSUE TITLE
[BUG]: Visual bug on dark mode with tailwind

### ISSUE THREAD

**Issue by isaacdarcilla** [stripe/react-stripe-js#435]
### What happened?

Card details not visible on dark mode with tailwind.

Light mode:
![image](https://github.com/stripe/react-stripe-js/assets/22732118/4d98e4f5-fc7b-40da-859c-a52e263d8fbc)

Dark mode:
![image](https://github.com/stripe/react-stripe-js/assets/22732118/6a0cb2f5-61bd-4786-b641-e2f9b089ec59)

### Environment

Latest

**Comment by tylersmith-stripe** [comment]
The [Card Element](https://stripe.com/docs/js/elements_object/create_element?type=card) is rendered within an `iframe`, which means the contents are encapsulated from all CSS on your page (e.g., Tailwind). To style the Card Element, you will need to use the [Style Object](https://stripe.com/docs/js/appendix/style), passed as in the `options` of the Card Element `create()` method.

**Comment by isaacdarcilla** [comment]
Thanks, works now.

```js
<CardElement options={{
    style: {
         base: {
            color: localStorage.theme === 'dark' ? '#fff' : '#000'
         }
     }
}} id="card-element" />
```
