### ISSUE TITLE
[BUG]: Canno suppress the `name` field of `Address` element, particularly when using `afterpay_clearpay`

### ISSUE THREAD

**Issue by atrauzzi** [stripe/react-stripe-js#447]
### What happened?

![image](https://github.com/stripe/react-stripe-js/assets/115199/b9f92f54-db72-44ff-a919-b715ff81b935)

This is the default form that Stripe presents for Afterpay.  Unfortunately, I can't create a payment intent server-side using the captured payment method without address information.

I would like to capture the address information prior to submitting the payment method to my server, but now when I try to make use of the Stripe Address element, I end up getting the "name" field twice!

![image](https://github.com/stripe/react-stripe-js/assets/115199/1f8b5552-5973-4b51-8ed2-6171061b1470)

As a sidenote:  In general, the DX for the Afterpay element feels a bit disjointed, are we sure it can't be improved some?  Perhaps just have the regular Stripe payment element incorporate these required fields instead of requiring me to splice it in?  Would make for a much simpler experience, similar to Klarna.

**Comment by singh-sidharth** [comment]
I'll try contributing to this when I have time. I am looking to close some react js issues or my skills might go stale :-D Whom do I talk to about contributing?

**Comment by brendanm-stripe** [comment]
Hey @atrauzzi -- apologies for not replying sooner, having missed the initial challenge for the Afterpay & Payment Element feedback at the end.

While you cannot currently hide the `name` field of the address element, you _can_ hide the `name` field of the Payment Element. You can do this using the `fields` option ([ref](https://stripe.com/docs/js/elements_object/create_payment_element#payment_element_create-options-fields)):

```
fields: {
        billingDetails: { 
          name: 'never',
        }
    },
```

Note the remark that when doing this, you'll need to provide the values from the hidden fields with `confirmPayment` within `billing_details` ([ref](https://stripe.com/docs/js/payment_intents/confirm_payment#confirm_payment_intent-options-confirmParams-payment_method_data-billing_details)), and you'll encounter an error if this is not provided.

As for the higher level feedback, thanks for sharing that! We're currently looking at ways to make the Payment Element and Address Element more flexible for different use cases and integration preferences.

**Comment by brendanm-stripe** [comment]
In `mode=billing` I'd agree, and have filed feedback internally to address that. The Shipping address name though isn't necessary the same name as the name for the payment.
