### ISSUE TITLE
add example how to collect card country for postal code collection

### ISSUE THREAD

**Issue by ilovett** [stripe/react-stripe-js#45]
### Summary

I'm following the [example here](https://github.com/stripe/react-stripe-js/blob/master/examples/hooks/2-Split-Card.js) -- it collects postal code without element assuming the card is US.

A while back [react elements dropped support for the postal element](https://github.com/stripe/react-stripe-elements/issues/322#issue-412652228)

Now that Postal support is dropped... How can I know if the card is US or CA so I can mask or validate the postal input properly?

### Other information

- https://github.com/stripe/react-stripe-js/blob/master/examples/hooks/2-Split-Card.js
- https://github.com/stripe/react-stripe-elements/issues/322#issue-412652228

**Comment by dweedon-stripe** [comment]
Hi @ilovett, sorry this is creating extra work for you! I think the best solution is the one we use in [Checkout](https://stripe.com/payments/checkout). 

1. Attempt to determine your customer's country automatically from their IP
2. Show a country selector and auto-fill it (based on the previous step)
3. Use this value to show/hide/validate the postal input.

I like the idea of showcasing this explicitly in one of our demos, so I will leave this issue open.

**Comment by matheusazzi** [comment]
Hello @ilovett and @dweedon-stripe. I'm using the split form and having to deal with this case. 

As the `CardElement` can know if it must display the postal code field or not, I'm assuming there's something I can use on StripeJS to check it for me when using the split form, as the logic for it exists.
E.g., on `CardNumber` blur, I can call a function to check if postal code is necessary / card is from US/UK/CA. 

However, I didn't found anything regarding it in the docs, do you happen to know if that's possible?

Using IP isn't guaranteed as the user can be in another place using their card, it has these false positives. 
Having a country dropdown and then show or not the postal input adds another step that might impact conversion. It looks like the best option, for now, is always to display the postal code field and make it optional.
