### ISSUE TITLE
[BUG]: IntegrationError: You must pass in a clientSecret when calling stripe.confirmPayment()

### ISSUE THREAD

**Issue by ursnj** [stripe/react-stripe-js#457]
### What happened?

Getting bellow error even im passing clientSecret properly.

Uncaught (in promise) IntegrationError: You must pass in a clientSecret when calling stripe.confirmPayment().
    at re (v3:1:62596)
    at e._handleMessage (v3:1:67979)
    at e._handleMessage (v3:1:81593)
    at v3:1:65882

### Environment

Chrome 118.0

**Comment by brendanm-stripe** [comment]
Can you share more details about your integration? Which guide/pattern are you following?

Note that in the [intent-first flow](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements#add-the-payment-element-to-your-payment-page) that `clientSecret` is required, but using the [deferred-intent flow](https://stripe.com/docs/payments/accept-a-payment-deferred?platform=web&type=payment#add-the-payment-element-to-your-checkout-page) you don't need that until confirmation and instead provide appropriate configuration options for Elements and Payment Element.
