### ISSUE TITLE
Typescript error on getElement

### ISSUE THREAD

**Issue by davidhousedev** [stripe/react-stripe-js#47]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md)!

### Summary

I receive a Typescript error when I attempt to use `getElement` by passing in a `CardElement`

Here's a code snippet:
```js
const stripe = useStripe()
const elements = useElements()
const { error, token } = await stripe.createToken(
  elements.getElement(CardElement),
  {/* various data */ }
)
```

And this is the error I receive from Typescript:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'StripeCardElement' is not assignable to parameter of type 'StripeIbanElement'.
      Type 'StripeCardElement' is not assignable to type '{ on(eventType: "change", handler: (event: StripeIbanElementChangeEvent) => any): StripeIbanElement; on(eventType: "ready", handler: () => any): StripeIbanElement; on(eventType: "focus", handler: () => any): StripeIbanElement; on(eventType: "blur", handler: () => any): StripeIbanElement; update(options: Partial<...>...'.
        Types of property 'on' are incompatible.
          Type '{ (eventType: "change", handler: (event: StripeCardElementChangeEvent) => any): StripeCardElement; (eventType: "ready", handler: () => any): StripeCardElement; (eventType: "focus", handler: () => any): StripeCardElement; (eventType: "blur", handler: () => any): StripeCardElement; }' is not assignable to type '{ (eventType: "change", handler: (event: StripeIbanElementChangeEvent) => any): StripeIbanElement; (eventType: "ready", handler: () => any): StripeIbanElement; (eventType: "focus", handler: () => any): StripeIbanElement; (eventType: "blur", handler: () => any): StripeIbanElement; }'.
            Types of parameters 'handler' and 'handler' are incompatible.
              Types of parameters 'event' and 'event' are incompatible.
                Type 'StripeCardElementChangeEvent' is missing the following properties from type 'StripeIbanElementChangeEvent': country, bankNamets(2769)
index.d.ts(269, 5): The last overload is declared here.
```

The usage of the API seems to work, and from what I can tell of the type definitions the implementation shouldn't yield any errors.

I'm very much a Typescript novice, so my apologies if I've missed something obvious!

### Other information

Here are some of my package versions:

```
    "@stripe/react-stripe-js": "^1.0.0-beta.7",
    "typescript": "^3.7.5"
```

And the contents of my `tsconfig.json`, in case that helps

```
{
  "compilerOptions": {
    // because we're compiling with Babel instead of TypeScript
    // and we're only using TypeScript for type checking, we'll set "noEmit"
    // to true so running type checking doesn't generate any files.
    "noEmit": true,
    "baseUrl": ".",
    "jsx": "react",
    "allowJs": true,
    "esModuleInterop": true
  },
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

**Comment by dweedon-stripe** [comment]
Hi @davidhousedev,

Sorry you are seeing this! It looks like TypeScript is unable to decide which `createToken` signature to use. There are [several overloads](https://github.com/stripe/stripe-js/blob/master/types/stripe-js/index.d.ts#L259-L306). 

Unfortunately, I'm not able to reproduce this using your configuration. It might actually have something to do with the options you are passing through to the second argument. Can you set up a minimal reproduction? This [CodeSandbox](https://codesandbox.io/s/trusting-allen-xp4fq?fontsize=14&hidenavigation=1&theme=dark
) might be a good start.

**Comment by davidhousedev** [comment]
Your suspicion is correct! The attributes I was passing into the data object led to the error surfacing in the sandbox. Here's what I added:

```jsx
    const { error, token } = await stripe.createToken(
      elements.getElement(CardElement),
      {
        name: "cardHolderName",
        address_line1: "streetAddress1",
        address_line2: "streetAddress2",
        address_streetAddress1: "streetAddress1",
        address_city: "city",
        address_state: "state",
        address_zip: "zipCode"
      }
    );
```

**Comment by dweedon-stripe** [comment]
Ah! Remove `address_streetAddress1`, it is an invalid parameter and confuses TypeScript since it can no longer infer the type of the options hash (`CreateTokenCardData`). Hopefully there is a way we can make that error a little nicer.

**Comment by dweedon-stripe** [comment]
@davidhousedev did the above work for you?

**Comment by ChaseIndustries** [comment]
I'm also seeing this error when trying to pass a `CardNumberElement` to `createToken()` - according to the stripe docs, they highly recommend collecting name and address with the token request. Is there anything we can do to fix this?

**Comment by dweedon-stripe** [comment]
Yep, you should still be able to do that. What does the object that you are passing in as the second parameter to `createToken` look like?

**Comment by ChaseIndustries** [comment]
When I remove the address fields, typescript doesn't complain, but this is the code im trying to use:
`const tokenResponse = await stripe.createToken(elements.getElement(CardNumberElement), {
            'name': formFields.ccname.value,
            'address_line1': billingStreet1,
            'address_line2': billingStreet2,
            'address_city': billingCity,
            'address_state': billingState,
            'address_zip': billingZip,
            'address_country': 'US',
            'currency': 'USD'
})`

**Comment by hofman-stripe** [comment]
To help troubleshoot, would you be able to assign the data to a typed const:

```ts
import {CreateTokenCardData} from '@stripe/stripe-js';

const cardTokenData: CreateTokenCardData = {
            'name': formFields.ccname.value,
            'address_line1': billingStreet1,
            'address_line2': billingStreet2,
            'address_city': billingCity,
            'address_state': billingState,
            'address_zip': billingZip,
            'address_country': 'US',
            'currency': 'USD'
};
const tokenResponse = await stripe.createToken(elements.getElement(CardNumberElement), cardTokenData)
```

**Comment by ChaseIndustries** [comment]
Hey, that worked! Thank you for the help!

**Comment by hofman-stripe** [comment]
Ok now I'm confused as to why TypeScript was complaining in the first place. Any chance you could copy paste the original full TypeScript error here?

**Comment by ChaseIndustries** [comment]
Weird- when I revert back to how I had it I'm not seeing the error anymore. It was the same error that was posted above (expected a `StripeIbanElement`), but now that I restarted VSCode it's not complaining. I think it might have been an issue with my TS server. If I run into it again I will reply here.
