### ISSUE TITLE
[BUG]: Cookie without Consent

### ISSUE THREAD

**Issue by alissonpadua** [stripe/react-stripe-js#472]
### What happened?

Hello! Still about this issue https://github.com/stripe/react-stripe-js/issues/367 I do see a 3rd party cookie being set like in the image (in red):

![image](https://github.com/stripe/react-stripe-js/assets/7661852/36f20bae-4669-428b-9048-efdd8bc9e48b) 

I'm using the https://www.cookiemetrix.com/ to analyze my website.

I would like to know how to prevent Stripe to store this cookie before user consent ?

Thank you!

### Environment

Production

**Comment by brendanm-stripe** [comment]
You can optionally disable some additional advanced fraud related cookies as described here: https://docs.stripe.com/disputes/prevention/advanced-fraud-detection#disable-advanced-fraud-detection

Note that some cookies are required for Stripe.js functionality as described in the previous issue.
