### ISSUE TITLE
Support for react native?

### ISSUE THREAD

**Issue by aibrahim3546** [stripe/react-stripe-js#48]
Hi there, Stripe is an amazing payment gateway. I would like to know if this library support react-native also? if not, are there any library that support react native at the moment.

Thank you.

**Comment by dweedon-stripe** [comment]
Hi @aibrahim3546,

There is a community maintained library, [tipsi-stripe](https://github.com/tipsi/tipsi-stripe). We don't currently have any Stripe maintained libraries for React native, but it is something we are investigating.

**Comment by juddey** [comment]
React Native Support from Stripe would be very, very welcome.

**Comment by aibrahim3546** [comment]
Hi @dweedon-stripe 
Okay. Thanks for the information. Would really love if Stripe make an official one.

**Comment by juanjsebgarcia** [comment]
I'd also like to chip in that an official Stripe library for React Native would be fantastic

**Comment by crjacinro** [comment]
+1

**Comment by marlon-wiprud** [comment]
+1

**Comment by markymc** [comment]
+1 from me too. Ideally one with React Native Web support. :)

**Comment by ashok-kumar** [comment]
+1

**Comment by teamzz111** [comment]
+1

**Comment by rubinjohny** [comment]
this would be great!

**Comment by oh3vci** [comment]
+1

**Comment by apenab** [comment]
+1

**Comment by zRelux** [comment]
+ 1

**Comment by cltsang** [comment]
React Native is supported here https://github.com/stripe/stripe-react-native
