### ISSUE TITLE
[BUG]: PaymentElement onLoaderStart sometimes fails to fire

### ISSUE THREAD

**Issue by randypuro** [stripe/react-stripe-js#482]
### What happened?

Apologies, as it's difficult to create a reproduction since the failure is intermittent; however, we were able to reproduce the issue on our end with repetitive retries. We depend on `PaymentElement` `onLoaderStart` to show our UI, and occasionally this callback is not firing (although `onReady` still fires).

### Environment

Chrome 122.0.6261.94 MacOS 14.3.1

**Comment by wahba-stripe** [comment]
Hello! 

If you don't pass in `loader: always` to your [elements initialization](https://docs.stripe.com/js/elements_object/create#stripe_elements-options-loader), we might choose not to display it (e.g. form render optimization). We'll work on making the docs a bit more legible.

In the meanwhile if you depend on the loader, pass `loader: always` into the [elements provider options](https://docs.stripe.com/stripe-js/react#elements-provider).

**Comment by randypuro** [comment]
Ah, gotcha, that makes sense. Thanks for the clarification and apologies for the noise.
