### ISSUE TITLE
StripeCardElementOptions - add disabled property to classes

### ISSUE THREAD

**Issue by landsman** [stripe/react-stripe-js#492]
### What happened?

Please add a new property `disabled` to `StripeElementClasses` to let me change styles when I change `StripeCardElementOptions` to disabled = true.

Or propagate this disabled state as data attribute within a existing className (base, complete, ...)

Currently, it's not possible to style such a input eg. wrapper background with card input fields.

### Environment

https://docs.stripe.com/js/elements_object/create_element?type=card#elements_create-options-disabled

### Reproduction

See the example on screenshot: 

![Screenshot 2024-04-12 at 13 57 14](https://github.com/stripe/react-stripe-js/assets/3184228/74e019f7-d216-4b04-ac0b-7a098bfdea66)

I can change the background only for the fields, but not for the whole wrapper as you can see on Email input.

**Comment by awalker-stripe** [comment]
Hello! Thank you for the screenshots and information – I see where you're trying to do some customization based on when the Element is `disabled`. Unfortunately, we aren't really equipped to truly dive into your integration here on Github. Could you reach out to [Stripe Support](https://support.stripe.com/) for help? This will allow us to better dive into your particular integration and see if there's an option that can work.

**Comment by landsman** [comment]
> Unfortunately, we aren't really equipped to truly dive into your integration here on Github

It's a general thing. Nothing specific to my integration.

**Comment by landsman** [comment]
@awalker-stripe can you please resolve it here?

**Comment by fruchtose-stripe** [comment]
Hi @landsman. This looks like an integration question, and we aren’t able to answer those here on GitHub. Please reach out to [Stripe Support](https://support.stripe.com/) for help.

**Comment by landsman** [comment]
@fruchtose-stripe can you just move this "feature request" to product team? It's a general thing.

**Comment by fruchtose-stripe** [comment]
Hi @landsman. I have flagged this issue internally. In the meantime, you may want to connect with [Stripe Support](https://support.stripe.com/) for assistance with your integration.

**Comment by landsman** [comment]
Thank you. 
I don't need the assistance. 
I need support in JS SDK for this thing, that's all :)
