### ISSUE TITLE
It's not possible to get the billing address in shipping mode

### ISSUE THREAD

**Issue by IgorNoskov** [stripe/react-stripe-js#494]
### What happened?

I use AddressElement with shipping mode and PaymentElement. In such case there is Billing is same as shipping information checkbox. When I uncheck it, two fields appear, country and postal code. But there is no way to get the billing address. 

<img width="439" alt="Screenshot 2024-04-16 at 10 16 13 PM" src="https://github.com/stripe/react-stripe-js/assets/33629521/04142e6e-ad53-46c5-beb2-8a5f45654b98">

On AddressElement change it returns this object:

```
{
    "elementType": "address",
    "elementMode": "shipping",
    "value": {
        "name": "",
        "phone": "",
        "address": {
            "line1": "",
            "line2": null,
            "city": "",
            "country": "US",
            "postal_code": "",
            "state": ""
        },
        "firstName": "",
        "lastName": ""
    },
    "empty": false,
    "complete": false,
    "isNewAddress": true
}
```

On PaymentElement change it returns this object:

```
{
    "elementType": "payment",
    "collapsed": false,
    "empty": false,
    "complete": true,
    "value": {
        "type": "card"
    }
}
```

**Comment by brendanm-stripe** [comment]
The billing details collected by the Payment Element will be on the Payment Method attached to the Payment Intent after the payment is confirmed.

https://docs.stripe.com/api/payment_methods/object#payment_method_object-billing_details

**Comment by IgorNoskov** [comment]
> The billing details collected by the Payment Element will be on the Payment Method attached to the Payment Intent after the payment is confirmed.
> 
> https://docs.stripe.com/api/payment_methods/object#payment_method_object-billing_details

@bredmond-stripe, thank you for your answer, I've checked `stripe.confirmPayment` and `stripe.retrievePaymentIntent` methods return Payment Intent but without attached Payment Method, I see only payment method string id there.

<img width="398" alt="Screenshot 2024-04-17 at 5 51 27 PM" src="https://github.com/stripe/react-stripe-js/assets/33629521/c89c4e27-0403-4f82-bc0b-68e9df8ac514">

Documentation says:
<img width="699" alt="Screenshot 2024-04-17 at 5 50 14 PM" src="https://github.com/stripe/react-stripe-js/assets/33629521/74904fd0-c3ee-47d7-8971-ed5d349b11d2">

I didn't found a way to get Payment Method object.

**Comment by brendanm-stripe** [comment]
You can use [expansion](https://stripe.com/docs/expand) to have the `payment_method` returned as the object instead of the string ID: https://docs.stripe.com/js/payment_intents/confirm_payment#confirm_payment_intent-options-confirmParams-expand

```
stripe.confirmPayment({
  elements,
  confirmParams: {
    expand: ['payment_method'],
    return_url: 'https://example.com',
  },
})
```

**Comment by IgorNoskov** [comment]
> expand: ['payment_method'],

@brendanm-stripe, thank you so much! It works!
