### ISSUE TITLE
[BUG]: Test mode API is fetching archived products  -  Live mode is working perfectly

### ISSUE THREAD

**Issue by Ehtz** [stripe/react-stripe-js#496]
### What happened?

The issue still persists with NextJS14. It was rendering fine and now it just disappeared so wired...

Stripe API version: ``` apiVersion: '2023-08-16', ```

Stripe test dashboard is fine nothing to report... .env keys are the same as before and working. I can access Stripe Payment Page.

I haven't touched or refactored the card component just have been working with Stripe Webhooks.

I believe this occurred after i used: ```stripe trigger checkout.session.completed``` to test webhooks

### Environment

   "stripe": "^13.2.0",
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Ehtz** [comment]
Is this normal that with the triggering from CLI it creates products?

<img width="442" alt="image" src="https://github.com/stripe/react-stripe-js/assets/121399963/b94c3c3f-c2d0-47d2-94cb-c566586e7fa3">
<img width="998" alt="image" src="https://github.com/stripe/react-stripe-js/assets/121399963/7001cd0a-0b7c-4f96-9de2-6d1e03c20dec">

**Comment by Ehtz** [comment]
I have found the code where the issue is likely coming from:

``` async function loadPrices() {
  const stripe = new Stripe(`${process.env.STRIPE_SECRET_KEY}`, {
    apiVersion: '2023-08-16',
  });
  const userIp = await fetchIpAddress();
  const userCountry = await fetchIPData(userIp as string);
  const prices = await stripe.prices.list();
  console.log('Prices:', prices);

  const sortedPrices = prices.data
    .sort((a, b) => a.unit_amount! - b.unit_amount!)
    .filter(({ active, currency }) => {
      if (!active) return false;
      switch (userCountry) {
        case 'EU':
          return currency === 'eur';
        case 'US':
          return currency === 'usd';
        case 'UK':
          return currency === 'gbp';
        default:
          return false;
      }
    });
    
  console.log('Country:', userCountry);
  console.log('Sorted Prices:', sortedPrices);
  return sortedPrices;
}

```
Now Stripe is returning archived products and despite ```   if (!active) return false; ````

Investigating further as to why it is returning only archived products...

**Comment by Ehtz** [comment]
> Is this normal that with the triggering: `stripe trigger checkout.session.completed` from CLI it creates products?
> 
> <img alt="image" width="442" src="https://private-user-images.githubusercontent.com/121399963/326540626-b94c3c3f-c2d0-47d2-94cb-c566586e7fa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTAwMzUsIm5iZiI6MTcxNDQ4OTczNSwicGF0aCI6Ii8xMjEzOTk5NjMvMzI2NTQwNjI2LWI5NGMzYzNmLWMyZDAtNDdkMi05NGNiLWM1NjY1ODZlN2ZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNTA4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDdiYTUwODc1MmMzMzk5Y2YzZjljNjU1OWVhOTBmYjNlMjMwMDk0ZDZiYTkzMzhmZTFkMTcxZDM2NzgwMjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5rd0VTWF8luFKqHp4JXCBbdkjQjI2gv4ypzoTvYAI7U"> <img alt="image" width="998" src="https://private-user-images.githubusercontent.com/121399963/326540825-7001cd0a-0b7c-4f96-9de2-6d1e03c20dec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTAwMzUsIm5iZiI6MTcxNDQ4OTczNSwicGF0aCI6Ii8xMjEzOTk5NjMvMzI2NTQwODI1LTcwMDFjZDBhLTBiN2MtNGY5Ni05ZGUyLTZkMWUwM2MyMGRlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNTA4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjhjYjhhNGEzNTY4ZjkzNWRkZTI5MjY1YTczN2E5MjNjYzBiNzRlZjI4N2E1ZWJmNWVjZGRlOGFkYTYyYmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SYTaD3lTcQk1DUMSHNb-6Y432g2RsmLIgxj49Ee8ZyY">

<img width="152" alt="image" src="https://github.com/stripe/react-stripe-js/assets/121399963/891e3a2f-290e-4fcc-b766-bc176bb8a75d">

**Comment by Ehtz** [comment]
Fixed by archiving all products and creating new ones in test dashboard

**Comment by brendanm-stripe** [comment]
Note that you can also specify `active=true` in your Prices List API request: https://docs.stripe.com/api/prices/list

**Comment by Ehtz** [comment]
> Note that you can also specify `active=true` in your Prices List API request: https://docs.stripe.com/api/prices/list#list_prices-active

Yes thanks for the observation, will implement this
