### ISSUE TITLE
Can i used my own input elements instead stripe elements

### ISSUE THREAD

**Issue by Ayan-Amir** [stripe/react-stripe-js#498]
### What happened?

how can i validate my card and create token by using my own input elements instead stripe elements

### Environment

Version 121.0.6167.184

**Comment by brendanm-stripe** [comment]
It is possible, but not recommended. You need to be aware that this has [PCI compliance implications](https://stripe.com/docs/security/guide#validating-pci-compliance) and you'll need to contact our [support team](https://support.stripe.com/contact) to have this [enabled for your account](https://support.stripe.com/questions/enabling-access-to-raw-card-data-apis).
