### ISSUE TITLE
Is distributing as ES6 intentional

### ISSUE THREAD

**Issue by daniel-lg1** [stripe/react-stripe-js#50]
Hi!

This library is currently distributed as ES6 which is a bit troublesome as we need to support IE11 and would like to avoid transpiling `node_modules` if possible. We did not experience this with `react-stripe-elements`, so this was an unexpected migration step.

Would you consider distributing the package as ES5 instead?

PS. Thank you for an excellent developer experience using Stripe.

**Comment by dweedon-stripe** [comment]
Nope. This is definitely a bug. Working on a fix.

**Comment by daniel-lg1** [comment]
Many thanks for the quick fix.
