### ISSUE TITLE
[BUG]: Unable to import useEmbeddedCheckoutContext 

### ISSUE THREAD

**Issue by alberto-htl** [stripe/react-stripe-js#505]
### What happened?

I am trying to unmount the EmbeddedCheckout using the `unmount` function. Checking the code I see there is a hook called `useEmbeddedCheckoutContext` to access to the context . This hook is not exported directly on the package index, is only exported on the component file `src/components/EmbeddedCheckoutProvider.tsx` Trying to import the hook using that file throws the following error:

./node_modules/@stripe/react-stripe-js/src/components/EmbeddedCheckoutProvider.tsx
Module parse failed: Unexpected token (10:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import * as stripeJs from '@stripe/stripe-js';
| 
> type EmbeddedCheckoutPublicInterface = {
|   mount(location: string | HTMLElement): void;
|   unmount(): void;

I suggest exporting this hook on the package index.

**Comment by brendanm-stripe** [comment]
Can you share more details about what you're to achieve in your integration? As far as I know that context is an internal concern of the component, and not meant to be used by you, but if you can point me to the reference you're following I can see if there's unexpected behaviour here.

**Comment by alberto-htl** [comment]
Hello @brendanm-stripe thank you for replying.

I am trying to remount the EmbeddedCheckoutProvider to fetch the checkout session with other params. I have manage to do it with the react state but I think will be more appropriate with the unmount function like the Stripe warning suggest on the console.

**Comment by brendanm-stripe** [comment]
Can you share a concrete example of what you mean? This sounds like an unsupported integration pattern, but I'm curious to understand more about it.

> fetch the checkout session with other params

Not entirely sure what this means either, so further explanation/example would be helpful.

**Comment by alberto-htl** [comment]
@brendanm-stripe I was trying to re-render the checkout in order to update the checkout session with new params, based on the user selection of the subscription type. I think is not the best pattern, or not the most common pattern, where all the information is gathered and confirmed before creating the checkout session. In this case the user could change the subscription type and see the new checkout update right away on the same page.

I managed to do this manually unmounting with a trick using useRef and conditional rendering, but I would prefer to use that function `unmount` that is available on stripe.js

**Comment by brendanm-stripe** [comment]
> update the checkout session with new params
Do you mean creating and re-mounting a _new_ Checkout session with updated line items and/or mode?

**Comment by alberto-htl** [comment]
@brendanm-stripe Yes exactly. If you could point me on the best way to do this with the library will be helpful. Thank you

**Comment by brendanm-stripe** [comment]
Gotcha! I think in that case you might be overcomplicating things slightly. You should be able to lean on React to destroy and mount a new embedded checkout by changing the `key` and providing a new client secret via `options`.

```
      <EmbeddedCheckoutProvider
        key={`session-quantity-${quantity}`}
        stripe={stripePromise}
        options={options}
      >
        <EmbeddedCheckout />
      </EmbeddedCheckoutProvider>
```

See an implementation: https://codesandbox.io/p/sandbox/react-stripe-js-forked-ftx96n?file=%2Fsrc%2Findex.js%3A54%2C1-60%2C34

**Comment by alberto-htl** [comment]
@brendanm-stripe You are right! Using `key` to force a re-render is great. Thank you so much for your support
