### ISSUE TITLE
[BUG]: Autofill with select password managers breaks PaymentElement component

### ISSUE THREAD

**Issue by KaneTesta** [stripe/react-stripe-js#514]
### What happened?

I've noticed that some users are experiencing difficulty when autofilling their card details in the `PaymentElement` component. Once autofilled, the whole component goes blank and throws the [following error](https://react.dev/errors/130?invariant=130&args%5B%5D=undefined&args%5B%5D=):

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.[missing argument]
```

Find below a screen share of me replicating this with LastPass on Chrome

https://github.com/stripe/react-stripe-js/assets/42565992/26ac0e25-e001-4b20-bb85-f2b59488b2e5

**Comment by KaneTesta** [comment]
Hi there,
Just wondering if there's any updates on this one?
@brendanm-stripe

**Comment by alexlande-stripe** [comment]
@KaneTesta sorry for the delay, are you still able to reproduce this issue? We had a separate report of this and rolled out a fix for it on July 17.

**Comment by KaneTesta** [comment]
It works, thanks
