### ISSUE TITLE
[BUG]: 3DS Challenge popup appearing below google pay popup 

### ISSUE THREAD

**Issue by jackhugh** [stripe/react-stripe-js#516]
### What happened?

When paying with google pay, any 3DS challenge popup appears below the google pay native UI so it cannot be interacted with.

### Environment

Windows - chrome

### Reproduction

Calling `paymentRequest.show()`

<img width="514" alt="Screenshot 2024-07-05 at 13 34 14" src="https://github.com/stripe/react-stripe-js/assets/24830612/af65b6c7-72d7-4aa0-9483-61f40064abff">

**Comment by brendanm-stripe** [comment]
Hey there, this suggests you've not integrated as we recommend in our guide here: https://docs.stripe.com/stripe-js/elements/payment-request-button?client=html#complete-payment

Note that there are _two_ `confirmCardPayment` calls, first with `{handleActions: false}` then without that, after calling `complete()` to dismiss the browser payment UI. Using this approach, you should be able to correct the issue.
