### ISSUE TITLE
[BUG]: The "Google Pay" button in ExpressCheckout isn't read correctly by screen readers

### ISSUE THREAD

**Issue by miduncan** [stripe/react-stripe-js#517]
### What happened?

As a user using a screen reader, when you navigate through the ExpressCheckout payment options, the Google Pay button is just read as "Frame 0". Apple Pay is read correctly as "Apple Pay".
![image](https://github.com/stripe/react-stripe-js/assets/55718965/d7457b67-611c-45e5-8ec5-2b44339be541)

Full repro steps:
1. Launch screen reader (this was tested using the Mac VoiceOver)
2. Go to a page with the `ExpressCheckoutElements` that has the Google Pay method
3. Focus the ExpressCheckoutElements and use either Tab/Shift+tab or CapsLock+LeftArrow/CapsLock+RightArrow to navigate the screen reader to the Google Pay button
4. Note that the button is simply read as "Frame 0"

I believe we are also seeing the cause of this bug in our aXe scanner:
![image](https://github.com/stripe/react-stripe-js/assets/55718965/cc178eac-0cd5-4dba-9650-89330c0919ab)

### Environment

macOS 10.15.7 using Chrome 126.0.X.X

**Comment by alexoser-stripe** [comment]
Thanks for reporting! VoiceOver actually does seem to be picking up the "Book with GPay" text for me.

![Screenshot 2024-08-02 at 4 49 26 PM](https://github.com/user-attachments/assets/a26d54bd-9721-42d0-9b79-9091184b790c)

Can you test if it happens with your screen reader as well in our docs at https://docs.stripe.com/elements/express-checkout-element just to confirm?

**Comment by miduncan** [comment]
I'm also seeing this fixed on our side in our website now! Thanks!
