### ISSUE TITLE
[BUG]: "City" input does not show up when selecting Japan as a country

### ISSUE THREAD

**Issue by brettgoulder** [stripe/react-stripe-js#519]
### What happened?

For some reason, the "City" input does not show up when selecting Japan as the country.

This can be demonstrated in the Address Element docs: https://docs.stripe.com/elements/address-element

Reproduction steps:
- Select "Japan"
- Enter in a Japanese postal code, e.g. "512-1216". 
Google may autofill it, which is fine, however the "city" name ends up in Address Line 1. In this case it'll say "Yokkaichi" which is the city name.

So the question is, should the "City" be included as separate input here or does it belong on Address Line 1? Would you be able to report this internally with your localization team?

### Environment

Chromium Engine Version 127.0.6533.73  on MacOS 14.6

### Reproduction

https://docs.stripe.com/elements/address-element

**Comment by brendanm-stripe** [comment]
Japanese address conventions are [quite different](https://en.wikipedia.org/wiki/Japanese_addressing_system) than North American addresses, and my understanding here is that "Address line 1" is being used in the generic sense to construct that address format. It (line 1) should not be considered as the same "house number and street name" as this is not generally applicable there.

That said, if the functionality is incorrect for representing a Japanese address with which you are familiar, please write in to our support team with that example and explaining the issue: https://support.stripe.com/contact

This relates to Address Element functionality within Stripe.js more broadly, and not any specific feature of the React elements to consume those which are made available by this library.
