### ISSUE TITLE
[BUG]: Accessibility issues with buttons from the Express Checkout Element

### ISSUE THREAD

**Issue by fedefunes96** [stripe/react-stripe-js#520]
### What happened?

When focusing the Google Pay button, the outline is not displayed correctly, it only appears at the top & bottom of the component.

Expected behavior:
1. The button should have a clear outline of the specified width
2. If using the dark button, the outline should have enough contrast

Screenshots:
<img width="256" alt="Screenshot 2024-08-02 at 5 28 52 PM" src="https://github.com/user-attachments/assets/92288b0a-85fa-4ac1-95a7-e9d4424d0197">

**Desktop:**
 - Browser: Google Chrome
 - Version: 126.0.6478.127

**Additional context**
This can also be seen in the demo on Stripe site: https://docs.stripe.com/elements/express-checkout-element#try-demo

### Environment

Chrome 126.0.6478.127 macOS 14.5

### Reproduction

1. Add a Google Pay button from the Express Checkout Element
2. Tab to focus that element
3. See that the outline is not showing as expected

**Comment by brendanm-stripe** [comment]
Thanks for reporting this. I've shared with the team internally to investigate the Google Pay button and others that don't appear to be getting the expected border on focus.

**Comment by miduncan** [comment]
To add to this, I'm also seeing this with the Apple Pay button and Amazon Pay button as well on the example page https://docs.stripe.com/elements/express-checkout-element#try-demo
