### ISSUE TITLE
[BUG]: Cannot change colorText for Block text

### ISSUE THREAD

**Issue by bombillazo** [stripe/react-stripe-js#521]
### What happened?

Currently there is no rule or property available to edit the Block text color, which results in unreadable text for things like the Stripe Link block
<img width="499" alt="image" src="https://github.com/user-attachments/assets/c1883c7a-3857-4ba7-8354-2da14a6022d7">

**Comment by bombillazo** [comment]
Hello, any update?

**Comment by alexlande-stripe** [comment]
@bombillazo Hey there, I just took a look at your integration. I was surprised to see this, I expected `color` to be a supported property for `.Block` rules.

I'm going to look into this and will try to give an update when I have more details, but in the meantime, I'd recommend updating your config with:

```js
variables: {
   // ...your variables
  colorText: '#fff' // or whatever color you want
}
```

Setting `colorText` will cover this `.Block` use case as well as others that you might not expect, so it will help future proof your integration. Note that we don't support alpha channels in color variables, so you won't be able to directly match the `'rgba(255, 255, 255, 0.85)'` color you're using within `rules`.

**Comment by bombillazo** [comment]
Ah got it, in this case the color comes from a theme variable which has using alpha channels, so it defaulted to that color. thanks for the info!

**Comment by bombillazo** [comment]
I will close this. I, too, expected `color` to work for `.Block`, but the root cause was the alpha color. That really can't be considered a bug; it's more like an improvement.
