### ISSUE TITLE
Stripe+AliPayment  Next Action url  doesn't work on mobile browser with live mode 

### ISSUE THREAD

**Issue by Asakaigg** [stripe/react-stripe-js#522]
### What happened?

I am integrating with stripe+Alipayment+wechat payment.
But it worked on test mode but when I switched it with live mode, the wechat payment didn't work.
For Alipayment, it  doesn't work on mobile.
we can't use the redirection for Ali payment due to our application workflow.
and so I have made popup window and visited the Next action url from there 
but it worked on chrome broswer
![image](https://github.com/user-attachments/assets/ce713475-7eb5-44ec-92c1-2c7c60a48038)
but it doesn't work with mobile broswer 
it showed invalid address on the mobile browser
![image](https://github.com/user-attachments/assets/d152dae6-7e18-4daa-8a76-8022afcc7337)
![image](https://github.com/user-attachments/assets/c0685d87-15b9-4d8a-85dc-a12c01172860)

**Comment by brendanm-stripe** [comment]
As this is not something related to functionality of React components made available in the library, please contract our support team for help with your integration: https://support.stripe.com/contact

Note that on mobile browsers, the customer is expected to have the native app for wechat/alipay installed. On desktop browsers, there is no expectation of installed apps, so a different flow is used. Mobile devices are expected to have the apps installed to redirect to.

**Comment by Asakaigg** [comment]
> As this is not something related to functionality of React components made available in the library, please contract our support team for help with your integration: https://support.stripe.com/contact
> 
> Note that on mobile browsers, the customer is expected to have the native app for wechat/alipay installed. On desktop browsers, there is no expectation of installed apps, so a different flow is used. Mobile devices are expected to have the apps installed to redirect to.

I think it is absolutely issue.
there is  a no way to prevent this error by checking the App installation status on the web app ?
