### ISSUE TITLE
[BUG]: Crash with "Error: Unknown country code: SD"

### ISSUE THREAD

**Issue by nguyenquocdathcmus** [stripe/react-stripe-js#524]
### What happened?

When selecting the country "SD" ( Sudan), the following error occurs: "Error: Unknown country code: SD".

### Environment

Browser: Chromium Engine Version 127.0.6533.73 
OS: MacOS 14.4.1

### Reproduction

Reproduction steps: 
1. Navigate to the country selection dropdown.
2.  Select "South Sudan" (SD) from the list of countries.
3. Observe the error: "Error: Unknown country code: SD".

### Question
Is "SD" a valid country code that should be supported, or is there an issue with how the country is being recognized in the system? How can I remove that country?

<img width="474" alt="Screenshot 2024-08-14 at 10 05 47" src="https://github.com/user-attachments/assets/cf2af1da-9de3-486c-a6e5-7e887f68be28">

**Comment by brendanm-stripe** [comment]
Thanks for reporting this, I've shared with the team internally to investigate.

**Comment by brendanm-stripe** [comment]
This should be fixed, can you recheck in your integration?

**Comment by brendanm-stripe** [comment]
Closing as I can no longer reproduce the error. Please let us know if this is still observed.
