### ISSUE TITLE
[BUG]: retrievePaymentIntent doesn't have metadata property

### ISSUE THREAD

**Issue by ne0c0de** [stripe/react-stripe-js#526]
### What happened?

Hi,

I'm using latest version of stripe/react-stripe-js

When I call ```retrievePaymentIntent``` method with payment intent client secret, the response doesn't include metadata that I sent when I created paymentIntent

However this property already exists in webhooks but my problem is on client side. How can I retreive this property from client side with retrievePaymentIntent method?

### Environment

Chrome Version 127.0.6533.90 (Official Build) (arm64)

**Comment by brendanm-stripe** [comment]
Hey @ne0c0de -- this is intentional. We only include `metadata` when objects are retrieved with a secret key.

> Stripe only returns metadata when you use a [secret key](https://docs.stripe.com/keys#obtain-api-keys) in your requests. We redact metadata from objects in response to publishable key requests, such as Stripe.js or Mobile SDKs client-side requests.

From: https://docs.stripe.com/metadata#requests

**Comment by brendanm-stripe** [comment]
You need to pass the PI id (`pi_123`) in the retrieve call, not the client secret (`pi_123_secret_456`).
