### ISSUE TITLE
Requesting Payment Element support for "hideIcon" option

### ISSUE THREAD

**Issue by annemirasol** [stripe/react-stripe-js#537]
### What happened?

We would like to be able to hide the card brand logos when using Payment element, as some merchants find the rotating logos to be inconsistent with the store theme, and possibly distracting customers during a critical step.

For clarity, we would like to have the flexibility to hide this:
<img width="503" alt="Screenshot 2024-10-18 at 1 04 15 PM" src="https://github.com/user-attachments/assets/9e661f08-a2a2-4ae5-8473-b7309958a828">

It looks like Card Element [supports a `hideIcon` option](https://docs.stripe.com/js/elements_object/create_element?type=card). Is this something we can add to Payment Element as well?

**Comment by brendanm-stripe** [comment]
Hey there, that's for the feedback. I've shared the feature request internally. As this is not specific to this library (it is functionality of the underlying Stripe.js Elements) I am closing the issue.
