### ISSUE TITLE
No support for on[KeyboardEvent] prevents use of escape key to close modals

### ISSUE THREAD

**Issue by kaylee42** [stripe/react-stripe-js#54]
Note: I'm currently using `react-stripe-elements`, but since it appears current development is happening here and issue is in both places, this is where I'm filing - if I should move it please let me know!

### Summary

I'm working on a site where payment options, and therefore the Stripe Elements, are often rendered in a modal. In order to be compliant with current [accessibility recommendations](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal) regarding modals, the escape key must close modals. However, when focus is in one of the Stripe elements, there is no way to detect the escape key press. It would be nice to have a prop option similar to that for `onChange`, `onFocus`, etc, that could be used to listen to keyboard events to assist in meeting accessibility guidelines.

Although I don't need it in this particular case, this could also potentially assist when developers need to do custom management of tab and shift+tab in modals in order to prevent keyboard focus from moving to the document underneath the modal.

**Comment by dweedon-stripe** [comment]
Hi @kaylee42 

This is a really great request. I think we should find a way to support this. We definitely want Elements to promote accessibility! That said, we definitely will not do it by adding broad support for KeyboardEvents. Exposing KeyboardEvents could leak a cardholder's payment information. Elements is intentionally designed _not_ to give your website information about what the cardholder is typing. We do this to keep your site [compliant with industry regulations](https://stripe.com/docs/security#validating-pci-compliance).

We definitely have some options though. We could add a new `"escape"` event to Elements, and support that in React Stripe.js with an `onEscape` prop. 

With regards to focus control, we already support `onFocus` and `onBlur` props. You should be able to implement the desired custom tab context using those events.

**Comment by kaylee42** [comment]
Amazing, thank you so much! I definitely understand the reasons behind not exposing keyboard events at large, but having the ability to hook into specific keyboard events like `Escape` would be incredibly helpful.

Also, even though I don't need them I do want to make the case for tab and shift + tab still! Focus and blur will occur both if a user clicks in/out of an element and if a user tabs in/out of an element, and you would never want to do custom focus management for a user who's navigating via a mouse. Additionally, focus/blur don't give you direction information, which the inclusion of both tab and shift + tab would. It would only be for cases where a Stripe element was the first or last focusable element in a modal AND a user was navigating via keyboard (using tab and shift + tab) that someone might need to manually handle focus to keep it inside the modal - ie, when someone tabs out of a Stripe element that's the last in a modal, you would need to move focus back to the first focusable element in the modal, but you wouldn't want to move focus for a mouse user who just clicked into a different input. I'm getting around this by using the `inert` polyfill, but that's not in particularly widespread usage right now. 

Again, thanks so much for the speedy response and for working on accessibility of Stripe elements!

**Comment by dweedon-stripe** [comment]
Hey @kaylee42,

I think this could be implemented by adding a hidden input after the Element. If the hidden input receives focus then send focus back to the first focusable element in the modal. We can also consider adding some metadata to `focus` and `blur` which might help with this.

**Comment by christopher-stripe** [comment]
We just published a new version of React Stripe.js (v1.1.0) that supports passing an `onEscape` prop to Element components. This can be used to close a dialog when a user presses the escape key. Thanks for reporting this @kaylee42!

We didn't add any mechanism yet for capturing `Tab` / `Shift-Tab` keypresses, since we weren't sure it was absolutely necessary to trap focus in a modal. The `inert` polyfill seems like one nice way to capture focus instead. Another approach I have seen is in [Reach UI](https://reacttraining.com/reach-ui/dialog/#aria-hiding-other-elements)—adding `aria-hidden` to non-dialog elements at the document root when the dialog is open.

**Comment by kaylee42** [comment]
Thank you so much @christopher-stripe!! Really appreciate this and looking forward to implementing this on our site
