### ISSUE TITLE
[BUG]: Multibanco Payment is not in type

### ISSUE THREAD

**Issue by ksamirdev** [stripe/react-stripe-js#542]
### What happened?

I was just having Multibanco Payment on my custom payment screen. But typescript says `Property 'confirmMultibancoPayment' does not exist on type 'Stripe'.ts(2339)`

I see docs for it https://docs.stripe.com/js/payment_intents/confirm_multibanco_payment

```
"@stripe/react-stripe-js": "^2.9.0",
"@stripe/stripe-js": "^4.10.0",
```

### Environment

macOS 15.1

**Comment by brendanm-stripe** [comment]
This type is part of `@stripe/stripe-js` (not this library, `react-stripe-js`) and this was recently added to version 4.9.0+

https://github.com/stripe/stripe-js/issues/645 
https://github.com/stripe/stripe-js/pull/666
