### ISSUE TITLE
loadStripe is not working with latest version

### ISSUE THREAD

**Issue by jmitchell33** [stripe/react-stripe-js#56]
I'm following pretty closely to the documentation, and am receiving the following error:

Error: Invalid prop `stripe` supplied to `Elements`. We recommend using the `loadStripe` utility from `@stripe/stripe-js`.

"@stripe/react-stripe-js": "^1.0.3",
"@stripe/stripe-js": "^1.0.2",

```
import {Elements} from '@stripe/react-stripe-js';
import {loadStripe} from '@stripe/stripe-js';

const stripePromise = loadStripe("pk_test_key");

<Elements stripe={stripePromise}>
     <PaymentForm/>
</Elements> 
```

**Comment by dweedon-stripe** [comment]
Hi @jmitchell33, this code looks pretty much correct...

Can you show me a minimum reproduction? This [minimal demo](https://codesandbox.io/s/react-stripe-js-minimal-t3cod) in CodeSandbox might be a good starting point.

**Comment by dweedon-stripe** [comment]
Do you see any other errors in the console?

**Comment by jmitchell33** [comment]
No.  Just a warning for the unmounted component (because this error is crashing the app).  Could it be related to also having <script src="https://js.stripe.com/v3/"></script>?  Is this still necessary?  If I console.log the promise, it shows as fulfilled.

**Comment by jmitchell33** [comment]
My PaymentForm had another <Elements> that I missed when migrating.  It's working after moving the loadStripe method to the PaymentForm.  Working as it should now.

**Comment by ramesh-gehlot** [comment]
There is <script src="https://js.stripe.com/v3/"></script> but how do I remove it. react places it there automatically

**Comment by HeyAmSoumya** [comment]
### Uncaught (in promise) ReferenceError: loadStripe is not defined
hi  , @dweedon-stripe I have the issue in my code , when I done **loadStripe** then it show me this error 

  this my getStripe.js ->>

`import { loadStripe } from "@stripe/stripe-js";


// import { loadStripe } from '@loadStripe/stripe-js'

let stripePromise;

const getStripe = () => {
  // IF ANY PROMISES IS NOT THERE SO GAVE THE PROMIES BY USE THE PUBLISH KEY..

  if (!stripePromise) {
    stripePromise =  loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY)
  }
  return stripePromise;
}

export default getStripe;`


and this my **Cart.jsx** where I gave the promise**(getStrip)** to the strip variable in **Cart.jsx** 

Here is my Cart.jsx code ->>
Here ( handleCheckout ) is a onClick event..

`const handleCheckout = async () => {
    const stripe = await getStripe();

    const response = await fetch('/api/stripe', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
          // THIS WILL GAVE ALL THE CARTITEMS INFORM JSON...

      body: JSON.stringify(cartItems),
    });

     //IN HERE IF THE RESPONSE - 500 MENAS ANY ERROR OCCURES 
    // THEN RETURN NOTHING..

    if(response.statusCode === 500) return;
   
    const data = await response.json();

    toast.loading('Redirecting...');
   // THIS THE CHECKOUT SHIPPING ID..
    stripe.redirectToCheckout({ sessionId: data.id });
  }`

so what should the error cause it?
