### ISSUE TITLE
Compatibility with react-redux

### ISSUE THREAD

**Issue by sholladay** [stripe/react-stripe-js#57]
I am in the process of migrating from the older [react-stripe-elements](https://github.com/stripe/react-stripe-elements) library, using the [migration guide](https://github.com/stripe/react-stripe-js/blob/master/docs/migrating.md).

In the migration guide, it is mentioned that we need to [replace `injectStripe()`](https://github.com/stripe/react-stripe-js/blob/d8e2b09c6abde8732908959205c2a15d00da7dbe/docs/migrating.md#3-usestripe-and-useelements-instead-of-injectstripe). However, it is not clear to me whether this is safe to do when the component is connected to Redux using `connect()` from [react-redux](https://github.com/reduxjs/react-redux).

The old `react-stripe-elements` library had a whole [Troubleshooting](https://github.com/stripe/react-stripe-elements#troubleshooting) section in the docs talking about how `injectStripe()` should be used on the _outside_ of `connect()`, as it would otherwise be unable to detect the context updates and so the component would fail to re-render.

As far as I understand, that issue from the Troubleshooting docs still applies to `@stripe/stripe-js`, as it also relies on context. Is that correct? Or do the hooks somehow solve it? Could you provide an example for using this library with `react-redux`?

Previously, I had code like this:

```jsx
const CheckoutForm = (props) => {
    const {stripe, elements} = props;
    // ...
};
```
```jsx
const CheckoutWithStripe = injectStripe(
    connect(null, {
        // ...
    })(
        reduxForm({
            // ...
        })(CheckoutForm)
    )
);
```
```jsx
<StripeProvider apiKey="pk_test_1234">
    <Elements>
        <CheckoutWithStripe />
    </Elements>
</StripeProvider>
```

The migration guide inidcates that I should replace that as follows:

```jsx
const CheckoutForm = (props) => {
    const stripe = useStripe();
    const elements = useElements();
    // ...
};
```
```jsx
const CheckoutWithStripe = connect(null, {
    // ...
})(
    reduxForm({
        // ...
    })(CheckoutForm)
);
```
```jsx
<Elements stripe={loadStripe('pk_test_1234')}>
    <CheckoutWithStripe />
</Elements>
```

**Comment by dweedon-stripe** [comment]
Hi @sholladay, 

The fact that we are using the new context API means this issue from `react-stripe-elements` goes away. React Redux implements `shouldComponentUpdate` \ `React.memo` which can block updates from the legacy context API (which is what `react-stripe-elements` used).

Take a look [at this demo](https://codesandbox.io/s/react-stripe-js-minimal-3qcsr). It blocks all updates from props, but Elements works fine (fill out the form and click pay, then check the console).

Note: You can change line #20 in `index.js` to `() => false` to start letting all updates through.
