### ISSUE TITLE
<IbanElement> default value

### ISSUE THREAD

**Issue by Toinouze** [stripe/react-stripe-js#67]
### Summary

Hi,

When our clients already have registered an IBAN, we would like to autofill the input with it.
Unfortunately there is no "value" option for `<IbanElement>`

Is there any way I can achieve this ?

Thanks

**Comment by dweedon-stripe** [comment]
Hi @Toinouze,

Since this is an integration question that is not specific to React Stripe.js. Can you reach out to [Stripe support](https://support.stripe.com)?

Thanks!
