### ISSUE TITLE
Focus/Keyboard Navigation broken in Safari + VoiceOver

### ISSUE THREAD

**Issue by toomstoxx** [stripe/react-stripe-js#74]
Both the Stripe `<CardElement>` and the individual card elements (`<CardNumberElement>`, `<CardExpiryElement>` and `<CardCvcElement>`) exhibit unpredictable and broken behavior in Safari while using VoiceOver. This does not happen in Chrome with VoiceOver---Chrome+VoiceOver works as expected.

I was not sure whether to submit this here or https://github.com/stripe/stripe-js as I believe these issues are not unique to `react-stripe-js`.

Note that I am seeing this behavior using macOS 10.15.4 and Safari 13.1.

There are multiple problems with keyboard focus/navigation. It's rather hard to describe exactly what is going on in text so I've included these videos. Unfortunately QuickTime does not include system sound when doing screen recordings, but I've included the VoiceOver window so hopefully it will be somewhat clear what is happening. It's not hard to recreate these to see (and hear!) for yourself in Safari/VO.

All of these happen on the page https://stripe.dev/elements-examples/ but I've also recreated them in my own code.

### Video 1: 
![video1](https://user-images.githubusercontent.com/9131705/77834878-5e5ab700-7105-11ea-9201-58c5fbaf3e8d.gif)
https://gfycat.com/rapidfearlessduck

I start with focus in the `Card Number` field (within the `<CardElement>`, I press `tab`, focus moves to the `Card Expiration` field, I press `tab` again, focus moves to the `CVC` field. So far everything is working as expected. Note that all field labels have been correctly read out by the screen reader.

Here's where things start going wrong: 

I press `tab` again. I expect focus to move from the `CVC` field to the `Pay $25` button. Instead, focus quickly cycles from  `Card Number` to `Card Expiration` to `CVC`.

I press `tab`. Once again, I expect focus to move from the `CVC` field to the `Pay $25` button. Instead, this time, focus moves to the `Address` field in the second form.

I've tested this with my own code and it seems that when focus leaves the `CardElement` it skips over the next tabbable element.

### Video 2: 
![video2](https://user-images.githubusercontent.com/9131705/77834976-45063a80-7106-11ea-884c-eaca96ce9aa9.gif)
https://gfycat.com/neighboringorganicbetafish
 
I start with focus in the `Card Number` field in the second form. I press `tab`. Focus moves to the `Card Expiration` field (as expected).  _However,_ Instead of reading the aria-label for the field `aria-label="Credit or debit card expiration date"` VoiceOver simply reads out `"New Line"` (you can see the newline character displayed on the VoiceOver window).

I press `tab` again. Focus moves to the `CVC`field. Again, instead of reading the aria-label, VoiceOver reads out `"New Line"`.

I press `tab` again. Instead of focus moving to the `Pay $25` button, it skips over into the `Name` field in the third form.

### Video 3:
![video3](https://user-images.githubusercontent.com/9131705/77834992-66672680-7106-11ea-9cf4-cab8ba52aaeb.gif)

https://gfycat.com/warlikerewardingbighornedsheep

I'm using the following code with react-stripe-js:

```javascript
const StripeExample = () => {
  const stripePromise = loadStripe('test');
  return (
    <div>
      <h1>Stripe Test</h1>
      <Elements stripe={stripePromise}>
        <CardNumberElement/>
        <CardExpiryElement/>
        <CardCvcElement/>
        <button>Checkout</button>
      </Elements>
    </div>
  );
};
```

I start with focus in the `<CardNumberElement>`. I press `tab` and *nothing happens*. Focus does not advance.

I press `tab` again. This time focus *skips over the `<CardExpiryElement>`* and moves to the `<CardCvcElement>`.

### Video 4:
![video4](https://user-images.githubusercontent.com/9131705/77834997-6cf59e00-7106-11ea-8b40-39c898ccbf0d.gif)
https://gfycat.com/enchantingpinkbuck

Using the same code as Video 3. Here I start with focus on the `Checkout` button and press `shift-tab` to *attempt* to traverse backwards through the fields. I'm honestly not sure how many times I pressed `shift-tab` but from the video I think it's clear that focus jumps all over the place. You can not get from the `Checkout` button to the `<CardNumberElement>` with 3 presses of `shift-tab` as would be expected.

### Video 5:
(This one's too long to embed.)
https://gfycat.com/bruisedzanyakitainu

Here I show VoiceOver with *Chrome*. Note that labels are read correctly when tabbing through fields, no fields/buttons are skipped, and shift-tab works as expected.

### Summary
I've identified the following issues in Safari/VoiceOver:

1. When inside the `<CardElement>` and the `CVC` field is focused. pressing `tab` loops focus through all the elements in the `<CardElement>` before refocusing the `CVC` field. The second time `tab` is pressed, focus skips over the next tabbable element.
2. When tabbing through individual card fields, instead of reading out the labels, VoiceOver simply reads `"New Line"`.
3. Using the `react-stripe-js` elements, focus *skips* over the next tabbable element (e.g. focus skips from `<CardNumberElement>` over `<CardExpiryElement>` and into `<CardCvcElement>`)
4. `shift-tab` behavior is broken

I hope this was clear. I'd be happy to elaborate on anything!

**Comment by mbarrett-stripe** [comment]
Hey @toomstoxx! Thanks for putting all of this together.

Safari 13 has an issue with programmatic focus changes into iframes, which all stripe elements are. This overall issue has come up quite a bit and we've reached out to Apple for a solution. You can see more information here in this thread: https://github.com/stripe/react-stripe-elements/issues/357

I'm going to close out this issue to keep the tracking consolidated to the other thread, but will note it in our list of asks about this. It will also be referenced over in that other thread for posterity.

**Comment by toomstoxx** [comment]
@mbarrett-stripe Thanks!

I just wanted to note, these problems *only* occur in Safari when VoiceOver is turned on. With VoiceOver turned off everything works as expected.

**Comment by dangaparker** [comment]
Hi @mbarrett-stripe, I was looking for updates on this issue but the other thread appears closed. This issue still appears to block our screen-reader users from entering payment details, which is hampering our a11y initiatives. Do you know if there is an active thread I can follow up in, or if this is still being worked on? Any additional info would be greatly appreciated. Thanks!
