### ISSUE TITLE
Getting access to stripe_token to pass to handleSubmit

### ISSUE THREAD

**Issue by yougotashovel** [stripe/react-stripe-js#77]
Hi,

I have a form with several fields, and a CardElement at the end.

I need a `stripe_token` field for a card source, to submitted with my form data for my server-side processing.

Is it possible to access a card token from the CardElement field?

Thanks, any help or pointers would be appreciated.

**Comment by dweedon-stripe** [comment]
Hi @yougotashovel,

This sounds like a general integration question. We try to limit the issues here for problems specific to these React bindings. [Stripe Support](https://support.stripe.com/) should be able to help you with this.
