### ISSUE TITLE
AuBankAccountElement bsbNumber and accountNumber missing

### ISSUE THREAD

**Issue by bangersandflash** [stripe/react-stripe-js#78]
When I log the onChange event, the bsbNumber and accountNumber are not part of the event object. The bankName and branchName however, appear as expected.

Is this the expected behaviour?

This is how I am logging the event:

<AuBankAccountElement onChange={(e) => {
                console.log(e)
            }} />

**Comment by hofman-stripe** [comment]
Yes, you can find the expected [properties of the change event in the Stripe.js reference](https://stripe.com/docs/js/element/events/on_change?type=auBankAccountElement).

If you have further questions on how to integrate with Elements, our [Stripe Support](https://support.stripe.com/) should be able to help you.
