### ISSUE TITLE
Support -webkit-text-security: disc; in CardCvcElement

### ISSUE THREAD

**Issue by ashleyyang0610** [stripe/react-stripe-js#80]
I'm looking for a solution to help me set the CVC content displayed as dots.
<img width="267" alt="截圖 2020-04-14 下午12 06 31" src="https://user-images.githubusercontent.com/22339489/79188347-5e6eec80-7e51-11ea-8fe9-3837457613b2.png">
<img width="262" alt="截圖 2020-04-14 下午12 06 19" src="https://user-images.githubusercontent.com/22339489/79188344-5d3dbf80-7e51-11ea-96c4-23ca84b7cb16.png">

At the begin, I found that `-webkit-text-security` CSS property is not supported in style option. So I was wondering to create my own CVC input component then set the CVC value when submit to create a stripe token.
```js
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';
import { Input } from 'components/Form';
import i18n from 'utils/i18n';

const CVCInput = styled(Input)`
    -webkit-text-security: disc;
`;

const CVC = ({
    onBlur,
    onChange,
    ...props
}) => {
    const [cvc, setCVC] = useState('');

    const validateCVC = () => {
        return {
            complete: !(cvc.length < 3),
            empty: cvc === '',
            error: !(/(^[0-9]{3}$)|(^[0-9]{4}$)/.test(cvc))
        };
    };

    const handleChangeCVC = (e) => {
        const target = e.target || e;
        const value = target.value.replace(/\D/g, '');
        const error = validateCVC();
        onChange(error, value);
        setCVC(value);
    };

    const handleBlurCVC = () => {
        const error = validateCVC();
        onBlur(error);
    };

    return (
        <CVCInput
            placeholder={i18n.t('payment:payment.form.cvc')}
            value={cvc}
            maxLength={4}
            onChange={handleChangeCVC}
            onBlur={handleBlurCVC}
            {...props}
        />
    );
};

CVC.propTypes = {
    onBlur: PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired
};

export default CVC;
```

Then I realize that the CVC value is not able to be set by myself due to its sensitivity. I can only use the stripe element for it. In the process I'm no doubt to touch the value inside. So the approach is failed. 

I've read the [similar issue](https://github.com/stripe/react-stripe-elements/issues/328) in react-stripe-elements before and understood the response you gave. 

However sometimes this request and the designs came from the whole team not only ourself. So I really need this.

I believe the simplest way to achieve it is extend the flexibility of input CSS property. Supporting `-webkit-text-security: disc;` is a quick and helpful way.

**Comment by hofman-stripe** [comment]
Browser specific CSS properties are a non-starter in a cross-browser library.

Regardless, this package is a wrapper around the Stripe.js library, and the feature would have to be implemented there, not in this package. As mentioned in the linked issue, this is something we believe would be detrimental to the user experience and we haven't heard a strong case for adding this besides "someone pushed for this requirement". We are not aware of any regulations requiring hiding the CVC from the user entering it.
