### ISSUE TITLE
What's the difference with React Stripe Elements

### ISSUE THREAD

**Issue by samuelcastro** [stripe/react-stripe-js#82]
### Summary

Hi, this is not a bug, I'm just wondering,  what's the difference with the React Stripe Elements (https://github.com/stripe/react-stripe-elements)? Why there are 2 different stripe react libs?

Thanks!

**Comment by fred-stripe** [comment]
Crossposting from my answer on the other issue:

> `react-stripe-js` is now out of beta and is the preferred path for anyone building on React 16+. `react-stripe-elements` is for React 15 and earlier. Both libraries will receive updates for new Elements as we add them, however, we intend for `react-stripe-js` to be the primary approach for new projects.

Hope that clears things up!
