### ISSUE TITLE
Payment with saved cards?

### ISSUE THREAD

**Issue by smblee** [stripe/react-stripe-js#83]
Hello, I am having trouble coming up with a way to enable users to pay with their saved cards under their Stripe customer profile. Could I get some help in implementing such a solution?

**Comment by dweedon-stripe** [comment]
Hi @smblee,

We try to focus on issues specific to these React bindings for Stripe.js in the issues here. This is more of an integration question that [Stripe Support](https://support.stripe.com) can help with.
