### ISSUE TITLE
Clear CardComponent

### ISSUE THREAD

**Issue by SCasarotto** [stripe/react-stripe-js#86]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md)!

### Summary
I would like to be able to clear the CardElement after submitting data however, it doesn't appear to be a way to get a ref. I am not seeing a way to get access to `elementRef` (previously: https://github.com/stripe/react-stripe-elements/issues/26) and it doesn't look like `createElementComponent` forwards Ref. Am I missing something? 

The only method I have found to work is to change the `key` on the `CardElement` component. While this works, it seems like accessing the intended properties to reset is a better solution.

**Comment by dweedon-stripe** [comment]
Hi @SCasarotto, 

You can use [`useElements`](https://stripe.com/docs/stripe-js/react#useelements-hook) and [`elements.getElement`](https://stripe.com/docs/js/elements_object/get_element) to obtain a reference to the underlying element.

```jsx
const PaymentForm = () => {
  const elements = useElements();
  
  const clearCard = () => {
    const cardElement = elements.getElement(CardElement);
    // ensure the Element is still mounted
    if (cardElement) {
      cardElement.clear()
    } 
  }
  
  // ...
}
```

**Comment by Safaid-Ansari** [comment]
how can we clear element value in angular
