### ISSUE TITLE
Cannot read property 'getElement' of null

### ISSUE THREAD

**Issue by EdwardBarton** [stripe/react-stripe-js#87]
### Summary

We recently have migrated from react-stripe-elements to react-stripe-js. After following the migration steps, we are receiving the the following error when attempting to load our app: `Cannot read property 'getElement' of null`

**Versions:**
@stripe/react-stripe-js: ^1.1.2
@stripe/stripe-js: ^1.4.0

Our form with a `CardElement` is broken into 3 files:

**index.js**
```js
// ...imports

// Confirmed correct API key
const stripePromise = loadStripe(process.env.REACT_APP_STRIPE_API_KEY)

const VenueCreate = () => (
  <Elements stripe={stripePromise}>
    <VenueForm />
  </Elements>
)
```

**VenueForm.js**
```js
// ...imports

const VenueForm = () => {
  const stripe = useStripe()
  const elements = useElements()
  const cardElement = elements.getElement(CardElement) // Cannot read property 'getElement' of null

  const onSubmit = async () => {
    const { token, error } = await stripe.createToken(cardElement, options)
  }

  return // form containing <VenueFields />
}
```

**VenueFields.js**
```js
// ...imports

const VenueFields =() => (
  <CardElement
    id="cardDetails"
    options={options}
    onBlur={handleBlur}
    onReady={handleReady}
    onChange={handleChange}
  />
)
```

I can't seem to troubleshoot what the issue is. Any assistance is appreciated. Thank you.

### Other information

Error occurs in latest versions of Chrome, Firefox, and Safari.

**Comment by dweedon-stripe** [comment]
Hi @EdwardBarton 

`loadStripe` loads Stripe.js and Elements asynchronously. The `useElements` hook will return `null` until Stripe.js has loaded. 

Solution: Move the call to `elements.getElement` into your `onSubmit` callback.

**Comment by EdwardBarton** [comment]
> Hi @EdwardBarton
> 
> `loadStripe` loads Stripe.js and Elements asynchronously. The `useElements` hook will return `null` until Stripe.js has loaded.
> 
> Solution: Move the call to `elements.getElement` into your `onSubmit` callback.

I'm so sorry, I must've overlooked that in the migration docs 🤦 

Thank you for your help!

**Comment by Ashik-Sarker** [comment]
Thank you so musch
