### ISSUE TITLE
How about Typescript support?

### ISSUE THREAD

**Issue by JanBaryla** [stripe/react-stripe-js#9]
Hi. I'm currently working on a React app that's going to handle payments through Stripe. I'm using Typescript and make heavy use of the React Hooks API. I know that https://github.com/stripe/react-stripe-elements is still technically the way to go when it comes to handling Stripe in React but I really like what you did with this library and after reading through the Beta docs, I'd love to be able to just use this library and be done with it.

I know you're using Flow for typing but it would be great if you could consider also exporting Typescript type definitions. Any chance you will be doing this any time soon? 

Would you even recommend trying to use this library over the legacy one at this moment in time? On one hand, I don't want to overcomplicate things by introducing a possibly flawed new library, but on the other, I would really just love to throw a useStripe and useElements into my component and be done with it.

**Comment by dweedon-stripe** [comment]
Hi @JanBaryla,

It's fairly safe to use this library, but I would recommend upgrading to the GA version once it is released (this is probably a few weeks out). 

Regarding Typescript, it is definitely something we are considering, but in order to do it properly, we will also need to add type definitions for all of Stripe.js.

**Comment by danseaman6** [comment]
@dweedon-stripe is adding type definitions something that you're currently pursuing? A type declaration file is currently available in NPM for the legacy library, but not this one.

**Comment by dweedon-stripe** [comment]
@danseaman6 @JanBaryla 

Sorry for the lack of updates here. We are actively working on adding first-party TS typings. I will post an update here when we have more to share.

**Comment by christopher-stripe** [comment]
Hello! We've just released TypeScript support in `v1.0.0-beta.5`.

Be sure to also upgrade the `@stripe/stripe-js` peer dependency to get the types for Stripe.js as well. If you have any feedback on the new types, feel free to drop it here or email [stripejs-feedback@stripe.com](mailto:stripejs-feedback@stripe.com). Thanks!

**Comment by danseaman6** [comment]
Hey @christopher-stripe and @dweedon-stripe, this is awesome, thanks for rolling it out!

I was working on implementing it today - I made an [issue](https://github.com/stripe/react-stripe-js/issues/11) a while ago for the hooks library about inlining  proptypes in react-stripe-js. Is stripe-js doing the same thing? I'm getting a rollup issue that looks like it could be there.

**Comment by christopher-stripe** [comment]
@danseaman6 We don't include `prop-types` in `@stripe/stripe-js`, but we did [recently tweak some configuration](https://github.com/stripe/react-stripe-js/commit/39b5c7c75b57d6d4e83f16aa0dfa31f18c404faa#diff-ff6e5f22a9c7e66987b19c0199636480) for bundling `prop-types` in this package that may be causing an issue. Want to open up another issue with some more info and we can debug from there?

**Comment by danseaman6** [comment]
https://github.com/stripe/react-stripe-js/issues/33 here you go

**Comment by davidhousedev** [comment]
This is great! I have a bit of a typescript noob question, though. I'm trying to add a `onChange` handler for the `CardElement` component, and would like to define the type of the custom `event` that gets passed in from Stripe. I could not, for the life of me, figure out how to import the type `stripeJs.StripeCardElementOptions`. Is this type just not made available for export, or is there something I'm missing?

Thanks!

**Comment by dweedon-stripe** [comment]
Hi @davidhousedev, the type you are looking for is [StripeCardElementChangeEvent](https://github.com/stripe/stripe-js/blob/master/types/stripe-js/elements/card.d.ts#L74). You should be able to import it like so:

```js
import {StripeCardElementChangeEvent} from '@stripe/stripe-js'|
```

**Comment by dweedon-stripe** [comment]
Closing so this does not become an aggregate issue for all types issues.
