### ISSUE TITLE
What's the point of CardExpiryElement and CardCvcElement

### ISSUE THREAD

**Issue by JacobParis** [stripe/react-stripe-js#91]
The examples highlight two main ways to integrate React Stripe with Stripe.js. The most common is to use the `CardElement` component, which allows the user to enter the card number, expiry, and cvc all in one component. The second method is to pass the `CardNumberComponent` instead, which lets you move the expiry and cvc input into separate inputs for UI designs that desire that.

An example of that approach is here: https://github.com/stripe/react-stripe-js/blob/master/examples/hooks/2-Split-Card.js

But in every example where that happens, including the one above, CardExpiryElement and CardCvcElement are unused. The inputs are placed on screen and they have stubbed event handlers showing that *something* could be happening there, but nothing is. Their values aren't sent to stripe at all, so maybe it's on the developer to provide client side validation? Are they just included for show?

**Comment by hofman-stripe** [comment]
The values are definitely sent to Stripe. When you pass one of the card elements in a split element form, Stripe.js internally retrieves the value of the other elements.

Sorry if this feels a little magical. For PCI compliance, when you get an pass an element to the Stripe.js SDK, the input value is not extracted then, but instead the element id is sent to an internal iframe, which collects the input values from the related element(s), before sending them to Stripe's servers.

**Comment by JacobParis** [comment]
Thank you that clears up my confusion

**Comment by EricWVGG** [comment]
It would be helpful if this was explained on the page at https://stripe.com/docs/stripe-js/react.

**Comment by coderdix** [comment]
> It would be helpful if this was explained on the page at https://stripe.com/docs/stripe-js/react.

2nd this
