### ISSUE TITLE
Add example with multiple forms

### ISSUE THREAD

**Issue by fernandobandeira** [stripe/react-stripe-js#94]
### Summary

Considering this example:
https://github.com/stripe/react-stripe-js/blob/master/examples/hooks/2-Split-Card.js

What would happen if there was two checkout forms there, would stripe still pick up the right CVC and Expiry for each Card Number or would we need to wrap each form with their own Elements?

I couldn't find an example like this neither an explanation in the docs about a situation like this, the recommended approach is to put the Elements on the top level of my app but if I have two checkout forms on a page I guess that would create problems...

**Comment by hofman-stripe** [comment]
Indeed, there should only be one element of each type in an `Elements` group. Consider the group as the equivalent of a form for Stripe Elements. You can add multiple `Elements` components to your page without issues.

I see that the [jsdoc does recommend](https://github.com/stripe/react-stripe-js/blob/e13fae556b1a667a5dfa1130c00d5ec4c2bc154e/src/components/Elements.tsx#L93-L94) to add the `Elements` component at the root, we probably should fix that. However, multiple forms is a pretty advanced integration, I'm not sure it warrants a dedicated example.
