### ISSUE TITLE
No example for createSource

### ISSUE THREAD

**Issue by juli1** [stripe/react-stripe-js#96]
### Summary

There is actually no example for `createSource` and I have difficulties using it. Would it be possible to have examples as to how to use it?

For now, all I did is to try to use the example on https://github.com/stripe/react-stripe-js  and replace `createPayment Method` with `createSource` and all I got is an error (`Unhandled Rejection (TypeError): cyclic object value`). 

The reference I found about `createSource` is on https://github.com/stripe/react-stripe-elements/blob/master/README.md and say that the element does not need to be passed. However, when doing that, I get the following error: `error Please use Stripe Elements to collect card details: https://stripe.com/docs/stripe-js#elements.`

Having examples would really help.

**Comment by dweedon-stripe** [comment]
Hi @juli1,

Sorry for the confusion here. We are moving from the Sources API to PaymentMethods and PaymentIntents and the documentation around React Stripe.js reflects this change.

Rest assured, Sources will continue to work. `createSource` in React Stripe.js works just like `createSource` in the underlying Stripe.js library ([docs](https://stripe.com/docs/js/tokens_sources/create_source#stripe_create_source-element)). 

```js
// use elements.getElement ala the createPayment method examples
const card = elements.getElement(CardNumber);
// When using createSource, the Element is passed as the first argument.
stripe.createSource(card, { owner: { name: "Jenny Rosen" } })
```

**Comment by juli1** [comment]
Thank you for the quick response. I was using the `elements.getElement(CardElement);`

Also, after some time, I did the following:

```
const card = elements.getElement(CardElement);
const { error, source } = await stripe.createSource(card);
```

and then `source.id` had a valid value. Any reason this might be a bad approach?

**Comment by dweedon-stripe** [comment]
That looks fine. The second data argument is optional.
