### ISSUE TITLE
Can't perform a React state update on an unmount component

### ISSUE THREAD

**Issue by galdil** [stripe/react-stripe-js#99]
I was integrating stripe in my website with very basic stuff:
Added a CardElement component and from the beginning of the development it give me this react error:
![Screen Shot 2020-05-19 at 15 41 24](https://user-images.githubusercontent.com/35641711/82327543-3c83ff00-99e7-11ea-952d-6c462f347515.png)

This is my implementation:
```
import React from 'react';
import { loadStripe, CustomFontSource } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';


const stripePromise = loadStripe(STRIPE_PK);

const PaymentPage = () => (
  <Elements stripe={stripePromise}>
    <PaymentsDetails />
  </Elements>
);


export default PaymentPage;
```

Thanks!

**Comment by hofman-stripe** [comment]
@galdil I cannot reproduce with the example given. Could you provide a codesandbox or similar with a reproduction?

**Comment by 1800Battery** [comment]
I get same error...  Whatever is in the react component using ComponentWillUnmount

**Comment by 1800Battery** [comment]
https://github.com/stripe/react-stripe-elements/blob/809258a8c72d945632a8e674696955e54186caee/src/components/Element.js   It's the ComponentWillUnmount here??
